### ISSUE TITLE
Add and support "identifier first + biometrics" to auth0_prompt terraform resource

### ISSUE THREAD

**Issue by ScreamingSum12** [auth0/terraform-provider-auth0#102]
Currently the [auth0_prompt](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/prompt) resource in the auth0 terraform provider does not support the "Identifier First + Biometrics" authorization profile. It has a boolean attribute for "Identifier First", but the authorization profiles now supported in auth0 are tertiary:

- Identifier + Password
- Identifier First
- Identifier First + Biometrics

### Proposed Solution

Modify the auth0_prompt terraform resource:
- remove the "identifier_first" boolean
- add an "authorization_profile" attribute that is tertiary (perhaps as an enumerated string) that supports Identifier + Password, Identifier First, and Identifier First + Biometrics.

Support consumption of this new attribute in the Auth0 Manan

### Alternatives and current workarounds

Currently no workaround available for codifying the Identifier First + Biometrics authorization profile in terraform.

**Comment by sergiughf** [comment]
Hey @ScreamingSum12 thanks for opening this issue. Our team will add support for this soon. Leaving the issue open until then.

**Comment by pablogamboa** [comment]
I am also interested in this feature @sergiughf ! Is this going to be part of the next release?

**Comment by sergiught** [comment]
Hey @ScreamingSum12 , @pablogamboa this feature is now available with the latest version of the provider: https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.34.0. Try it out and let us know if you encounter any issues:)
