### ISSUE TITLE
Can't trigger passwordless to turn on 

### ISSUE THREAD

**Issue by joemacrovesta** [auth0/terraform-provider-auth0#1040]
![image](https://github.com/user-attachments/assets/7ff2067b-f7cf-4add-93fd-b948da4ff262)
- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am attempting to enable the passwordless email connection in Auth0 using Terraform, but the connection does not activate in the dashboard (as shown in the attached screenshot). Even though the connection is correctly linked to my application via auth0_connection_client, the email passwordless toggle remains off, and the connection does not get enabled.

Terraform Configuration:
Below is the relevant Terraform code I’m using:

```
resource "auth0_connection" "passwordless_email" {
  strategy = "email"
  name     = "email"
  options {
    from                   = var.email_template_from_string
    subject                = var.email_template_subject_string
    syntax                 = "liquid"
    template               = var.email_template_body_string
    disable_signup         = false
    brute_force_protection = true
    non_persistent_attrs   = []
    auth_params = {
      scope         = "openid email profile offline_access"
      response_type = "code"
    }
    
    totp {
      time_step = 300
      length    = 6
    }
  }
}

resource "auth0_connection_client" "passwordless_email_client" {
  connection_id = auth0_connection.passwordless_email.id
  client_id     = auth0_client.my_app.client_id
}

```
The Problem:
The connection is successfully created, and the client linkage works, but the Passwordless Email toggle in the Auth0 dashboard (as seen in the attached screenshot) remains off.
I attempted to use enabled = true in the auth0_connection resource, but it appears that this is not a valid option for the resource.
As a result, I cannot activate the passwordless email connection, and it doesn't use the custom email template as expected.
Expected Behavior:
The passwordless email connection should be enabled and available for users to log in, and it should use the custom email template I’ve provided in the Terraform configuration.
Attached:
Screenshot showing the passwordless email toggle remaining off despite the connection being created.
Can you help me identify how to properly enable the passwordless email connection via Terraform?

### Expectation

to toggle on passwordless and enble my application for it

### Reproduction

read code 

### Auth0 Terraform Provider version

hashicorp

### Terraform version

      source  = "auth0/auth0"       version = "~> 1.3.0"     }

**Comment by duedares-rvj** [comment]
@joemacrovesta Circling back on this if you had a chance to try this out.

**Comment by duedares-rvj** [comment]
Hello @joemacrovesta 

Since I haven't heard back on this issue, I'm going ahead and closing it for now.
But please don't hesitate to re-open if the issue re-appears.

We'd be happy to triage and assist you!

Thanks again!
