### ISSUE TITLE
Can't add basic properties to auth0_form

### ISSUE THREAD

**Issue by Flaaj** [auth0/terraform-provider-auth0#1055]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I tried adding a form through terraform. 

this is the config:

```
resource "auth0_form" "marketing_opt_ins_form" {
  name = "Marketing Opt-Ins Form"

  start = jsonencode({
    coordinates = {
      x = 0
      y = 0
    }
    next_node = "step_marketing_opt_ins_form"
  })

  nodes = jsonencode([
    {
      alias = "OptIns Screen"
      config = {
        components = [
          {
            category = "BLOCK"
            config   = { content = "We'll send you marketing emails. Agree?" }
            id       = "rich_text_hdem"
            type     = "RICH_TEXT"
          },
          {
            category  = "FIELD"
            config    = { text = "<p>Yes and continue</p>" }
            required  = false
            transient = false
            id        = "marketing_consent_yes"
            type      = "LEGAL"
          },
          {
            category  = "FIELD"
            config    = { text = "<p>No and continue</p>" }
            required  = false
            transient = false
            id        = "marketing_consent_no"
            type      = "LEGAL"
          },
          {
            category = "BLOCK"
            config   = { text = "Submit" }
            id       = "next_button_feFY"
            type     = "NEXT_BUTTON"
          }
        ]
        next_node = "$ending"
      }
      coordinates = {
        x = 500
        y = 0
      }
      id   = "step_marketing_opt_ins_form"
      type = "STEP"
    }
  ])

  ending = jsonencode({
    coordinates = {
      x = 1500
      y = 0
    }
    resume_flow = true
  })

  languages {
    default = "en"
    primary = "en"
  }
}
```

Terraform errored, giving below error message.

```
Error: 400 Bad Request: Payload validation error: 'None of the valid schemas were met' on property nodes[0] ({description}). Inner errors: [ Payload validation error: 'Additional properties not allowed: components' on property nodes[0].config ({description}). (also) Payload validation error: 'Invalid value "STEP"' on property nodes[0].type. (also) Payload validation error: 'Additional properties not allowed: next_node,components' on property nodes[0].config ({description}). (also) Payload validation error: 'None of the valid schemas were met' on property nodes[0].config.components[2] ({description}). Inner errors: [ Payload validation error: 'Additional properties not allowed: transient,required' on property config.components[2] ({description}). (also) Payload validation error: 'Additional properties not allowed: transient' on property config.components[2] ({description}). ]. ].
```

It seems like I can't use any property name. Is it a bug or am I doing something wrong?

### Expectation

The plan should succeed.

### Reproduction

1. Paste the above auth0_form resource code fragment into your terraform file
2. Run a terraform plan from your terraform file.

### Auth0 Terraform Provider version

1.7.1

### Terraform version

1.2.0

**Comment by Flaaj** [comment]
@kushalshit27 
Hey, thank you very much, this worked. I don't understand though why? Can you point to a line that caused an error?

Also, how can I export as terraform file? I only have option to export as json.

**Comment by msinstil** [comment]
This issue persists for IMAGE Component, it seems to be not supported yet from terraform:

```
{
              id= "image_YTvB"
              type= "IMAGE"
              config= {
                src      = "someURL"
                width    = 200
                height   = 76
                position ="CENTER"
              }
              category = "BLOCK"
            },
```
Heres the error when adding an Image component to Form:
`
 Error: 400 Bad Request: Payload validation error: 'None of the valid schemas were met' on property nodes[0] ({description}). Inner errors: [ Payload validation error: 'Additional properties not allowed: components' on property nodes[0].config ({description}). (also) Payload validation error: 'Invalid value "STEP"' on property nodes[0].type. (also) Payload validation error: 'Additional properties not allowed: next_node,components' on property nodes[0].config ({description}). (also) Payload validation error: 'None of the valid schemas were met' on property nodes[0].config.components[0] ({description}). Inner errors: [ Payload validation error: 'None of the valid schemas were met' on property config.components[0] ({description}). Inner errors: [ Payload validation error: 'Additional properties not allowed: width,src,position,height' on property config ({description}). (also) Payload validation error: 'Invalid value "IMAGE"' on property type. (also) Payload validation error: 'Additional properties not allowed: width' on property config ({description}). ]. (also) Payload validation error: 'None of the valid schemas were met' on property config.components[0] ({description}). Inner errors: [ Payload validation error: 'Additional properties not allowed: width,src,position,height' on property config ({description}). (also) Payload validation error: 'Invalid value "IMAGE"' on property type. ]. ]. ].`
