### ISSUE TITLE
Failed to install provider - openpgp: key expired

### ISSUE THREAD

**Issue by 1FastSTi** [auth0/terraform-provider-auth0#1060]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

│ Error: Failed to install provider
│ 
│ Error while installing auth0/auth0 v1.7.1: error checking signature:
│ openpgp: key expired

### Expectation

should be able to use the provider

### Reproduction

Try installing the provider

### Auth0 Terraform Provider version

1.7.1

### Terraform version

1.6.0

**Comment by vatadepalli** [comment]
Facing the same issue. @1FastSTi is this the best place for this issue? Anyway we could escalate this?

**Comment by 1FastSTi** [comment]
I'm told from a friend that if you were to upgrade TF to 1.6.1+ of the 1.6.x flavor, that it works.

**Comment by duedares-rvj** [comment]
This is a terraform issue and the patch was released here:
https://github.com/hashicorp/terraform/pull/34004

Hope upgrading the terraform version shall resolve the issue. 
I'm closing this for now, but feel free to re open a new one. 
Thanks
