### ISSUE TITLE
Provider's PGP signing key is expired!

### ISSUE THREAD

**Issue by jstrassburg-ds** [auth0/terraform-provider-auth0#1061]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Attempting to install the provider results in:

```text
│ Error: Failed to install provider
│ 
│ Error while installing auth0/auth0 v1.7.1: error checking signature:
│ openpgp: key expired
```

### Expectation

I expected the provider to install successfully like it did quite recently.

### Reproduction

```bash
cat << EOF > ./config.tf
terraform {
  required_version = ">= 1.6.0"

  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = ">= 1.0.0"
    }
  }
}
EOF
terraform init
```

### Auth0 Terraform Provider version

1.7.1

### Terraform version

1.6.0

**Comment by jstrassburg-ds** [comment]
If you're experiencing this issue, try a newer Terraform version. 1.6.1 doesn't have this problem.

**Comment by 17jmumford** [comment]
This can also be resolved by updating to a more recent version of Auth0 Terraform Provider, such as 1.7.3
