### ISSUE TITLE
Manage MFA Factors

### ISSUE THREAD

**Issue by rpf3** [auth0/terraform-provider-auth0#124]
Is there a way to manage the enabled MFA factors as outlined [here](https://auth0.com/docs/secure/multi-factor-authentication/enable-mfa)?  The only thing I can find that deals with MFA is the guardian resource.

**Comment by sergiughf** [comment]
Hey @rpf3 👋🏻 , you can indeed use the `guardian` resource for this. 

Docs: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/guardian

Some examples that could help your use case:

```hcl
resource "auth0_guardian" "twilio_example" {
  policy = "all-applications"
  phone {
	provider = "twilio"
	message_types = ["sms"]
	options {
		enrollment_message = "enroll foo"
		verification_message = "verify foo"
		from = "from bar"
		messaging_service_sid = "foo"
		auth_token = "bar"
		sid = "foo"
	}
  }
}

resource "auth0_guardian" "default" {
  policy = "all-applications"
  phone {
    provider      = "auth0"
    message_types = ["sms"]
    options {
      enrollment_message   = "{{code}} is your verification code for {{tenant.friendly_name}}. Please enter this code to verify your enrollment."
      verification_message = "{{code}} is your verification code for {{tenant.friendly_name}}."
    }
  }
  email = true
  otp = true
}
```

Does this help?

**Comment by rpf3** [comment]
Thank you, yes.  Not sure how I overlooked the `otp` argument.  What about DUO integration?

**Comment by rpf3** [comment]
Will do, thanks for the info/help

**Comment by Arifahmed007** [comment]
is there a way to enable or disable the MFA adaptive risk accessment here. i dont see this option in guardian resource.
<img width="1221" alt="image" src="https://github.com/user-attachments/assets/3a56c293-f528-4c2a-98bd-cdacddb526da">
