### ISSUE TITLE
E-Mail documentation in Connection

### ISSUE THREAD

**Issue by bourbonfgiles** [auth0/terraform-provider-auth0#125]
### Describe the problem you'd like to have solved

In https://registry.terraform.io/providers/alekc/auth0/latest/docs/resources/connection there is no mention of how to structure the email resource.

### Describe the ideal solution

An example resource with any inline blocks that I can work from.

**Comment by sergiughf** [comment]
Hey @bourbonfgiles 👋🏻 , nice to chat with you again!

So a couple of things, the docs you're referencing are from a totally different provider than this one. The docs for the Auth0 provider are at https://registry.terraform.io/providers/auth0/auth0/latest/docs.

We do have an example on how to use the `email resource` that you can find at: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/email. 

Was this what you were looking for?

**Comment by bourbonfgiles** [comment]
And to you sir! :D Apologies, it's quite high up in the Google results. I'll make sure I keep it within that one.

So when I specify email in connection I have to use the email resource rather than the connection resource?

**Comment by sergiughf** [comment]
Ah, you're trying to use the `email` strategy on the `connection` resource not the actual `email` resource to set up a new email provider. Now everything is a lot more clear, apologies for the confusion. 

The docs for the connection resource are indeed these ones: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection. 

Here's an example config:

```hcl
resource "auth0_connection" "email" {
	name = "Acceptance-Test-Email-{{.random}}"
	is_domain_connection = false
	strategy = "email"
	options {
		disable_signup = false
		name = "Email OTP"
		from = "Magic Password <password@example.com>"
		subject = "Sign in!"
		syntax = "liquid"
		template = "<html><body><h1>Here's your password!</h1></body></html>"
		brute_force_protection = true
		totp {
			time_step = 360
			length = 4
		}
	}
}
```

**Comment by sergiughf** [comment]
Make sure you also check https://auth0.com/docs/authenticate/passwordless/authentication-methods/email-otp for the docs on the correct tags to use within the body template.

**Comment by bourbonfgiles** [comment]
Thank you so much @sergiughf 

I'll pop this into our module now.

**Comment by sergiughf** [comment]
Awesome @bourbonfgiles, I'm closing this down then but in case you encounter issues please reopen this.
