### ISSUE TITLE
Creatinng a passwordless email connection does not turn on the radio button in the portal.

### ISSUE THREAD

**Issue by bourbonfgiles** [auth0/terraform-provider-auth0#136]
### Describe the problem

When declaring an email connection (listed as authentication > passwordless > email in the portal) it does move the radio button in the portal. 

Terraform plans, and successfully applies an auth0 connection of type email in our pipelines. 

### What was the expected behavior?

The radio button turns green and we can see the predicted outcome in the portal.

**Comment by congon4tor** [comment]
Adding a bit more information on this issue.
Our connection resource looks something like this:
```terraform
resource "auth0_connection" "email" {
  name = "Passwordless-Connection"
  strategy = "email"
  enabled_clients = ["client_id"]
  is_domain_connection = true
  options = []
}
```
After applying it I can see this connection through the API with no issues it looks like this
```json
{
  "id": "con_ID",
  "options": {
    "name": "Email",
    "totp": {
      "length": 6,
      "time_step": 180
    },
    "email": {
      "body": "<html><body><a href=\"{{ link }}\">{{ link }}</a></body></html>",
      "from": "{{ application.name }} <root@auth0.com>",
      "syntax": "liquid",
      "subject": "Welcome to {{ application.name }}"
    },
    "disable_signup": true,
    "non_persistent_attrs": null,
    "brute_force_protection": false
  },
  "strategy": "email",
  "name": "Passwordless-Connection",
  "is_domain_connection": true,
  "realms": [
    "Passwordless-Connection"
  ],
  "enabled_clients": [
    "CLIENT_ID"
  ]
}
```

And when visiting the Application I can see the connection toggled on in the connections tab.
However when navigating in the dashboard to Authentication > Passwordless the Email toggle in not green.
We expect when we create a connection with startegy `email` that this toggle button in Authentication > Passwordless would be active and we would be able to view the settings for the connection.

**Comment by sergiughf** [comment]
Hey @bourbonfgiles, @congon4tor thanks for opening this. This is not actually a bug, let me explain what happens. 

The Auth0 Tenant will allow multiple email connections to be created through the Management API but the one you see in the passwordless connections tab:

![image](https://user-images.githubusercontent.com/28300158/164051794-a57ee6ad-7637-4589-9beb-f65bd6299aab.png)

in order for the UI to activate that, the connection name you're creating needs to be named "email" e.g. 

```hcl
resource "auth0_connection" "email" {
    name = "email"
    strategy = "email"
    enabled_clients = ["some_id_of_some_application/client"]
    is_domain_connection = true
}
```

So if you want to see that one enabled you'll have to have `name = "email"`

So if you already got that created, make sure to import that one. You can find the exact ID of it using the API Explorer https://auth0.com/docs/api/management/v2#!/Connections/delete_connections_by_id and then re-apply the enabled clients ids and the toggle will get green. 

Let me know if you encounter any issues.

**Comment by congon4tor** [comment]
Hi @sergiughf, thank you very much changing the name to `email` made the toggle go green in the UI

**Comment by sergiughf** [comment]
Happy to help!:)
