### ISSUE TITLE
In-line arguments in Provider block no longer recognized

### ISSUE THREAD

**Issue by danapczynski** [auth0/terraform-provider-auth0#146]
### Describe the problem

I'm in the process of updating from v0.26.2 of Alex's repo.

While I acknowledge that environment variables are the preferred place to keep configuration values like `domain`, `client_id`, and `client_secret`, it seems I'm *no longer able* to specify those values as in-line arguments to `provider`.

The documentation in this repo indicates that this should be possible: 
https://github.com/auth0/terraform-provider-auth0/blob/main/docs/index.md#example-usage

Screenshot:
![image](https://user-images.githubusercontent.com/4496588/164523337-66fe256e-430b-4f2f-b9d1-a9aa2ee1ea2e.png)

This implementation is also described [in Terraform's own docs](https://registry.terraform.io/providers/auth0/auth0/latest/docs#example-usage).

However, when I attempt to run a plan with config values set in this way, I receive output like this:

> Error: Missing required argument
> The argument "domain" is required, but was not set.
>
> Error: Missing required argument
> The argument "client_id" is required, but was not set.
>
> Error: Missing required argument
> The argument "client_secret" is required, but was not set.

If I give in and set these values as environment variables (`AUTH0_DOMAIN`, etc), the provider finds the values without an issue.

### What was the expected behavior?

It should be possible to specify provider configuration inline (even if we agree that one should not hardcode sensitive values into one's codebase)

### Reproduction

1. Open some existing code that uses the Auth0 Provider
2. Ensure that the `AUTH0_DOMAIN`, `AUTH0_CLIENT_ID`, and `AUTH0_CLIENT_SECRET` env variables are not being exported, and open a command prompt
3. Back in your provider code block, set those values as shown in the screenshot above (keyed as `domain`, `client_id`, `client_secret`)
4. Attempt a `terraform plan`

### Environment

Tested the above on v0.29 and v0.30 of `terraform-provider-auth0`, and the issue is present in both.

The issue was not present in v0.26.2 of the old repo, but I've not tested against later versions from that repo.

**Comment by sergiughf** [comment]
Hey @danapczynski I tested this with v0.30.0 and I wasn't able to reproduce. Can you confirm your terraform config looks something similar to:

```hcl
terraform {
    required_providers {
        auth0 = {
            source  = "auth0/auth0"
            version = "0.30.0"
        }
    }
}

provider "auth0" {
    debug = "true"
    domain = "someDomain"
    client_secret = "someSecret"
    client_id = "someClientID"
}
```

?

**Comment by bartvanackooij** [comment]
Hi,

I'm currently running into the same issue and the same as @danapczynski while upgrading from alexkappa's provider v0.26.2 to v0.30.0 . 

```
│ Error: Missing required argument
│ 
│ The argument "client_id" is required, but was not set.
╵
╷
│ Error: Missing required argument
│ 
│ The argument "client_secret" is required, but was not set.
╵
╷
│ Error: Missing required argument
│ 
│ The argument "domain" is required, but was not set. 
```

And I can confirm my config looks exactly like the snippet you posted @sergiughf and these values are set. 

I also tried different (older) version of the auth0/auth0 provider (v0.27.0), but same results.

**Comment by bartvanackooij** [comment]
My issue is resolved, I overlooked something small and simple. But perhaps it might point someone in the right direction:

Our issue was having different versions of the provider in the config. In our setup we have a separate repo with a terraform module called `auth0-module-x`.  Here we updated the official provider and version to `v0.30.0` . 

But we call and configure this `auth0-module-x` from another repo. Where we did not update the provider in the provider.tf file. 

Which caused the aforementioned `Missing required argument`

**Comment by danapczynski** [comment]
Thanks all, for the assistance! Yes, our issue turned out to be a similar to the one described by @bartvanackooij — we had some overlapping config files for our module, and only one of them was updated to point to the newer version of the provider.

Once I set the uncaught reference to the newer version, things started working as expected.

**Comment by cmeury** [comment]
For anyone arriving here from Google; it might also be an existing Terraform state (local or remote) referencing the old provider.
