### ISSUE TITLE
Support explicit audience value

### ISSUE THREAD

**Issue by tadhglewis** [auth0/terraform-provider-auth0#148]
### Describe the problem you'd like to have solved

Currently you cannot explicitly set a `audience` when setting up the provider, you can only set the `domain`.

This makes it impossible to use terraform if you are using a custom domain and the `auth0.com` domain is not publicly accessible

### Describe the ideal solution

Add support for the following figuration with an optional audience property
```
provider "auth0" {
  domain = "<domain>"
  audience = "<audience>"
  client_id = "<client-id>"
  client_secret = "<client-secret>"
  debug = "<debug>"
}
```

### Alternatives and current workarounds

None

### Additional context

node-auth0 supports this already - https://github.com/auth0/node-auth0 / https://github.com/auth0/node-auth0/blob/master/src/management/index.js#L86

**Comment by sergiughf** [comment]
Hey @tadhglewis, thanks for opening this issue. For this to be available on the terraform-provider we first have to add it on the Go SDK https://github.com/auth0/go-auth0 that the provider leverages. We'll evaluate when to add support for this in the near future and update this issue once that's available:) Thanks for your patience!

**Comment by tadhglewis** [comment]
@sergiughf is there any kind of eta for this? bit of a blocker for us :( if it's expected to take some time I might have a crack at some Go

**Comment by sergiughf** [comment]
Unfortunately I don't have any ETA on this as it wasn't something we were planning for in the immediate future.

**Comment by sergiughf** [comment]
Hey @tadhglewis would it be possible to describe your use case a bit better? Any information you can share would be helpful for us to be able to prioritize this accordingly. 

Specifically this part:
> This makes it impossible to use terraform if you are using a custom domain and the auth0.com domain is not publicly accessible

**Comment by tadhglewis** [comment]
@sergiughf I found a way around this by generating an access token before starting terraform and then using AUTH0_DOMAIN and AUTH0_API_TOKEN env vars instead of passing in just the client id / secret.

It would still be nice/cleaner to let Terraform handle the access token generation instead of us having to run a script beforehand and pass it in.

Re why we can't use auth0.com, we have a auth0.com tenant domain which isn't publicly accessible. We then have a custom domain which proxies to the auth0.com domain which is publicly accessible - this is for added security measures.

**Comment by sergiught** [comment]
Hey @tadhglewis 👋🏻 we've added support for this in the latest version of the provider. You can check the docs at:  https://registry.terraform.io/providers/auth0/auth0/latest/docs#audience

Please upgrade to v0.36.0 to make use of it and let us know if you encounter any issues with it.

**Comment by tadhglewis** [comment]
@sergiught thanks!
