### ISSUE TITLE
Use Custom Domain in Emails

### ISSUE THREAD

**Issue by rpf3** [auth0/terraform-provider-auth0#149]
### Describe the problem you'd like to have solved

Use Custom Domain in Emails

### Describe the ideal solution

I'm not sure if this is possible because I don't see it available in the management API documentation but it would be nice to be able to enable the "Use Custom Domain in Emails" option in the `auth0_custom_domain` resource.

**Comment by pablogamboa** [comment]
@rpf3 isn't this currently supported with auth0_tenant ? Something like:

```
resource "auth0_tenant" "tenant" {
  default_directory = auth0_connection.your_db.name

  friendly_name = "YourName"
  picture_url   = var.logo_uri
  support_url   = "${var.base_url}/support"
  allowed_logout_urls = [
    "${var.base_url}/auth0/logout"
  ]
  enabled_locales = ["en"]
  session_lifetime = 86400
  flags {
    disable_clickjack_protection_headers = false
    enable_custom_domain_in_emails = true
  }
}
```

**Comment by rpf3** [comment]
@pablogamboa thanks for that, not sure how I missed it there.

**Comment by sergiughf** [comment]
@pablogamboa, many thanks for stepping in and helping @rpf3 with this issue! Glad we were able to resolve this 💪🏻
