### ISSUE TITLE
Bad validation for tenant idle_session_lifetime and session_lifetime

### ISSUE THREAD

**Issue by tadhglewis** [auth0/terraform-provider-auth0#150]
### Describe the problem

I imported an existing Auth0 tenant and copied the properties from state to the resource however the idle_session_lifetime and session_lifetime were set to `0` however this validation seems to have a minimum of 0.01 - https://github.com/auth0/terraform-provider-auth0/blob/main/auth0/resource_auth0_tenant.go#L125

How come the value in Auth0 (`0`) is not supported in the Terraform config? Is this just bad validation in the provider or is this expected?

### What was the expected behavior?

Allow `0` values for idle_session_lifetime and session_lifetime

### Reproduction

- Import Auth0 tenant
- Copy state to resource

### Environment
n/a

**Comment by sergiughf** [comment]
Hey @tadhglewis, thanks for opening this issue. We made an improvement through https://github.com/auth0/terraform-provider-auth0/pull/193 that is now merged and will be available in the next release! As such we'll be closing this down but feel free to reopen in case of need.
