### ISSUE TITLE
Create permissions as a resource and reference them instead of duplicating them manually

### ISSUE THREAD

**Issue by jclaessens97** [auth0/terraform-provider-auth0#154]
### Describe the problem you'd like to have solved

Currently I need to duplicate permissions in roles instead of referencing them.

For example I have a `read:users` permission inside the role `admin` and `customer`.

Currently, I would have to duplicate a permissions block manually, which allows to introduce human error such as typo's and decreases maintainability:

```
permissions {
  resource_server_identifier = auth0_resource_server.api.identifier
  name                       = "read:users"
}
```

### Describe the ideal solution

I would love to be able to either reference to a permission or define a list of permissions that can be reused.

### Alternatives and current workarounds

Copy / Paste the permisson block manually in every role that needs it.

### Additional context

N/A

**Comment by sergiught** [comment]
Hey @jclaessens97 👋🏻 

Thanks for opening an issue with us and apologies for the delay in getting back to you. 

Would you be able to help us out a little in understanding your request by providing a full terraform example of how you are currently managing this and what would an ideal solution look like?

**Comment by sergiught** [comment]
Hey folks, we just released https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.48.0 with a new `auth0_resource_server_scope` (1:1) and `auth0_resource_server_scopes` (1:many) resources to manage an APIs scopes. Please check it out and let us know if you encounter any issues! Now you'll be able to reference those added API scopes (permissions) anywhere else in your other resources like roles and users.

Docs: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/resource_server_scope
