### ISSUE TITLE
Crashing after terraform import on ParseInt

### ISSUE THREAD

**Issue by alexander-r-arnold** [auth0/terraform-provider-auth0#157]
### Describe the problem
Stack trace from the terraform-provider-auth0_v0.29.0 plugin:
panic: Error reading level state: strconv.ParseInt: parsing "-9223372036854776000": value out of range
goroutine 63 [running]:
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).get(0xc0007520e0, 0xc00009fea0, 0x1, 0x1, 0xc00025bb08, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema/resource_data.go:537 +0x429
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).State(0xc0007520e0, 0xc00037c8c0)
    github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema/resource_data.go:335 +0x32f
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ShimInstanceStateFromValue(0xc00012aea0, 0x1fbe900, 0xc000817ba0, 0x1c5f220, 0xc00080f9b0, 0x1fbe900, 0xc000817ba0, 0x1c5f220)
    github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema/resource.go:196 +0x1ae
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00019f318, 0x1fbda90, 0xc000910300, 0xc000300480, 0xc00019f318, 0xc000910300, 0xc00046bba0)
    github.com/hashicorp/terraform-plugin-sdk@v1.16.1/internal/helper/plugin/grpc_provider.go:510 +0x265
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1d80000, 0xc00019f318, 0x1fbda90, 0xc000910300, 0xc000300420, 0x0, 0x1fbda90, 0xc000910300, 0xc000347000, 0xd92)
    github.com/hashicorp/terraform-plugin-sdk@v1.16.1/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008e41c0, 0x1fc7bf8, 0xc000319500, 0xc00068c400, 0xc0003a91a0, 0x2618ad0, 0x0, 0x0, 0x0)
    google.golang.org/grpc@v1.31.1/server.go:1180 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0008e41c0, 0x1fc7bf8, 0xc000319500, 0xc00068c400, 0x0)
    google.golang.org/grpc@v1.31.1/server.go:1503 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00030a190, 0xc0008e41c0, 0x1fc7bf8, 0xc000319500, 0xc00068c400)
    google.golang.org/grpc@v1.31.1/server.go:843 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
    google.golang.org/grpc@v1.31.1/server.go:841 +0x1fd
Error: The terraform-provider-auth0_v0.29.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

`terraform import` a client and client grant and then started receiving this after trying to `terraform plan`

### What was the expected behavior?
`terraform plan` works

**Comment by sergiughf** [comment]
Hey @alexander-r-arnold, thanks for opening this issue! It's quite unusual for an import to work and then terraform plan to fail as both the import and the plan will read from the api through a GET request. Would you be able to provide us with more info on this like the terraform config you're using?

**Comment by alexander-r-arnold** [comment]
I was using version 0.29.0. I also got this when using 0.32.0. Do you need any other information @sergiughf ?

**Comment by sergiughf** [comment]
Hey @alexander-r-arnold, thanks for getting back to this. The debug logs you provided don't really help unfortunately pin point the issue. Could you provide a reproducible terraform configuration for us? Is this happening only on the client resource or on the client grant or both? What values are you trying to import into it? Specifically the integer ones. Do you have any set on the tenant with value -9223372036854776000 ?

**Comment by sergiughf** [comment]
Glad to hear that @alexander-r-arnold, unfortunately I wasn't able to reproduce this here on my end either and considering you managed to solve it, I'll close this down. Please feel free to reopen in case you encounter this again and would be great to provide additional debug info for us to troubleshoot in case it happens.
