### ISSUE TITLE
Public data lookup for IP allowlists

### ISSUE THREAD

**Issue by bacoboy-doordash** [auth0/terraform-provider-auth0#164]
It would be nice to have a unauthenticated data lookup for the public IPs used by Auth0 so it could be directly used in terraform policies.

Rather than copy/pasting/watching for email notifications of changes to https://auth0.com/docs/secure/security-guidance/data-security/allowlist

**Comment by sergiught** [comment]
Hey @bacoboy-doordash, apologies for taking a while to get back to you. 

I do agree that it would be a great addition to the provider to have a data source perhaps with ip addresses. Unfortunately this is not something that is part of the [Management API](https://auth0.com/docs/api/management/v2), on which this provider relies on and as such we can't support this. We'll get this feedback through tho for consideration perhaps in a v3 of the API. 

For now what I'd suggest is to keep the list of ip addresses in a terraform variable that you could reference in various places of need in your configuration.
