### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by joshm91** [auth0/terraform-provider-auth0#167]
Hey @sergiughf 

Sorry to raise an issue for this but can a new release be published soon please? We're basically waiting to deploy our Auth0 TF until the Connection metadata feature  (72ed9a8192a5da42c035c7441785978c23032f0a) is released and I don't really want to go maintaining our own build of main.

Thanks!

**Comment by sergiughf** [comment]
Hey @joshm91, I'll take a look and get back to you to see what's holding up the new release. Apologies for the inconvenience!

**Comment by joshm91** [comment]
@sergiughf No worries at all, thanks a lot!

**Comment by sergiughf** [comment]
Hey @joshm91, we just created a new release with the latest updates 🥳 

https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.30.3

and is also available on the terraform registry: https://registry.terraform.io/providers/auth0/auth0/0.30.3

Thanks for your patience! 

I'll close this issue down now.
