### ISSUE TITLE
auth0_log_stream output: aws_partner_event_source 

### ISSUE THREAD

**Issue by georg-ikegps** [auth0/terraform-provider-auth0#168]
### auth0_log_stream output: aws_partner_event_source 

When creating a log stream connection with Amazon EventBridge, the resource doesn't seem to output the resulting `aws_partner_event_source`.
This makes it rather hard to create dependent resources like EventBridge rules.

### Describe the ideal solution

The resource has an output that can be used in other resources.

### Alternatives and current workarounds

My workaround is to manually create the log stream and import it into the remote state.
The `aws_partner_event_source` is then referenced as a local variable.

**Comment by brianhyder** [comment]
I tested this out and it seems to provide the output for the `aws_partner_event_source`.  It isn't immediately clear that the `sink` property is a list.

```terraform
terraform {
  required_providers {
    auth0 = {
      source = "auth0/auth0"
      version = "0.30.3"
    }
  }
}

provider "auth0" {
  domain = ""
  client_id = ""
  client_secret = ""
}

resource "auth0_log_stream" "stream" {
  name = "AWS Eventbridge"
  type = "eventbridge"
  status = "active"
  filters = []
  sink {
    aws_account_id = "AWS_ACCOUNT_HERE"
    aws_region     = "us-east-1"
  }
}

output "aws_partner_event_source" {
  value = auth0_log_stream.stream.sink[0].aws_partner_event_source
}

```

**Comment by georg-ikegps** [comment]
Thank you!
