### ISSUE TITLE
Connection icon_url not supported

### ISSUE THREAD

**Issue by JohnnyDeuss** [auth0/terraform-provider-auth0#186]
### Describe the problem

The `icon_url` option is missing for the `options` block in the `auth0_connection` resource. The result is that, if the `icon_url` is set directly through the management API, Terraform will wipe it the next time it updates that connection.

### What was the expected behavior?

The `icon_url` is not cleared.

### Reproduction

1. Create a custom OAuth2 resource in Terraform, with icon_url in the options.
2. Plan and apply (the icon_url won't be set)
3. Set the icon URL with the management API (works)
4. Plan and apply (the icon_url is cleared)

### Environment

- `terraform-provider-auth0`: 0.30.2

**Comment by willvedd** [comment]
Thanks for opening this ticket. It has been fixed with [v0.31.0](https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.31.0). Please update and give it a go!
