### ISSUE TITLE
Universal Login Customization

### ISSUE THREAD

**Issue by georg-ikegps** [auth0/terraform-provider-auth0#211]
### Describe the problem you'd like to have solved

We'd like to configure the Universal Login Customization via the terraform provider.
Currently we need to match dev and prod manually when using the customization.

### Describe the ideal solution

The universal login customisation is available as a resource

### Alternatives and current workarounds

Manually setting the settings

**Comment by sergiughf** [comment]
Hey @georg-ikegps, this is already supported but it's found under the tenant resource. Please check: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/tenant#universal-login and let us know if you need any help :)

**Comment by ldigiuseppe** [comment]
Hi @sergiughf, I see you can configure 2 colors from the terraform tenant resource. But on Auth0, there are more options like 
- Primary button label color
- Secondary button border
- Secondary button label
- Base Focus Color
Also on the website, we can configure the font, borders styles, and other options. 
![image](https://user-images.githubusercontent.com/64983/177450760-baa4f1ae-c484-432c-95ec-8552e6661ef9.png)

**Comment by sergiughf** [comment]
@ldigiuseppe For that level of customization you can use the branding resource:) https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/branding

**Comment by onliner10** [comment]
@sergiught How could we use this to customise colours other than primary or page_background? Those are not listed in the docs, and it seems in the sources that schema does not allow any other values.

Could you provide an example on how to update the default theme?

**Comment by ldigiuseppe** [comment]
We ended up doing it from the website UI, couldn't find the same options in the terraform resource.

**Comment by sergiught** [comment]
Hey folks, thanks for the continued discussion on this one. To give some extra info, what some of you are seeing on the universal login customization page is the **First Availability** of the new universal login page branding themes, meaning you'll be able to customize a lot more things than before. However this isn't generally available yet. 

For more info on our product release stages: https://auth0.com/docs/troubleshoot/product-lifecycle/product-release-stages. 

We'll be able to add support for this within the terraform provider as we get closer to the GA release. 

For now feel free to open a separate feature request issue for this on the repo 🙏🏻

**Comment by sergiught** [comment]
Hey folks 👋🏻 , Universal Login Branding Themes is now available through the latest version of this provider v0.36.0. Please upgrade to it to start using the `auth0_branding_theme` resource: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/branding_theme and let us know if you encounter any issues. You'll be able to start translating the configs from 
![image](https://user-images.githubusercontent.com/28300158/186457941-18e637b5-d2d6-4693-8963-929d79a14b07.png)
into your terraform config.
