### ISSUE TITLE
auth0_action dependencies not getting updated on version change

### ISSUE THREAD

**Issue by hemalshah-gradientedge** [auth0/terraform-provider-auth0#218]
### Describe the problem

When we update the version on a dependency on auth0_action, the updated version does not get applied and no changes are detected.

```
  dependencies {
    name    = "@org/package"
    version = "1.8.1"
  }
```

### What was the expected behavior?

Change in version should be detected and applied.

### Reproduction

1.  Set dependencies and a specific version:
```
  dependencies {
    name    = "@org/package"
    version = "1.7.0"
  }
```
2. Apply these changes
3. Update the version
```
   dependencies {
    name    = "@org/package"
    version = "1.8.1"
  }
```
4. Apply these changes.
5.

**Comment by sergiughf** [comment]
Hey @hemalshah-gradientedge thanks for opening this issue with us and for the reproduction steps. We'll be taking a look at this in the upcoming weeks.

**Comment by sergiughf** [comment]
Hey @hemalshah-gradientedge , we fixed this in https://github.com/auth0/terraform-provider-auth0/pull/247 and it will get released soon!
