### ISSUE TITLE
Add support for Twitter Connection Options

### ISSUE THREAD

**Issue by arcticShadow** [auth0/terraform-provider-auth0#224]
### Describe the problem

'twitter' strategy for auth0_connection resource is not applying the client_id or client_secret. 
Started on provider version 0.30.2 - tried 0.32.0 and 0.31.0, same issue, but experienced other issues on 0.32.0 as well. 

### What was the expected behaviour?

Expected `client_id` or `client_secret` to be set. (They set correctly using the management rest api)

### Reproduction

```terraform
resource "auth0_connection" "twitter" {
  name     = "twitter"
  strategy = "twitter"
  enabled_clients = [
    auth0_client.swagger_ui_app.id,
    auth0_client.consumer_web_app.id
  ]
  options {
    client_id                = local.social_apps.twitter.appId
    client_secret            = local.social_apps.twitter.appSecret
    set_user_root_attributes = "on_each_login"
  }
}
```
### Environment
Have tried with 0.30.2 - and 0.31.0 Currently cant get 0.32.0 to apply against my existing state due to other issues.

**Comment by arcticShadow** [comment]
I have raised a seperate but possibly related issue https://github.com/auth0/terraform-provider-auth0/issues/225  which covers problems i had updating to 0.32.0 version of the provider (wondering if that would fix this issue)

The new provider did not fix the issue - my client_id and client_secret are not setting from the provider. 

Also noticed, that on every apply - the entire options object (include attributes that are not related to twitter) is attempting to be set 9see below) This dosn't feel right. Letting it apply, and running plan/apply again, i get the same output (so its not applying i think)

```
# module.auth0.auth0_connection.twitter will be updated in-place
  ~ resource "auth0_connection" "twitter" {
        id                   = "<CONNECTION_ID>"
        name                 = "twitter"
        # (5 unchanged attributes hidden)

      ~ options {
          + allowed_audiences              = []
          + api_enable_users               = false
          + brute_force_protection         = false
          + client_id                      = "<MY_TWITTER_CLIENT_ID>"
          + client_secret                  = (sensitive value)
          + configuration                  = (sensitive value)
          + custom_scripts                 = {}
          + debug                          = false
          + disable_cache                  = false
          + disable_sign_out               = false
          + disable_signup                 = false
          + domain_aliases                 = []
          + enabled_database_customization = false
          + forward_request_info           = false
          + import_mode                    = false
          + ips                            = []
          + non_persistent_attrs           = []
          + pkce_enabled                   = false
          + requires_username              = false
          + scopes                         = []
          + scripts                        = {}
          + set_user_root_attributes       = "on_each_login"
          + sign_saml_request              = false
          + strategy_version               = 0
          + use_cert_auth                  = false
          + use_kerberos                   = false
          + use_wsfed                      = false
          + waad_common_endpoint           = false
        }
    }
```

For now - i need to remove the twitter connection - I cant get it working using the strategy (will try the oidc strategy)

**Comment by sergiughf** [comment]
Hey @arcticShadow, thanks for opening this. I was able to reproduce your issue and found out that actually we're not supporting setting the options for strategies other than:

```
const (
	ConnectionStrategyAuth0 = "auth0"
	ConnectionStrategyGoogleOAuth2 = "google-oauth2"
	ConnectionStrategyFacebook = "facebook"
	ConnectionStrategyApple = "apple"
	ConnectionStrategyLinkedin = "linkedin"
	ConnectionStrategyGitHub = "github"
	ConnectionStrategyWindowsLive = "windowslive"
	ConnectionStrategySalesforce = "salesforce"
	ConnectionStrategySalesforceCommunity = "salesforce-community"
	ConnectionStrategySalesforceSandbox = "salesforce-sandbox"
	ConnectionStrategyEmail = "email"
	ConnectionStrategySMS = "sms"
	ConnectionStrategyOIDC = "oidc"
	ConnectionStrategyOAuth2 = "oauth2"
	ConnectionStrategyAD = "ad"
	ConnectionStrategyADFS = "adfs"
	ConnectionStrategyAzureAD = "waad"
	ConnectionStrategySAML = "samlp"
	ConnectionStrategyGoogleApps = "google-apps"
)
```

We'll work on adding support for twitter options and all the other idp's very soon! I'll leave this issue open until then but I'll mark it instead as a feature instead of a bug.

**Comment by arcticShadow** [comment]
Thanks for confirming! 

I suspect that this is also the cause of the next issue I encountered trying to get Twitter to work via oauthq strategy (I don't see oauth1 on the list)

**Comment by sergiughf** [comment]
Yeah that's correct, the same is the case for oauth1. We're in the process of adding a lot of missed features to the provider at the moment and we're aiming at resolving this issue in the upcoming weeks. So stay tuned:)

**Comment by sergiught** [comment]
Hey @arcticShadow 👋🏻 , twitter connection options are now supported with the latest version of the provider: https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.34.0. Let us know if you have any issues with it.
