### ISSUE TITLE
Separate auth0_connection `options` blocks into provider-specific option blocks

### ISSUE THREAD

**Issue by reify-tanner-stirrat** [auth0/terraform-provider-auth0#234]
### Describe the problem you'd like to have solved
When I go to the [`options` documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection#options) for this provider, literally every option is listed as "(Optional)." My sense is that this is because no one option is common to all providers, so they're all technically "optional" because there's only a single `options` block that's used to configure every different provider.

It'd be much nicer from a DX standpoint to have options blocks that have clues to which values are actually necessary for a given provider, and it'd be nice to be able to discover this through means other than going through the Management UI for adding a particular kind of connection and manually discovering which values are and aren't required.

### Describe the ideal solution
Rather than a single options block:
```tf
options {
  foo = bar
  another_optional_thing = baz
}
```

I'd rather have top-level optional blocks, and then each of those optional blocks clearly delineate which values are and aren't optional:
```tf
# for an AAD connection
aad_options {
  client_id = "whatever"
}

# for a SAML connection
saml_options {
  signing_cert = "whatever"
}
```

#### Workarounds
I can find the characteristics of these values through manual inspection of the Management UI. I can also plan something and let it fail and 400 because the management API rejects things and iterate that way. Neither is very nice.

#### Alternatives
I'm not versed enough in terraform to know whether there are architectural alternatives to what I'm describing above.

### Additional context
I wouldn't call myself an expert in Terraform, so if there are good reasons for the API being the way that it is currently, I'm game to hear them and then document them.

**Comment by reify-tanner-stirrat** [comment]
> we'd be left with 50+ different blocks that have quite a big amount of duplication between them

Is the concern that this would make the provider (i.e. the backing code) hard to maintain? If there are ways to share the definitions between different kinds of blocks on the backend, that still seems like a sane tradeoff.

I agree that I wouldn't want to have to maintain all of the duplicated definitions separately.

**Comment by sergiught** [comment]
Hey @reify-tanner-stirrat as mentioned in https://github.com/auth0/terraform-provider-auth0/issues/238#issuecomment-1278695160 as well, a v3 of the API is on the roadmap and the connections resource will be reworked. As we aim at being as close as possible with the behavior of the API we'll defer this kind of work for then. As such we'll close this issue down, but rest assured feedback has been taken into account and is highly appreciated!

In the meantime we'll improve our documentation to specify in the examples all the fields that can be set for each type of connection and as well attach strategy options on the options fields in https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection#nestedblock--options. 

I created https://github.com/auth0/terraform-provider-auth0/issues/365 to focus just on this.
