### ISSUE TITLE
OIDC Connection type requires overspecification when discovery URL is provided

### ISSUE THREAD

**Issue by reify-tanner-stirrat** [auth0/terraform-provider-auth0#238]
## Note
I think this is really more a problem with the management API than it is the terraform provider, but I don't know where to open an issue to that effect. If there's a more appropriate place for this issue to be I'm happy to transfer it or have it transferred.

It also seems like this may be a difference between the management API flow (which I'm assuming is a single POST request) compared to how the UI handles it (which may include more steps?).

#### Expected
When I provide an `issuer`, I'd expect that between that and `discovery_url`, Auth0 would use the discovery URL to look up relevant pieces of information and use them directly, namely `authorization_endpoint` and `jwks_url`.

#### Observed
When I omit `authorization_endpoint` and `jwks_url` (both available at `discovery_url`), the management API 400s, saying that both are required.

### Describe the ideal solution
This also may be ignorance on my part of how OIDC works and how Auth0 interacts with OIDC connections, but it seems like if I provide a discovery URL, it should use the information provided by that URL, and I shouldn't have to specify it in the configuration.

It seems like if a an `openid-connection` endpoint is specificed, it [should have this requisite information](https://openid.net/specs/openid-connect-discovery-1_0.html#rfc.section.4.2).

### Alternatives and current workarounds
I was able to get to a complete configuration by hitting 400s until I had a complete TF description, then running `apply`, then `plan`ning again to see what other values were populated, adding those values, and then `apply`ing again.

It's not preventing me from getting work done, but the DX is frustrating.

### Additional context

Nothing off the top of my head.

**Comment by sergiught** [comment]
Hey @reify-tanner-stirrat 👋🏻 

Really appreciate the detailed description and the time put together to raise this with us. I completely agree with you that once a `discovery_url` is set, all the other information could be easily extracted from there without further input from the user. 

This is unfortunately something that the Management API doesn't account for in its current v2. However on the roadmap there's a v3 planned next (I don't have an ETA on when this will be done tho) that will greatly improve the behavior of all the resources and we will pass along this request as feedback to account for when reworking the internals of the API. As an extra suggestion you could as well open this within the community forums too, to gauge interest from other folks as well: https://community.auth0.com/c/apiv2/mgmt-api/28. 

However as this isn't something we can action on within the terraform provider itself, we'll be closing this issue down.

**Comment by willvedd** [comment]
**Update:** OIDC discovery is now supported on the Auth0 server-side so you no longer need to over-specify those connection details.
