### ISSUE TITLE
infinite_idle_token_lifetime/infinite_token_lifetime/idle_token_lifetime not longer work?

### ISSUE THREAD

**Issue by sergiughf** [auth0/terraform-provider-auth0#24]
From terraform-provider-auth0 created by [mattmillen888](https://github.com/mattmillen888): alexkappa/terraform-provider-auth0#337  

Have these features been deprecated?

  refresh_token {
    infinite_idle_token_lifetime = true
    infinite_token_lifetime = false
    idle_token_lifetime = 1296000
  }

as i now get:
An argument named "infinite_token_lifetime" is not expected here.
An argument named "idle_token_lifetime" is not expected here.
An argument named "infinite_idle_token_lifetime" is not expected here.

when i do terraform plan

**Comment by algiorgi** [comment]
Sorry for my band english.
I have been experimenting something similiar.

I have this terraform script:

```
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "0.30.2"
    }
  }
}

provider "auth0" {
  domain        = "some-valid-domain"
  client_id     = "some-valid-client-id"
  client_secret = "some-valid-client-secret"
}

resource "auth0_client" "auth0_test" {
  name                       = "AppName"
  description                = "AppDescription"
  app_type                   = "spa"
  oidc_conformant            = true
  token_endpoint_auth_method = "none"

  refresh_token {
    rotation_type   = "non-rotating"
    expiration_type = "non-expiring"
    token_lifetime  = 36000
  }

  jwt_configuration {
    alg = "RS256"
  }
}
```
This script works fine the very first time but when I execute it again I get:

Error: 400 Bad Request: Neither infinite_token_lifetime nor infinite_idle_token_lifetime can be true when token expiration type is 'non-expiring'

According to the documentation both values are false by default:

[infinite_idle_token_lifetime](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/client#infinite_idle_token_lifetime) - (Optional) Boolean, (Default=false) Whether or not inactive refresh tokens should be remain valid indefinitely.

[infinite_token_lifetime](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/client#infinite_token_lifetime) - (Optional) Boolean, (Default=false) Whether or not refresh tokens should remain valid indefinitely. If false, token_lifetime should also be set

**Comment by sergiughf** [comment]
Hey folks, this got fixed through https://github.com/auth0/terraform-provider-auth0/pull/187 and it will be available in the next release planned towards the end of next week (approximately). We'll be closing this down cuz of this.
