### ISSUE TITLE
Connection `options.configuration` changes unreported

### ISSUE THREAD

**Issue by Jrc356** [auth0/terraform-provider-auth0#251]
### Describe the problem
When planning changes to a connection, changes to `options.configuration` are unreported in the plan.

### What was the expected behavior?
Changes to `options.configuration` are reported in a plan.

### Reproduction

1. create a connection with empty `options.configuration`
2. update the connection to have a configuration (through UI, cli, or other non-terraform means)
3. plan the connection
4. notice there are no mentions of changes to `options.configuration` planned

### Environment

- Auth0 provider version: `~> 0.32.0`
- Terraform version: `1.2.4`

**Comment by sergiught** [comment]
Hey @Jrc356 👋🏻 , 

Thanks for reporting this. Unfortunately the database settings (options.configuration) values are encrypted once set, so we can't display an accurate diff as the API will return the encrypted value. However I did add a warning at least for the keys to ensure we don't by mistake wipe away anything that was present inside the management dashboard and not tracked within terraform in https://github.com/auth0/terraform-provider-auth0/pull/307. 

I'll update this issue once that's merged and released into a new version. 

Thanks for your patience!

**Comment by sergiught** [comment]
Hey @Jrc356  this was now added within https://registry.terraform.io/providers/auth0/auth0/0.37.0, closing this issue down now. 

Be mindful that when an unmanaged configuration secret is found, you'll have to add it to your terraform config, and then remove it from the dashboard UI and run terraform apply again.
