### ISSUE TITLE
Missing argument for "Add Permissions in the Access Token" in auth0_resource_server

### ISSUE THREAD

**Issue by jeroenmarchand** [auth0/terraform-provider-auth0#257]
### Describe the problem

The dashboard interface for API's shows an "Add Permissions in the Access Token" option under "RBAC Settings" that adds a permissions claim to the access_token. This argument seems to be missing from the `auth0_resource_server` docs. This makes it impossible to correctly configure the API with Terraform.

### What was the expected behavior?

An extra argument for the "Add Permissions in the Access Token" in `auth0_resource_server` that can be set to `true`

### Reproduction

[Docs for resource](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/resource_server)

```
resource "auth0_resource_server" "default" {
  name        = "Example Resource Server (Managed by Terraform)"
  identifier  = "https://api.example.com"

  # Enable RBAC
  enforce_policies = true

  # Option for adding permission claim to access_token?
}
```

The resource above does enable RBAC.

### Environment

- **Version of `terraform-provider-auth0` used: v0..33.0**

**Comment by sergiughf** [comment]
Hey @jeroenmarchand, thanks for opening an issue with us! 

In order to toggle the "**Add Permissions in the Access Token**" setting please set `token_dialect` to `access_token_authz` while making sure `enforce_policies` is `true`. 

This is however referenced in the docs as well under **token_dialect**: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/resource_server#token_dialect. 

👋🏻

**Comment by jeroenmarchand** [comment]
Missed that one, sorry. Thanks for the clarification!

**Comment by ynnelson** [comment]
The documentation should be updated because this isn't clear. It's very confusing.

**Comment by sergiught** [comment]
Hey @ynnelson 👋🏻 thanks for the feedback. If this is still confusing we'll reopen this issue and look for ways to make this more clear.

**Comment by josecsotomorales** [comment]
Also experienced this one, it's confusing to find out that property, but glad there is a way.

**Comment by sergiught** [comment]
Hey folks, appreciate the feedback. We have a PR over at https://github.com/auth0/terraform-provider-auth0/pull/371 to try to improve the docs. Let us know if this helps!

**Comment by sergiught** [comment]
Hey folks, we just released https://registry.terraform.io/providers/auth0/auth0/0.39.0 with a fix for this. We'll close the issue down now.
