### ISSUE TITLE
Passwordless email connection -> Not possible to set options.name

### ISSUE THREAD

**Issue by bartvanackooij** [auth0/terraform-provider-auth0#260]
### Describe the problem

Hi! 

When deploying a Passwordless email connection through the auth0_connection resource, the connection name is not set properly. Comparing the settings in the UI shows the 'Connection' is empty and can't be set: 

This is what I see when deployed with terraform: 
<img width="379" alt="Screenshot 2022-07-27 at 21 42 00" src="https://user-images.githubusercontent.com/17408996/181358299-2bde17f8-cc9e-4077-a7d3-5e0023c69d16.png">

And getting the data with the API the options is missing the `"name":"email"`

```
    "options": {
      "email": {}, 
      ... ...
    },
```

### What was the expected behavior?

Expected: 
This is what I expect (from another setup which was created manually) 
<img width="379" alt="Screenshot 2022-07-27 at 21 40 27" src="https://user-images.githubusercontent.com/17408996/181358067-e797597a-7907-4b46-a104-1a7ecdafb0e8.png">

```
    "options": {
      "name": "email",
      "email": {},
      ... ... 
    },
```

### Reproduction
Using a basic set up of the connection: 

```
resource "auth0_connection" "passwordless_email" {
  strategy = "email"
  name     = "email"
  enabled_clients = [
    auth0_client.NAME.id,
    auth0_client.NAME.id
  ]

  options {
    from           = var.from_address
    subject        = var.email_subject
    syntax         = "liquid"
    template       = var.template
    disable_signup = false
  }
}
```
Trying adding `name = "email"` to the options did not work either. Am I missing something here? I'm running into issues with the passwordless email and I'm wondering if this is causing this. 

### Environment
version: 0.33.0 of the auth0 provider

**Comment by bartvanackooij** [comment]
My last update: 

> Trying adding name = "email" to the options did not work either.

is incorrect. It **does** work and it shows in the UI / API. 

Just checking before I close this issue:

This is not mentioned in the auth0_connection [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection#passwordless-email). Is there a reason to allow users to set the name of the connection and should we update the documentation page that the `options` block supports the `name` argument? 

Or should this be set when the `strategy = "email"` is used in the auth0_connection resource?

**Comment by willvedd** [comment]
>This is not mentioned in the auth0_connection [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection#passwordless-email). Is there a reason to allow users to set the name of the connection and should we update the documentation page that the options block supports the name argument?

Perhaps it could be made more clear in the docs, but the `name` property on the connection resource is mentioned here: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection#argument-reference. All connections share a core set of arguments but there are various sets of custom arguments that are specific to a connection type. The `name` argument is generic and applies to all types. Again, this probably isn't immediately obvious given all the different connection types. 

Knowing this, do you have any suggestions on how to improve the docs?

>Or should this be set when the strategy = "email" is used in the auth0_connection resource?

I'd be reluctant to do any implicit magic with the names here for passwordless connections specifically. It should be explicitly defined like all other connections.
