### ISSUE TITLE
webauthn_platform_first_factor in auth0_prompt resource is not working as expected

### ISSUE THREAD

**Issue by itsnagaraj** [auth0/terraform-provider-auth0#264]
### Describe the problem

I tried configuring authentication profile in Auth0 using `auth0_prompt` resource and setting `webauthn_platform_first_factor` to true

```
resource "auth0_prompt" "universal-login" {
  universal_login_experience     = "new"
  identifier_first               = !var.auth_profile_webauthn_enabled
  webauthn_platform_first_factor = var.auth_profile_webauthn_enabled
}
```

### What was the expected behavior?

After applying the changes, I should see that `Identifier + Biometrics first (enterprise)` selected in Auth0 console but I see `Identifier First`

Every time I run the pipeline I see that state transitions from `false` to `true`

```
  # auth0_prompt.universal-login will be updated in-place
  ~ resource "auth0_prompt" "universal-login" {
        id                             = "terraform-xxxxxxxxxxxxxxxxxx"
      ~ webauthn_platform_first_factor = false -> true
        # (2 unchanged attributes hidden)
    }
```

### Environment
Version of `terraform-provider-auth0` used: 0.34.0
Version of `terraform` used: 1.1.9

**Comment by sergiught** [comment]
Hey @itsnagaraj thanks for opening the issue, I'll be taking a look at this today or tomorrow. Apologies for the inconvenience caused 😞

**Comment by sergiught** [comment]
Hey @itsnagaraj I wasn't able to reproduce this. To better understand what's happening could you run the `terraform apply ` command with `TF_LOG=debug` 🙏🏻 ?

```shell
TF_LOG=debug terraform apply
```

**Comment by itsnagaraj** [comment]
Sure. I Will give this a go and keep you posted

**Comment by itsnagaraj** [comment]
Hi @sergiught, I was able to get this `Identifier + Biometrics first (enterprise)` working after changing the configuration to following. 

```
resource "auth0_prompt" "prompt" {
  universal_login_experience     = "new"
  identifier_first               = var.auth_profile_identifier_first_enabled
  webauthn_platform_first_factor = var.auth_profile_webauthn_enabled
}
```

both `auth_profile_webauthn_enabled` and `auth_profile_identifier_first_enabled` has to be set to `true` for the option to be selected in authentication profile. In my case I was previously setting negated value of `auth_profile_webauthn_enabled`.
