### ISSUE TITLE
data resources will be always searched from first 50 clients

### ISSUE THREAD

**Issue by rma945** [auth0/terraform-provider-auth0#267]
### Describe the problem

If you have more than 50 clients - terraform data resources will not work properly, because by default [API client will always use 50 items per page](https://github.com/auth0/go-auth0/blob/ed11d807f202c44fe3e3c683083ad0badd1c2a9b/management/management.go#L412)

### What was the expected behavior?

Add parameter in a provider configuration for a define **per_page** variable

### Reproduction

Just create more than 50 clients, and then try to get the client with logical number 51 by data resource

### Environment
terraform version: 1.2.6
auth0 provider version: 0.31.0

**Comment by sergiught** [comment]
Hey @rma945 thanks for reporting this. I went ahead and worked on a fix for this in https://github.com/auth0/terraform-provider-auth0/pull/306. Once that gets merged and released I'll update this issue:) Thanks for your patience!

**Comment by sergiught** [comment]
Hey @rma945  this was now fixed within https://registry.terraform.io/providers/auth0/auth0/0.37.0, closing this issue down now.
