### ISSUE TITLE
email template "reset

### ISSUE THREAD

**Issue by thomaskvnze** [auth0/terraform-provider-auth0#276]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When creating a auth0_email_template resource of type "reset_email", the management api returns a 400 Bad Request: The template property provided in payload must match template in the URL.

We tried to reproduce the error by calling the management api by hand. This error is sent back when the called template path in the URL mismatches the template property in the JSON, e.g.

URL:
`https://my-domain.eu.auth0.com/api/v2/email-templates/reset_email`

Body:
```
{
     template: "verify_email"
}
```

It looks like you are sending the wrong template payload to the management api.

### Expectation

When creating a auth0_email_template resource of type "reset_email", the change password template is set and the management api returns a 200

### Reproduction

```
resource "auth0_email_template" "invite-change-password" {
  template = "reset_email"
  body = "<p>hello</p>
  from = "no-reply@anything.com"
  result_url = "https://anything.com"
  subject = "My subject"
  syntax = "liquid"
  url_lifetime_in_seconds = 86400
  enabled = true
}
```

### Auth0 Terraform Provider version

0.34

### Terraform version

1.2.6

**Comment by sergiught** [comment]
Hey @thomaskvnze 👋🏻 

I did a terraform apply on your reproduction sample, but did not encounter any issues. 

```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

This is the payload that got sent: 

```json
{"template":"reset_email","body":"<p>hello</p>","from":"no-reply@anything.com","resultUrl":"https://anything.com","subject":"My subject","syntax":"liquid","urlLifetimeInSeconds":86400,"enabled":true}
```

**Comment by sergiught** [comment]
Hey @thomaskvnze, I wasn't able to find any issues and couldn't reproduce your issue either. If you're still encountering issues please feel free to reopen this and add additional info.

**Comment by pamular** [comment]
I have encountered the same issue:
```
auth0_email_template.reset_email_staging: Modifying... [id=verify_email_by_code]

Error: 400 Bad Request: The template property provided in payload must match the template in the URL.

  with auth0_email_template.reset_email_staging,
  on env-staging.tf line 534, in resource "auth0_email_template" "reset_email_staging":
 534: resource "auth0_email_template" "reset_email_staging" {
```
It looks like it's trying to modify another template?

My template looks like this:

```
resource "auth0_email_template" "reset_email_staging" {
  provider   = auth0.staging
  depends_on = [auth0_email.smtp_email_provider_staging]

  template                = "reset_email"
  body                    = file("${path.module}/auth0/templates/reset_email.html")
  from                    = "no-reply@granular-energy.com"
  subject                 = "[STAGING] Reset your password"
  syntax                  = "liquid"
  url_lifetime_in_seconds = 3600
  enabled                 = true
}
```

**Comment by pamular** [comment]
Found it: it needs the `result_url` parameter to work properly...
