### ISSUE TITLE
Unable to create SES Email Provider

### ISSUE THREAD

**Issue by alexander-r-arnold** [auth0/terraform-provider-auth0#282]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We currently set up our ses email provider in the auth0 console manually. Later, after running terraform import, and trying to apply some changes for the first time, we run into the following error

```
auth0_email.amazon_ses_email_provider: Destroying... [id=ses]
auth0_email.amazon_ses_email_provider: Destruction complete after 1s
auth0_email.amazon_ses_email_provider: Creating...
╷
│ Error: 409 Conflict: An email provider is already configured: ses
│ 
│   with auth0_email.amazon_ses_email_provider,
│   on email.tf line 5, in resource "auth0_email" "amazon_ses_email_provider":
│    5: resource "auth0_email" "amazon_ses_email_provider" {
│ 
╵
Releasing state lock. This may take a few moments...
```

If we apply again, we get a similar error, but without the destroy

```
auth0_email.amazon_ses_email_provider: Creating...
╷
│ Error: 409 Conflict: An email provider is already configured: ses
│ 
│   with auth0_email.amazon_ses_email_provider,
│   on email.tf line 5, in resource "auth0_email" "amazon_ses_email_provider":
│    5: resource "auth0_email" "amazon_ses_email_provider" {
│ 
╵
Releasing state lock. This may take a few moments...
```

This was the original terraform plan

```
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # auth0_email.amazon_ses_email_provider must be replaced
-/+ resource "auth0_email" "amazon_ses_email_provider" {
      ~ id                   = "ses" -> (known after apply)
        name                 = "ses"
        # (2 unchanged attributes hidden)

      ~ credentials {
          + access_key_id     = (sensitive value) # forces replacement
          + secret_access_key = (sensitive value) # forces replacement
          - smtp_port         = 0 -> null
            # (1 unchanged attribute hidden)
        }
    }
```

### Expectation

I would expect this to allow me to create/update in place an existing SES email provider.

### Reproduction

This error is gotten on any terraform apply

### Auth0 Terraform Provider version

0.29.0

### Terraform version

1.1.0

**Comment by sergiught** [comment]
Hey @alexander-r-arnold 👋🏻 thanks for reporting this. I was able to reproduce the issue and I'll be working on a fix. I'll let you know when the fix will be available in the next release. Thanks for your patience!

**Comment by sergiught** [comment]
Hey @alexander-r-arnold  this was now fixed within https://registry.terraform.io/providers/auth0/auth0/0.37.0, closing this issue down now.

**Comment by alexander-r-arnold** [comment]
Thank you @sergiught !!
