### ISSUE TITLE
`set_user_root_attributes` on `auth0_connection` not idempotent

### ISSUE THREAD

**Issue by ad8lmondy** [auth0/terraform-provider-auth0#283]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am creating an `auth0_connection` resource, and setting the `set_user_root_attributes` option to be `on_each_login`. However, every time I run a plan and apply, the next time I run a plan, it reports:

```
  # module.auth0_database["XYZ"].auth0_connection.connection will be updated in-place
  ~ resource "auth0_connection" "connection" {
        id                   = "con_1234"
        name                 = "XYZ"
        # (5 unchanged attributes hidden)

      ~ options {
          + set_user_root_attributes       = "on_each_login"
            # (27 unchanged attributes hidden)

            # (5 unchanged blocks hidden)
        }
    }
```
even if a plan has just been applied.

Looking at the state in Terraform cloud, I see this:
```
    ...
    {
      "module": "module.auth0_database[\"XYZ\"]",
      "mode": "managed",
      "type": "auth0_connection",
      "name": "connection",
      "provider": "provider[\"registry.terraform.io/auth0/auth0\"]",
      "instances": [
        {
          "schema_version": 2,
          "attributes": {
            "display_name": "",
            "enabled_clients": [
              "abcdefg",
              "hijklm"
            ],
            "id": "con_1234",
            "is_domain_connection": false,
            "metadata": {},
            "name": "XYZ",
            "options": [
              {
                ...
                "set_user_root_attributes": "",
                ...
```
So it looks like it's not getting set in the state somehow? Not sure.

Having a look here: https://github.com/auth0/terraform-provider-auth0/blob/e8bb30582c7a92baf57f0ad90638e66b8a4ff102/internal/provider/structure_auth0_connection.go#L97, I can see that all the other types of `func flattenConnectionOptionsXYZ` functions include a line like:
```go
"set_user_root_attributes": options.GetSetUserAttributes(),
```
but that the `flattenConnectionOptionsAuth0` does not. Maybe this is the issue?

This is only an issue if I try to set the `set_user_root_attributes` variable. With an database of type `auth0` with no custom database, of course it doesn't make sense for `set_user_root_attributes` to have a value - but when there is a custom DB, it should accept the value.

### Expectation

The `set_user_root_attributes` value should only need to be set once, and not show up as a change every time a plan is run.

### Reproduction

```terraform
resource "auth0_connection" "connection" {
  name     = XYZ
  strategy = "auth0"

  enabled_clients = []

  options {
    enabled_database_customization = true
    set_user_root_attributes = "on_each_login"
  }
}
```

As mentioned above, this makes sense for when `enabled_database_customization = false` - the `set_user_root_attributes` doesn't have any meaning that case - but when customization _is_ enabled, we should be able to set `set_user_root_attributes`.

Could be vaguely related to: https://github.com/auth0/terraform-provider-auth0/issues/83 ?

### Auth0 Terraform Provider version

v0.34.0

### Terraform version

Terraform v1.2.6 on linux_amd64

**Comment by sergiught** [comment]
Hey @ad8lmondy really appreciate you opening this issue and for the super detailed description! It really makes our lives easier:) I have a fix already in https://github.com/auth0/terraform-provider-auth0/pull/303 ready for review. I'll post back here when it's merged and available in a release. Thanks for your patience!

**Comment by sergiught** [comment]
Hey @ad8lmondy this was now fixed within https://registry.terraform.io/providers/auth0/auth0/0.37.0, closing this issue down now.

**Comment by ad8lmondy** [comment]
Thanks heaps!
