### ISSUE TITLE
auth0_action runtime is not supported

### ISSUE THREAD

**Issue by kpettijohn** [auth0/terraform-provider-auth0#286]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I seem to be unable to create an action with a node16 runtime. 
```
resource "auth0_action" "test" {
  name    = "Test"
  runtime = "node16"
  supported_triggers {
    id      = "post-login"
    version = "v1"
  }
  code   = <<-EOT
      exports.onContinuePostLogin = async (event, api) => {
          console.log("test");
      };
   EOT
  deploy = false
}
```

Error response
```
Error: 400 Bad Request: runtime is not supported
```

If I use a node12 runtime the action is successfully created. 

### Expectation

Ability to create auth0 actions using the node16 runtime.

### Reproduction

1. Create a auth0_action using the node16 runtime
2. Apply Terraform
3. Error: 400 Bad Request: runtime is not supported

### Auth0 Terraform Provider version

0.35.0 and 0.34.0

### Terraform version

1.1.8

**Comment by willvedd** [comment]
You're correct that `node16` should be available for actions. I believe the issue here is around the version of the trigger you're binding to, `v1`:

```
 supported_triggers {
    id      = "post-login"
    version = "v1"
  }
  ```
  
Version 1 does not support node 16 which should explain the error. Further, versions 1 and 2 of that trigger are deprecated, so I'd recommend trying again with `v3` which supports node 16 by default. Hope that helps!

**Comment by willvedd** [comment]
@kpettijohn One final followup here – I've pushed a change to an internal repo that adds more context to this exact error. I'm hoping it enables users to rectify themselves. Thanks again for bringing this to our attention.
