### ISSUE TITLE
Update @types/auth0 with latest types

### ISSUE THREAD

**Issue by Aaronius** [auth0/terraform-provider-auth0#290]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

It would be really helpful to have types for all Auth0 resources. As an example, right now I'm writing code for a login action that I want to deploy using Terraform. I'd love to have types for the action function, the event object, and the api object.

### Describe the ideal solution

I would love to see Auth0 make a concerted effort to help its developer community by updating @types/auth0 with the latest types. There is already [an issue in the DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/52877) that has a list of missing types.

### Alternatives and current workarounds

Write our own types. Make our own contributions.

**Comment by willvedd** [comment]
@Aaronius No doubt that would be a helpful addition! However, your request pertains to the Auth0 Node SDK, which has no relation to the Terraform provider. There is an [existing thread](https://github.com/auth0/node-auth0/issues/572) about this exact feature request though, I recommend you divert this sentiment there instead. I can assure you that our teams take this type of feedback very seriously!
