### ISSUE TITLE
Import auth0_organization_connection fails

### ISSUE THREAD

**Issue by manuel-guilbault** [auth0/terraform-provider-auth0#299]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Trying to import an existing `auth0_organization_connection` resource using a random UUID v4 as the ID, as per [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/organization_connection#import), fails with the following error:

```
│ Error: 404 Not Found: Not Found
```

### Expectation

I expect the existing `auth0_organization_connection` to be imported in the state successfully.

### Reproduction

1. Deploy an `auth0_organization` resource (with a `connections` block) using version 0.28.1 of the provider.
2. Upgrade the provider to version 0.36.0.
3. Modify the `auth0_organization` resource declaration by converting the `connections` block into a new `auth0_organization_connection` resource.
4. Try to import the `auth0_organization_connection` resource in the state.

### Auth0 Terraform Provider version

0.36.0

### Terraform version

1.2.7

**Comment by sergiught** [comment]
Hey @manuel-guilbault 👋🏻 ! Really appreciate you opening this issue. I was able to reproduce the issue and started working on a fix. I'll give you an update on this when the fix is available. Thanks for your patience!

**Comment by sergiught** [comment]
Hey @manuel-guilbault this was now fixed within https://registry.terraform.io/providers/auth0/auth0/0.37.0, closing this issue down now.

**Comment by manuel-guilbault** [comment]
Awesome, thanks a lot @sergiught !
