### ISSUE TITLE
Missing Documentation for clients

### ISSUE THREAD

**Issue by mbainter** [auth0/terraform-provider-auth0#313]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

App Type is a required field with limited options, but the options are not provided in the Terraform resources page for clients.

### Expectation

This section of the documentation should specify what the options for this parameter are, but it does not.  Further, it is not defined in the Applications documentation on the auth0 website, but only in the Management API documentation for creating clients.

The clients page here in the provider docs should provide the list: spa, native, non_interactive, or regular_web.

### Reproduction

Go to the documentation page for clients in terraform, look at the page, and note that it doesn't explain what the available options for the app_type parameter are.

### Auth0 Terraform Provider version

0.34

### Terraform version

1.2.5

**Comment by sergiught** [comment]
Hey @mbainter thanks for reporting this! I'm improving the docs in https://github.com/auth0/terraform-provider-auth0/pull/325. Once that's merged and released we'll be able to close this down.
