### ISSUE TITLE
Auth0_Client with addons samlp throws 400 Bad Request: Payload validation error  in the latest version. 

### ISSUE THREAD

**Issue by Viru82** [auth0/terraform-provider-auth0#314]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Auth0_Client with addons samlp stopped working in the latest version. 

Following block of code used to work fine till auth0/auth0 version 0.34 , however it stopped working in the latest version.

resource "auth0_client" "test_app" {
  name                       = "MyApp"
  app_type                   = "regular_web"
  token_endpoint_auth_method = "client_secret_post"
  callbacks                  = ["https://signin.aws.amazon.com/saml"]
  grant_types                = ["authorization_code", "refresh_token", "implicit"]
  addons {
    samlp {
      audience = "urn:amazon:webservices"
    }
  }
}

Actual Result - throw following errors even though they are optional fields

['', "Error: 400 Bad Request: Payload validation error: 'Expected type string but found type null' on property addons.samlp.recipient. (also) Payload validation error: 'Expected type array but found type null' on property addons.samlp.nameIdentifierProbes. (also) Payload validation error: 'Expected type object but found type null' on property addons.samlp.mappings. (also) Payload validation error: 'Expected type string but found type null' on property addons.samlp.destination. (also) Payload validation error: 'Expected type string but found type null' on property addons.samlp.authnContextClassRef.", '', '  with auth0_client.quicksight_Testing[0],', '  on auth0.tf line 642, in resource "auth0_client" "quicksight_Testing":', ' 642: resource "auth0_client" "quicksight_Testing" {']

### Expectation

App should be created without any issues

### Reproduction

Following block of code used to work fine till auth0/auth0 version 0.34 , however it stopped working in the latest version.

resource "auth0_client" "test_app" {
  name                       = "MyApp"
  app_type                   = "regular_web"
  token_endpoint_auth_method = "client_secret_post"
  callbacks                  = ["https://signin.aws.amazon.com/saml"]
  grant_types                = ["authorization_code", "refresh_token", "implicit"]
  addons {
    samlp {
      audience = "urn:amazon:webservices"
    }
  }
}

### Auth0 Terraform Provider version

0.37

### Terraform version

2.2.3

**Comment by sergiught** [comment]
Hey @Viru82 👋🏻 thanks for reporting this,

**Comment by sergiught** [comment]
Hey @Viru82 this is now fixed in the latest release https://registry.terraform.io/providers/auth0/auth0/0.37.1! Please make sure to upgrade to it to have this resolved. Thanks for your patience!
