### ISSUE TITLE
Provider throw 400 error when we attempt to create actions with triggers "post-user-registration" or "post-change-password"

### ISSUE THREAD

**Issue by bt-shoprunner** [auth0/terraform-provider-auth0#329]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

My team is attempting to implement Auth0 actions via the terraform provider, and we seem to have found a bug involving the supported triggers.  

Here is the snippet of terraform that we are trying to execute:

```
resource "auth0_action" "my_email_template" {
  depends_on = [auth0_email.my_email_provider]
  name       = format("Send Welcome Email %s", timestamp())
  runtime    = "node16"
  code       = file("${path.module}/auth0/welcome_mail.js")
  deploy     = true

  supported_triggers {
    id      = "post-user-registration"
    version = "v3"
  }
}
```

When attempting to execute this via terraform apply, we get the following error:

```
│ Error: 400 Bad Request: trigger is not supported
│ 
│   with auth0_action.my_email_template,
│   on auth0.tf line 40, in resource "auth0_action" "my_email_template":
│   40: resource "auth0_action" "my_email_template" {
│ 
```

This also fails for the trigger "post-change-password."  The trigger "post-login" works perfectly fine, but other's just don't. 

I've been using the trigger names defined [here](https://auth0.com/docs/customize/actions/flows-and-triggers).  

The issue presents with versions 0.36.0, 0.37.0, and 0.37.1 when we test this out.

### Expectation

I would assume that when my terraform runs, the trigger would be applied along with the correct action.

### Reproduction

Given the terraform 
```
resource "auth0_action" "my_email_template" {
  depends_on = [auth0_email.my_email_provider]
  name       = format("Send Welcome Email %s", timestamp())
  runtime    = "node16"
  code       = file("${path.module}/auth0/welcome_mail.js")
  deploy     = true

  supported_triggers {
    id      = "post-user-registration"
    version = "v3"
  }
}```

When it is executed against an Auth0 tenant, 

Then the action is created with the correct trigger.



### Auth0 Terraform Provider version

0.37.1

### Terraform version

1.2.8

**Comment by john-tipper** [comment]
I have the same issue with `post-user-registration` - I also don't know what the list of acceptable versions is for a given trigger. I blindly put `v3` and got the same error. When I put `v2` as the version, it worked.

**Comment by mparz111** [comment]
Also having the same issue. Would be great if the documentation could be updated with all the supported triggers

**Comment by sergiught** [comment]
Hey folks, we're trying to improve this by adding a guide on how to fetch an always up to date list of available action triggers and their versions in https://github.com/auth0/terraform-provider-auth0/pull/370. Once that's merged and released the terraform registry docs will render the guide in a nicer format. Stay tuned!

**Comment by sergiught** [comment]
Hey folks, we just released https://registry.terraform.io/providers/auth0/auth0/0.39.0 with a fix for this. We'll close the issue down now. Have a look at the new guide https://registry.terraform.io/providers/auth0/auth0/latest/docs/guides/action_triggers
