### ISSUE TITLE
Impossible to create/overwrite an already existing email provider

### ISSUE THREAD

**Issue by pamular** [auth0/terraform-provider-auth0#330]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm trying to create an email provider on an Auth0 tenant. A custom email provider was already configured, but i disabled it, hoping that Auth0 would overwrite it nonetheless.

But here is what happened:

```
Error: 409 Conflict: An email provider is already configured: smtp

  with auth0_email.smtp_email_provider_production,
  on env-production.tf line 449, in resource "auth0_email" "smtp_email_provider_production":
 449: resource "auth0_email" "smtp_email_provider_production" {
...
```

### Expectation

I expected the creation of the email provider, even though a provider is already configured (even manually).

### Reproduction

1. Given a manually configured custom email provider on an Auth0 tenant
2. When a custom email provider is described and applied by Terraform
3. Then a error is thrown

### Auth0 Terraform Provider version

0.37.1

### Terraform version

1.2.2

**Comment by sergiught** [comment]
Hey @pamular 👋🏻 

While I do agree that the developer experience could be improved for single entity resources like the email provider (there can only ever be 1), it's not technically impossible to manage an already existing email provider. To do so please use the import command first and then apply any changes you might desire: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/email#import. 

We'll flag this as a DX improvement instead of a bug and leave the issue open until it gets improved.

**Comment by sergiught** [comment]
Closing this down as this has been improved in the latest release: https://registry.terraform.io/providers/auth0/auth0/0.40.0.
