### ISSUE TITLE
Using $ in auth0_prompt_custom_text resource body throws invalid reference error

### ISSUE THREAD

**Issue by AyushmatiGit** [auth0/terraform-provider-auth0#332]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We should be able to use $ in the json body of a resource of type 'auth0_prompt_custom_text' when defining custom text on our Auth0 prompts using terraform.
This is shown as examples on[ Auth0 terraform provider documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/prompt_custom_text) and [Auth0 documentation](https://auth0.com/docs/customize/universal-login-pages/customize-login-text-prompts).
Example:
`"pageTitle" : "Log in | ${clientName}"`

However when we use this in our terraform file, we get an error :
```
│ Error: Invalid reference
│
│   on auth0.tf line 7146, in resource "auth0_prompt_custom_text" "custom_texts_login":
│ 7146:         "description" : "To access ${clientName}, you must log in."
│
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.

```

**Mitigation**: To mitigate, we had to use $$clientName. But this is not as stated in the documentation.

### Expectation

1. We should be able to use $ in the json body of a resource of type 'auth0_prompt_custom_text' when defining custom texts on our Auth0 prompts using terraform as mentioned in the documentations, without getting any errors.
2. If we are supposed to use $$ in the json body for the resource, the documentation should be updated.

https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/prompt_custom_text
https://auth0.com/docs/customize/universal-login-pages/customize-login-text-prompts

### Reproduction

resource "auth0_prompt_custom_text" "custom_texts_login" {
  prompt = "login"
  language = "en"
  body = jsonencode(
    {
      "login" : {
        "description" : "To access ${clientName}, you must log in."
      }
    }
  )  
}

### Auth0 Terraform Provider version

0.37.1

### Terraform version

Terraform v1.3.0 on windows_amd64

**Comment by sergiught** [comment]
Hey folks, we just released https://registry.terraform.io/providers/auth0/auth0/0.39.0 with a fix for this. We'll close the issue down now.
