### ISSUE TITLE
auth0_branding_theme: Links restricted to IntType but accepts floats on UI

### ISSUE THREAD

**Issue by pablogamboa** [auth0/terraform-provider-auth0#333]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

While porting some manually-added branding tweaks that a colleague had done, I've realized that the UI and API seemingly accept floats as value in certain places where the terraform provider only accepts ints. For example:

* links.size: https://github.com/auth0/terraform-provider-auth0/blob/main/internal/provider/resource_auth0_branding_theme.go#L267
* body_text.size: https://github.com/auth0/terraform-provider-auth0/blob/main/internal/provider/resource_auth0_branding_theme.go#L201
* subtitle.size: https://github.com/auth0/terraform-provider-auth0/blob/main/internal/provider/resource_auth0_branding_theme.go#L296

I think this TypeInt should be TypeFloat instead.

### Expectation

Certain fields should accept float values, and at the moment is restricted to int only.

### Reproduction

Go to the UI, introduce a float size for any of the mentioned attributes. Ensure that if you fetch it manually with the API it comes as a float. 

Excerpt of me fetching it via curl

```
curl -vH "Authorization: Bearer ${TOKEN}" \
  https://foo.eu.auth0.com/api/v2/branding/themes/default
{
"fonts": {
    "font_url": "https://github.com/ethereum/ethdev-site/blob/master/public/fonts/Proxima%20Nova%20Reg%20It.woff",
    "reference_text_size": 16,
    "title": {
      "bold": true,
      "size": 150
    },
    "subtitle": {
      "bold": false,
      "size": 87.5
    },
    "body_text": {
      "bold": false,
      "size": 87.5
    },
    "buttons_text": {
      "bold": true,
      "size": 100
    },
    "input_labels": {
      "bold": false,
      "size": 100
    },
    "links": {
      "bold": true,
      "size": 87.5
    },
    "links_style": "normal"
  },
...
}
```

### Auth0 Terraform Provider version

0.37.1

### Terraform version

1.1.4

**Comment by thetimbecker** [comment]
I am in the same situation and running into this exact same issue, down to the numbers. I'm assuming these are the default numbers which means this will be a common issue people run into.

As a workaround, I am setting these to 87 instead of 87.5. I'm sure no one will mind.


Also, in case anyone else is stuck on this, I couldn't find the theme ID in the UI. I ended up finding it using the Management API browser: https://auth0.com/docs/api/management/v2/#!/Branding/get_default_branding_theme

**Comment by sergiught** [comment]
Hey folks, apologies for the inconvenience caused, that was a pretty bad oversight on our part. 😞 We'll probably have some time to focus on fixing this once we wrap up https://github.com/auth0/terraform-provider-auth0/issues/14. We'll keep you updated 🙏🏻

**Comment by sergiught** [comment]
Hey folks, we just released https://registry.terraform.io/providers/auth0/auth0/0.39.0 with a fix for this. We'll close the issue down now.

**Comment by pablogamboa** [comment]
@sergiught thank you!
