### ISSUE TITLE
auth0_tenant idle_session_lifetime and session_lifetime are incorrect

### ISSUE THREAD

**Issue by victoriafrench** [auth0/terraform-provider-auth0#353]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The Auth0 Dashboard UI, the API, and your documentation state that both `idle_session_lifetime` and `session_lifetime` are in `minutes`.

The configuration is transmitting in `hours`, not `minutes`. Also, import is resulting in `0` for both values (I assume because the default values are out of range).

There was an issue that is closed (#150) that stated this is fixed, but I have a new installation with the latest providers and this is what is occurring.

### Expectation

Configurations should be using `minutes` not `hours`

### Reproduction

resource "auth0_tenant" "test" {
      session_lifetime = 1
      idle_session_lifetime = 1
}

Both will be set to 60 in Auth0.

### Auth0 Terraform Provider version

0.37.1

### Terraform version

1.3.2

**Comment by sergiught** [comment]
Hey @victoriafrench 👋🏻 thanks for opening this issue! 

While I completely understand the confusion and the frustration working with those 2 fields (indeed historically they have been quite hard to work with), in our provider docs we do mention that they represent the number of hours. 

From https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/tenant#idle_session_lifetime
> [idle_session_lifetime](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/tenant#idle_session_lifetime) (Number) Number of hours during which a session can be inactive before the user must log in again.

From https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/tenant#session_lifetime
>[session_lifetime](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/tenant#session_lifetime) (Number) Number of hours during which a session will stay valid.

We can't always guarantee that the [API Docs](https://auth0.com/docs/api/management), the Dashboard labels and our [Terraform Provider Docs](https://registry.terraform.io/providers/auth0/auth0/latest) will be in sync. Please always consider as a source of truth the provider docs: https://registry.terraform.io/providers/auth0/auth0/latest. 

I also just did a quick terraform import with v0.38.0 and I was able to correctly import those 2 fields with a non 0 value. So I wasn't able to reproduce your import issue. Could you perhaps give us additional debug output by running terraform import with `TF_LOG=DEBUG` and `AUTH0_DEBUG=true` env vars? e.g. 

```terminal
$ TF_LOG=DEBUG AUTH0_DEBUG=true terraform import auth0_tenant.test <any-id>
```

**Comment by sergiught** [comment]
We'll be closing this down, as we weren't able to reproduce the issue with the import on the tenant resource and the `idle_session_lifetime` and `session_lifetime` are documented as being the value in hours. In case of additional input we can always reopen.
