### ISSUE TITLE
404 in auth0_branding resource after upgrade to 0.38.0

### ISSUE THREAD

**Issue by markusbaumg** [auth0/terraform-provider-auth0#358]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After upgrading to 0.38.0, the state of the `auth0_branding` resource cannot be refreshed

Defined Resource
```
resource "auth0_branding" "xxx" {
  logo_url = "https://xxx.com/logo.png"
  colors {
    primary         = "#6546e8"
    page_background = "#fff"
  }
}
```
Issue that apears when upgrading to 0.38.0. This does not happen with 0.37.1
```
module.auth0.auth0_branding.xxx: Refreshing state... [id=terraform-20220908101302395600000001]
│ Error: 404 Not Found: Template does not exist.
│ 
│   with module.auth0.auth0_branding.xxx,
│   on ../modules/auth0/branding.tf line 1, in resource "auth0_branding" "xxx":
│    1: resource "auth0_branding" "xxx" {
```

### Expectation

Terraform state can be refreshed

### Reproduction

- Define and apply resource in an older version
- Upgrade terraform provider to 0.38.0
- Run `terraform refresh`

### Auth0 Terraform Provider version

v0.38.0

### Terraform version

Terraform v1.3.2

**Comment by sergiught** [comment]
Hey @markusbaumg 👋🏻 ,

I tried to reproduce the issue you're experiencing however I am unable to. In the latest release we also haven't modified the schema of the branding resource. 

```shell
$ terraform refresh
$ echo $?                                                                        ✔  14:18:41
0
```

I tried as well to downgrade from 0.38.0 to 0.37.1 and I'm still not experiencing any issues. The state structure stays the same. 

What happens if you try to reimport the resource? (https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/branding#import)

**Comment by markusbaumg** [comment]
Hey @sergiught 

Thank you for investigating this and for the workaround! I'll stick to 0.37.1 for now.

**Comment by mswezey23** [comment]
I hit this error today as well. Looking forward to the fix being released :)

**Comment by sergiught** [comment]
Hey folks, we just released https://registry.terraform.io/providers/auth0/auth0/0.39.0 with a fix for this. We'll close the issue down now.
