### ISSUE TITLE
400 in client when setting custom_login_page to "" in 0.38.0

### ISSUE THREAD

**Issue by nomeelnoj** [auth0/terraform-provider-auth0#360]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When running a previous module for auth0_client where we default the `custom_login_page` to `""`, we now get a 400.

### Expectation

This functionality should remain across versions, or be accompanied by a notice for breaking changes.

### Reproduction

1. Create a client module with variables in all fields (similar to the shortcut code below)

```hcl
# main.tf
# this is the application resource which configures how client applications
# will interact with auth0.
resource "auth0_client" "client" {
  name        = var.app_name
  description = var.app_description

  app_type                            = var.app_type
  logo_uri                            = var.app_logo_uri
  callbacks                           = var.app_login_callbacks
  allowed_logout_urls                 = var.allowed_logout_urls
  grant_types                         = var.app_grant_types
  allowed_origins                     = var.allowed_origins
  web_origins                         = var.web_origins
  organization_require_behavior       = var.organization_require_behavior
  organization_usage                  = var.organization_usage
  initiate_login_uri                  = var.initiate_login_uri

  custom_login_page    = var.custom_login_page # THIS IS THE ISSUE
}
```
Then make sure the variable for custom_login_page is set to `""`
```hcl
# variables.tf
vartiable "custom_login_page" {
  default = ""
  type    = string
}
```

2. Run `terraform plan`, it succeeds
3. Run `terraform apply`, see error:

```
Error: 400 Bad Request: Payload validation error: 'String is too short (0 chars), minimum 1' on property custom_login_page (The content (HTML, CSS, JS) of the custom login page).
```

### Auth0 Terraform Provider version

0.38.0

### Terraform version

1.2.3

**Comment by sergiught** [comment]
Hey @nomeelnoj 👋🏻 , thanks for opening an issue with us.

The error you're receiving is coming directly from the Backend Management API as it's not allowed to set the `custom_login_page` to an empty string. 

Our https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.38.0 release focuses on fixing the bug that was preventing folks to set things as empty across the various configuration fields. So what you're experiencing is actually the bug getting finally fixed. You should have never been allowed to set `custom_login_page` to `""`. 

In case you're not passing `custom_login_page` you should instead default it to `null` and not `""`. 

e.g. 

```terraform
# variables.tf
variable "custom_login_page" {
  default = null
  type    = string
}
```

This will end up in a successful creation/update with the `custom_login_page` not getting sent to the API in case there is no value for it. 

```terminal
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
