### ISSUE TITLE
Error: "read: connection reset by peer" during terraform deployments

### ISSUE THREAD

**Issue by apm101** [auth0/terraform-provider-auth0#375]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Long Terraform deployments with many resources will fail due to connection errors:

```
Error: failed to send the request: Get "https://---------------.us.auth0.com/api/v2/organizations/org_----------------": read tcp 10.226.14.--:----80->104.16.171.253:443: read: connection reset by peer

Error: request failed: Get "https://----------------.us.auth0.com/api/v2/organizations/org_--------------------": read tcp 10.226.7.--:---74->104.16.171.253:443: read: connection reset by peer
```

The error messages appear to be coming from the go-auth0 sdk
https://github.com/auth0/go-auth0/blob/433d9b2d9247c3a37dff52880d42333bb19e21d6/management/management_request.go#L95

### Expectation

The provider/auth0 go sdk can be more resilient to these transient errors.

The AWS Go SDK has builtin request retry logic that may provide direction to address this issue if you choose to pursue a solution.
[Request Retryer](https://github.com/aws/aws-sdk-go/blob/fde575c64841b291899bc112dfcdc206f609a305/aws/request/retryer.go#L168-L185)

### Reproduction

The errors are infrequent and not easily repeatable.

1. Long terraform plan with remote state refresh enabled (3+ hours). Error is difficult to reproduce consistently. 

### Auth0 Terraform Provider version

0.38.0

### Terraform version

1.1.8

**Comment by sergiught** [comment]
Hey @apm101 👋🏻 

Thanks for reporting this, we've however flagged this as an enhancement that we could do to the provider, rather than a bug within the code. 

What we could do is perhaps extend the retries within the `go-auth0` SDK to also include `syscall.ECONNRESET` (connection reset by peer). 

I don't have an ETA on when we could tackle this, but as always contributions are welcome if you want to give this a go from your end. 

We'll post any updates in this issue.

**Comment by sergiught** [comment]
Hey @apm101      👋🏻 

Retries are now part of the [v1.0.0-beta.0](https://registry.terraform.io/providers/auth0/auth0/latest/docs) release! 🙌🏻 Please give it a try and let us know if you encounter any issues.

```
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "1.0.0-beta.0"
    }
  }
}
```

### 📚 Resources

[Quickstart](https://registry.terraform.io/providers/auth0/auth0/latest/docs/guides/quickstart) | [Documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) | [Migration Guide](https://github.com/auth0/terraform-provider-auth0/blob/v1/MIGRATION_GUIDE.md) | [Changelog](https://github.com/auth0/terraform-provider-auth0/releases/tag/v1.0.0-beta.0)
