### ISSUE TITLE
Support "settings" block on "auth0_email"

### ISSUE THREAD

**Issue by mgroverroku** [auth0/terraform-provider-auth0#384]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The Auth0 Management API allows you to specify a "settings" object when creating/patching an email provider: [https://auth0.com/docs/api/management/v2#!/Emails/post_provider](https://auth0.com/docs/api/management/v2#!/Emails/post_provider)
The Auth0 Terraform does not let you specify a settings block:
`╷
│ Error: Unsupported block type
│ 
│   on email.tf line 34, in resource "auth0_email" "smtp_email_provider":
│   34:   settings {
│ 
│ Blocks of type "settings" are not expected here.
╵`
We specifically want to use this to set X-SES-FROM-ARN headers on emails so that we can perform cross account email sending using AWS SES via SMTP.

### Describe the ideal solution

Support the "settings" block with a sub block of "headers" in line with the Management API.

**Comment by mgroverroku** [comment]
Having looked further into the "headers" part of the settings object, this only supports setting SES Configuration Sets so wouldn't solve our problem, but it would probably still be a good idea for the Template to match the Management API

**Comment by sergiught** [comment]
Hey @mgroverroku 👋🏻 ,

Indeed the `settings` field is not supported yet for the various provider settings. 

However the payload accepted for the SMTP Settings follows this JSON schema:

```
    headers: {
      type: 'object',
      properties: {
        'X-MC-ViewContentLink': {
          type: 'string',
        },
        'X-SES-Configuration-Set': {
          type: 'string',
        },
      },
      additionalProperties: false,
    },
```

`X-SES-FROM-ARN` is not among those so it won't get accepted by the Management API.

And the one for SES Settings:

```
    message: {
      type: 'object',
      properties: {
        configuration_set_name: {
          type: 'string',
        },
      },
      additionalProperties: false,
    },
```

Would these work in your use case?

**Comment by mgroverroku** [comment]
Unfortunately I don't believe they would. The X-MC-ViewContentLink is MailChimp specific and the X-SES-Configuration-Set/configuration_set_name properties don't let you set the headers required by AWS for cross account email sending e.g. X-SES-FROM-ARN.
We can work around it on our side, but it reduces the amount that we can control directly with Terraform.

**Comment by sergiught** [comment]
@mgroverroku thanks for double checking! Unfortunately a request will have to be put through then for the Management API to support the extra headers you require, as without that we can't also support it within the terraform provider. 

I'll leave this issue open tho so we can add support for the settings field for the various providers, as that's something missing right now.

**Comment by sergiught** [comment]
Closing this down, as this is now available in the latest release: https://registry.terraform.io/providers/auth0/auth0/0.40.0.

Docs: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/email#nested-schema-for-settings
