### ISSUE TITLE
Allow initiate_login_uri to contain URLs with fragments as it's supported by Auth0 API

### ISSUE THREAD

**Issue by mlni** [auth0/terraform-provider-auth0#388]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The validation rules for the field `initiate_login_uri` on `auth0_client` resource explicitly reject URLs containing fragments (like https://company.com/#/authorize).

Auth0 API however does support URLs with fragments and the [documentation for the corresponding field](https://auth0.com/docs/authenticate/login/auth0-universal-login/configure-default-login-routes) in the management UI states the URLs may contain fragments. Relevant quote from the documentation:

> Note that it requires https and it cannot point to localhost. login_url can include query parameters _and a URI fragment_.

Pointing the login url against a URL with fragment is useful in case of Single-Page apps that handle authentication on frontend side. It seems likely that the validation rules have been recently relaxed on Auth0 API side.

### Expectation

The `initiate_login_uri` field of `auth0_client` resource to also allow URLs with fragments.

### Reproduction

Given a Terraform block like the following:
```
resource "auth0_client" "repro" {
    name = "Repro case"
    initiate_login_uri = "https://company.com/#/fragment"
}
```
It would be expected that the client validates, but instead it fails with the following error:
> Error: expected "initiate_login_uri" to have a url with an empty fragment. https://company.com/#/fragment

### Auth0 Terraform Provider version

0.37.1

### Terraform version

1.3.3

**Comment by sergiught** [comment]
Closing this down, as this is now available in the latest release: https://registry.terraform.io/providers/auth0/auth0/0.40.0. Thanks again @mlni 👍🏻
