### ISSUE TITLE
auth0_client_grants to manage all grants for an app or api authoritatively

### ISSUE THREAD

**Issue by sergiught** [auth0/terraform-provider-auth0#39]
From terraform-provider-auth0 created by [red8888](https://github.com/red8888): alexkappa/terraform-provider-auth0#403  

`auth0_client_grant` allows us to create a specific grant, but I want to fully control and track all grants made for an app or api. It makes sense to have a resource named like `auth0_client_grants` that takes a map/list of all grants configured for an application (or maybe api or make it configurable).

So if a user manually adds a grant terraform would see that change against the list of grants in the diff. Also, we could import an `auth0_client_grants` resource and it would find and reconcile all grants.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
Hey @red8888 👋🏻 

Apologies for the delay in getting back to you on this issue. 

You could accomplish the desired behavior using a terraform module, where you'd keep track of all your `auth0_resource_server`'s and appropriate scopes and accept as an input variable to this module a clientID, and then simply reference that by passing the ID of your app so it can use all of them. 

E.g.

```terraform
# ./client_grants/main.tf

terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "0.39.0"
    }
  }
}

variable "clientID" {
  description = "The Client ID to assign all the grants to"
  type        = string
}

resource "auth0_resource_server" "myAPI" {
  name        = "My Resource Server"
  identifier  = "https://api.example.com"
  signing_alg = "RS256"

  scopes {
    value       = "create:appointments"
    description = "Create appointments"
  }

  scopes {
    value       = "read:appointments"
    description = "Read appointments"
  }
}

resource "auth0_client_grant" "my_grant" {
  audience  = auth0_resource_server.myAPI.identifier
  client_id = var.clientID
  scope     = auth0_resource_server.myAPI.scopes[*].value # this gives it all the scopes of the resource server
}
```

and then reference that like so:

```terraform
# ./main.tf

terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "0.39.0"
    }
  }
}

provider "auth0" {
  debug = "true"
}

resource "auth0_client" "myClient" {
  name = "My Client"
}

module "all_my_grants" {
  source = "./client_grants"
  clientID = auth0_client.myClient.id
}

```

You could also create another variable to pass it resource server identifiers as well. 

Hope this helps! If you have any questions let us know, we can always reopen and dive deeper into this.

**Comment by gabeio** [comment]
@sergiught I believe the user here was talking about that if a client grant was created via the auth0 ui, terraform would not notice nor alert the user to the fact that a foreign client grant was created and does not match the current terraform configuration.

*Example*:

1. I create a client & a grant:

```
resource "auth0_resource_server" "example" {
  name        = "My Resource Server"
  identifier  = "https://api.example.com"
  signing_alg = "RS256"
}

resource "auth0_client" "myClient" {
  name = "My Client"
}

resource "auth0_client_grant" "my_grant" {
  audience  = auth0_resource_server.example.identifier
  client_id = auth0_client.myClient.id
  scope = []
}
```

2. I go into auth0 ui and enable that myClient to have access to the auth0 management api
3. `terraform plan`/`terraform apply`

^ with those steps when I run `terraform apply` it incorrectly believes everything is fine, when I did _not_ ever want that client to have access to the auth0 management api. There does not seem to be a way to authoritatively control client grants from terraform.

the user in question here was suggesting that a new resource named `auth0_client_grants` be created to authoritatively control _all_ grants from a single client, which seems similar to how there is `connection_client` (singular create/update) & `connection_clients` (authoritative).

The Idea:
```
resource "auth0_resource_server" "exampleA" {
  name        = "My Resource Server"
  identifier  = "https://api.example.com"
  signing_alg = "RS256"
}

resource "auth0_resource_server" "exampleB" {
  name        = "My Resource Server"
  identifier  = "https://api.example.com"
  signing_alg = "RS256"
}

resource "auth0_client" "myClient" {
  name = "My Client"
}

resource "auth0_client_grants" "myClient" {
  client_id  = auth0_client.myClient.id
  grant {
    audience = auth0_resource_server.exampleA.identifier
    scope    = []
  }
  grant {
    audience = auth0_resource_server.exampleA.identifier
    scope    = []
  }
  // if no other grants then these should be the _only_ grants this client has at all.
}
```

I actually am having the same issue and almost opened a separate ticket/issue for this but found this one. I can own this issue if you'd like to re-open it, or I can go ahead and make a new issue.
