### ISSUE TITLE
Feature Request : `auth0_custom_domain_certificate` resource

### ISSUE THREAD

**Issue by BalaGanaparthi** [auth0/terraform-provider-auth0#398]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

When using `auth0_custom_domain` with `type   = "self_managed_certs"` there is no terraform resource available to upload self managed certificate to Auth0 

#### Upload self managed certificate to Auth0
```hcl
resource "auth0_custom_domain_certificate" "certs_to_auth0" {
  domain_id         = auth0_custom_domain.a0_custom_domain.id
  type              = "PEM"
  certificate       = var.certificate
  private_key       = var.private_key
  certificate_chain = var.certificate_chain
  depends_on        = [
    auth0_custom_domain_verification.iamok_domain_verify,
  ]
}
```
Reference to Okta with similar resource [okta_domain_certificate](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/domain_certificate)

### Alternatives and current workarounds

N/A

### Additional context

When custom domain is configured with self manage certificate, the self managed certs must be uploaded to Auth0

**Comment by sergiught** [comment]
Hey @BalaGanaparthi 👋🏻 

If you choose to manage the certificates for your custom domains without assistance from Auth0, you need to know how to manage your own proxy and certificates for inbound connections that require multiple DNS records on the domain. You have to purchase or provide the certificates and manage the renewals yourself. You will also need a reverse proxy where the certificate will be installed. 

You won't be hosting the certificates within the Auth0 tenant. 

Please have a look at: https://auth0.com/docs/customize/custom-domains/self-managed-certificates.
