### ISSUE TITLE
Documentation restructuring

### ISSUE THREAD

**Issue by paulocuambe** [auth0/terraform-provider-auth0#399]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

While reading and using the `resource`s described in the auth0 provider, it was extremely difficult to locate things such as:
1. **Read-only**: well, this title by itself is confusing, adding to that it appears in the middle of the **arguments reference (schema, in the docs)** and it doesn't appear in the _On this page_ link section.
2. **On this page** navigation links do not mention the _Read-only_ attributes section. Which I believe to be one of the most explored sections after defining the resource because you have to use the attributes the resource exports for other things in your Terraform file.

### Describe the ideal solution

My suggestion is that the documentation structure be changed to best describe what the reader wants to accomplish. These suggestions will be based off the **aws** provider and the Terraform documentation https://developer.hashicorp.com/terraform/registry/providers/docs#format.
1. **Change the title _Schema_ to _Argument Reference_**. I suggest this change because it is clearer and it makes it clear that the user should be filling the fields described.
2. **Change the title _Read-Only_ to _Attributes Reference_**. This also makes it clearer that the user should be reading these values and not filling them.
3. **Put the _Read-Only (or Attributes Reference)_ in a section of its own (h2) outside the _Schema/Argument Reference_ section for better visibility**. This also means that it will be after all the _nested schema_ descriptions. The problem with **On this page** section should also be solved by this.

### Additional context

I would like to propose the changes mentioned here because I faced a lot of problems locating things inside the documentation and I lost a lot of time trying to and I think this problem might not be mine alone.

For example due to the unclear _Read-Only_ section I thought that all your resources did not export any attributes so I tried to use `data` to get the attributes. Only few days later did I realize that I should be using those instead.

**I will happily work to make these changes.**

**Comment by paulocuambe** [comment]
I will be starting the work in a fork.

**Comment by sergiught** [comment]
Hey @paulocuambe 👋🏻 ,

Thanks for opening an issue with us. The documentation is generated using HashiCorp's https://github.com/hashicorp/terraform-plugin-docs and it follows the guidelines presented by them. I'd suggest making a proposal for a restructuring over there instead as we won't drop support for automatically generating the docs.

The fact that the " ON THIS PAGE" section doesn't display 3rd level headers is something that can be suggested to the HashiCorp team instead to improve their docs rendering as it isn't something that comes directly from our provider.

**Comment by paulocuambe** [comment]
Alright. Thanks
