### ISSUE TITLE
`universal_login` flag of auth0_tenant resource does not affect anything.

### ISSUE THREAD

**Issue by kshvesov** [auth0/terraform-provider-auth0#402]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Looking at Auth0 Management API I could not find what `universal_login` flag in `auth0_tenant` resource correlates to 
https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/tenant#universal_login. It seems that the flag is excessive and misleading. Is it possible to get rid of it?

### Describe the ideal solution

`universal_login` optional block of `auth0_tenant` resource should be enough to accommodate color settings.

### Alternatives and current workarounds

It does not really looks like the `universal_login` flag is affecting anything.

**Comment by sergiught** [comment]
Hey @kshvesov 👋🏻 

Thanks for raising awareness of this. We added a deprecation notice and clarified what the flag is used for in the latest release: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/tenant#nested-schema-for-flags
