### ISSUE TITLE
Incomplete documentation for client_secret_rotation_trigger

### ISSUE THREAD

**Issue by reify-tanner-stirrat** [auth0/terraform-provider-auth0#404]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

This is the current documentation:

> [client_secret_rotation_trigger](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/client#client_secret_rotation_trigger) (Map of String) Custom metadata for the rotation. For more info: [rotate-client-secret](https://auth0.com/docs/get-started/applications/rotate-client-secret).

`rotate-client-secret`'s documentation has no reference to the `client_secret_rotation_trigger`.

What is this metadata? How is it used? What does it affect? What can I do with it?

### Expectation

Answers to any of the above questions.

I'm happy to provide a PR to update the documentation once I have answers to this.

The problem I'm trying to solve that led me to this place is:

We have our Auth0 resources managed in Terraform. We need to rotate a couple of the secrets, ideally in a way that is managed and then picked up by Terraform so that it can be propagated outwards to other applications by AWS Keymanager.

It'd also be nice to know how long old keys are valid after a rotation - the only understanding I can glean from the current documentation is that the old secret is immediately invalidated, which is a problem when we need to propagate changes without downtime.

### Reproduction

N/A

### Auth0 Terraform Provider version

0.40.0

### Terraform version

N/A

**Comment by sergiught** [comment]
Hey @reify-tanner-stirrat 👋🏻 

Thanks for opening the issue and apologies for the late reply! 

Indeed, we could do a better job explaining what the `client_secret_rotation_trigger` attribute does. 

In short, the presence of the attribute is a trigger to rotate the `client_secret`. It doesn't necessarily need to be set to any value it can also be just `client_secret_rotation_trigger = { }`. However we allow for any arbitrary custom metadata to be included in order to help cover a variety of use cases. 

For example:

```
client_secret_rotation_trigger = {
		triggered_at = "2022-12-012T16:12:01Z"
		triggered_by = "sergiught"
}
```

The contents of the trigger won't affect the resource in any way. 

This might help for avoiding downtime as well: https://community.auth0.com/t/rotating-client-application-secret-without-downtime/90732.

**Comment by reify-tanner-stirrat** [comment]
I appreciate the clarification on the documentation. I'll submit a PR to improve it.

I've seen your documentation around maintaining two secrets. These are the stated prerequisites:

* The system relies on the configuration to maintain either a list of client secrets or at least two separate configuration entries (CURRENT and NEXT) representing client secrets.
* By default, the system uses the first client secret in the list or the CURRENT configuration entry. If an error is received during an exchange that requires client authentication and the error is known to be associated with a problem related to client credentials, the system should be capable of retrying the operation using the next secret in the list or the NEXT configuration entry.
* If an event occurs that forces the system to attempt to use the next secret in the list or the NEXT configuration entry and the operation succeeds when using the new secret, the system should discard the old secret and update the configuration in a way that the next secret (the one that succeeded) is considered to be the default/current one going forward.

This seems to carry an implicit assumption that keys are managed by the individual application, and doesn't seem to account for the industry standards around key management whereby keys are held at the infrastructure level in something like AWS Key Manager or Hashicorp Vault and then provided to applications as environment variables or secrets. It seems to imply application-level dynamic key management, which not every company will have implemented, nor will have engineering time to implement.

Other platforms provide mechanisms whereby multiple keys are considered valid, and key rotation involves creating a new key, propagating it while both are active, and then removing the old one. Is there a technical reason that this isn't possible for application client secrets? Otherwise this seems like a poor DX.

It seems that we'd have a potential workaround by creating an entirely new client application that is identical to the old one except for name, walking over our configuration to use it, and then removing the old application, which is the same idea as multiple keys, except with extra steps and incidental complexity. Is that basically my only option for a downtimeless rotation if I don't have dynamic key management in place? If so, this seems like something that should be clearly caveated in the key rotation documentation, not buried in a community post.
