### ISSUE TITLE
cannot manage auth0 management api with terraform

### ISSUE THREAD

**Issue by hkolvenbach** [auth0/terraform-provider-auth0#407]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Referring to https://github.com/auth0/terraform-provider-auth0/pull/374, it should be possible to modify the auth0 management API via terraform, however, this does not seem to work for me as expected, the following code in a terraform module fails:
```
resource "auth0_resource_server" "auth0" {
	name = "Auth0 Management API"
	identifier = var.auth0-mgmt-api-identifier
	token_lifetime = 86400
	skip_consent_for_verifiable_first_party_clients = false
}

## grant access to management api
resource "auth0_client_grant" "mgmt_api_grant" {
  client_id = auth0_client.client-service.id
  audience  = auth0_resource_server.auth0.identifier
  scope = ["create:user_tickets",
          "create:users",
          "read:users",]
}
```

(`var.auth0-mgmt-api-identifier` contains the identifier found in the auth0 dashboard).

With the following error message:

```
Error: 400 Bad Request: The identifier https://<tenant>.eu.auth0.com/api/v2/ is not available for use, as it is reserved by Auth0.
│ 
│   with module.auth0_config.auth0_resource_server.auth0,
│   on ../../modules/auth0/main.tf line 16, in resource "auth0_resource_server" "auth0":
│   16: resource "auth0_resource_server" "auth0" {
```

### Expectation

I should be able to modify the settings of the auth0 management API via terraform.

### Reproduction

This is a minimal configuration that fails for me:

```
resource "auth0_resource_server" "auth0" {
	name = "Auth0 Management API"
	identifier = var.auth0-mgmt-api-identifier
	token_lifetime = 86400
	skip_consent_for_verifiable_first_party_clients = false
}

## grant access to management api
resource "auth0_client_grant" "mgmt_api_grant" {
  client_id = auth0_client.client-service.id
  audience  = auth0_resource_server.auth0.identifier
  scope = ["create:user_tickets",
          "create:users",
          "read:users",]
}
```

### Auth0 Terraform Provider version

0.40

### Terraform version

1.3.5

**Comment by sergiught** [comment]
Hey @hkolvenbach 👋🏻 

Apologies for the late reply! 

If you want to manage the auth0 management api, you'll first need to import and only after change the desired settings. 

e.g. 

```terminal
terraform import auth0_resource_server. auth0 XXXXXXXXXXXXXXXXXXXXXXX
```

You can find the ID within the Auth0 Dashboard.

**Comment by sergiught** [comment]
Hey @hkolvenbach I'll go ahead and close this issue as we haven't heard back from you. In case you're still encountering any difficulties managing the auth0 management api resource please feel free to reopen or leave a message over here.

**Comment by hkolvenbach** [comment]
@sergiught sorry for the late reply. Yes, this can be closed for now, I think I did miss the terraform import.

**Comment by hkolvenbach** [comment]
Just to confirm as I have been working on this again: `terraform import` did indeed solve this.
