### ISSUE TITLE
Support for custom database connections breaks when enabling script context

### ISSUE THREAD

**Issue by matthosking-mydeal** [auth0/terraform-provider-auth0#410]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Once you've enable custom database context for a connection, the provider leaves `enable_script_context` as `false` since it is not supported, causing:
```
│ Error: 400 Bad Request: once enabled, options.enable_script_context can not be disabled
```

### Expectation

Either the API needs to not set any value (leave as is) when not provided, or support for `enable_script_context` will need to be added to the connection options.

### Reproduction

1. Given an auth0 connection with a custom database created with Terraform.
2. When `Context object in database scripts` is enabled for the connection.
3. Then any further attempts to run Terraform against the connection fail with the 400 error: `once enabled, options.enable_script_context can not be disabled`

### Auth0 Terraform Provider version

0.40

### Terraform version

1.3.6

**Comment by sergiught** [comment]
Hey @matthosking-mydeal 👋🏻 

Thanks for bringing this to our attention. I have a fix in https://github.com/auth0/terraform-provider-auth0/pull/452 but it depends on https://github.com/auth0/go-auth0/pull/158 first getting merged. I'll give you an update when this gets released. 

What happens is that unfortunately the options block needs to be sent with all its properties even if we're sending a `PATCH`. So if you have a db connection with script context enabled we need to send that in the options block as true, not sending it makes the request fail, as seen above.

**Comment by sergiught** [comment]
Hey @matthosking-mydeal 👋🏻 this is now fixed within the latest release https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.43.0. Please check it out and let us know if you encounter any issues. You'll now need to set the `enable_script_context` as true within the config to not get the error any more.
