### ISSUE TITLE
`auth0_branding_theme` requires all args

### ISSUE THREAD

**Issue by TiltUp-Rad** [auth0/terraform-provider-auth0#412]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

`auth0_branding_theme` schema requires all fields (which made me click around manually in the end - I do NOT want to provide all the arguments - auth0 defaults work well for me except a couple of exceptions)
meanwhile `auth0_branding` has all fields optional (which is nice and easy to use)

### Expectation

`auth0_branding_theme` fields are optional, just like `auth0_branding`

### Reproduction

go to `https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/branding_theme`

### Auth0 Terraform Provider version

0.40.0

### Terraform version

1.3.5

**Comment by sergiught** [comment]
Hey @TiltUp-Rad 👋🏻 

Thanks for opening an issue! 

The provider leverages the Auth0 Management API in order to manage branding themes through e.g. https://auth0.com/docs/api/management/v2#!/Branding/post_branding_theme. As you can see almost all the arguments are required when executing this request. 

We could however provide sensible defaults within the provider code to be sent to the API, perhaps using the ones available when no branding theme is set. What do you think? 🤔 

I'll mark this as a feature request instead as this is not currently a bug.

**Comment by TiltUp-Rad** [comment]
hey @sergiught
yes, providing sensible defaults sounds like a great idea :) 

cheers,
Rad

**Comment by TiltUp-Rad** [comment]
oh someone actually picked it up. you guys are amazing <3

**Comment by sergiught** [comment]
Hey @TiltUp-Rad 👋🏻 indeed:) @nialdaly did an awesome contribution 💪🏻 We will be able to merge that in today and cut a release. 

However instead of 

```
resource "auth0_branding_theme" "my_theme" { }
```

We will have the following as the minimal config

```
resource "auth0_branding_theme" "my_theme" { 
  borders {}
  colors {}
  fonts {
    title {}
    subtitle {}
    links {}
    input_labels {}
    buttons_text {}
    body_text {}
  }
  page_background {}
  widget {}
}
```

Would this work for your use case?

**Comment by TiltUp-Rad** [comment]
yup. that works as well :) 
cheers

**Comment by sergiught** [comment]
This is now available within the latest release https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.44.1 :) Thanks again @TiltUp-Rad for raising the issue with us!

**Comment by nialdaly** [comment]
Thanks! @sergiught for your work and guidance on it 😀
