### ISSUE TITLE
Can't apply changes on imported them with id `default`

### ISSUE THREAD

**Issue by cesararroba** [auth0/terraform-provider-auth0#430]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After importing my theme from Auth0 with id `default` and changing some colors I'm not being able to apply them due to the following error:

```
│ Error: 400 Bad Request: Path validation error: 'Object didn't pass validation for format theme-id: default' on property themeId (The ID of the theme).
```

### Expectation

I expected it to apply.

### Reproduction

1. Import the theme with id `default`
2. Change some attributes, in my case, some colors.
3. Get the error.

### Auth0 Terraform Provider version

0.42.0

### Terraform version

1.2.6

**Comment by whoward** [comment]
Hey @cesararroba check out [406](https://github.com/auth0/terraform-provider-auth0/issues/406#issuecomment-1329478708)

**Comment by cesararroba** [comment]
> Hey @cesararroba check out [406](https://github.com/auth0/terraform-provider-auth0/issues/406#issuecomment-1329478708)

That worked for me, thanks!
