### ISSUE TITLE
Universal Login bodies in auth0_branding resources are always detected as new

### ISSUE THREAD

**Issue by whoward** [auth0/terraform-provider-auth0#432]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, I'm trying to use the `auth0_branding` resource to set the template for universal login.  After applying the template is correctly set, but on subsequent applies the provider does not recognize the template as created and attempts to create it again.

### Expectation

The template should be set once and should not need any further changes in subsequent applies so long as the intended and actual values are both identical.

### Reproduction

- use the following resource:
```hcl
resource "auth0_branding" "branding" {
  logo_url = "https://mycompany.org/logo.png"

  colors {
    primary = "#1994FC"
    page_background = "#000000"
  }

  universal_login {
    body = <<EOS
      <!DOCTYPE html><html>
        <head>
          {%- auth0:head -%}
        </head>
        <body>
          <h1>This is custom</h1>
          {%- auth0:widget -%}
        </body></html>
    EOS
  }
}
```
- a custom domain must be assigned to the tenant in order to modify the body of the universal logic object
- Run `terraform apply` once to create the universal login template
- Run `terraform apply` again, the plan will suggest that the universal login template does not exist and will attempt to recreate it

This issue can be reproduced consistently.

### Auth0 Terraform Provider version

0.42.0

### Terraform version

1.3.2

**Comment by sergiught** [comment]
Hey @whoward 👋🏻 

Thanks for bringing this to our attention. I was able to reproduce this and understand what's wrong. I'm gonna start working on a fix soon. I'll keep you posted.

**Comment by sergiught** [comment]
A potential fix is available at https://github.com/auth0/terraform-provider-auth0/pull/446.

**Comment by sergiught** [comment]
Hey @whoward  👋🏻 this is now available in the latest release https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.43.0. Please check it out and let us know if you encounter any issues.

**Comment by whoward** [comment]
Hi @sergiught
I've just tested it out and it seems like it's working perfectly, thanks!
