### ISSUE TITLE
Support for "Custom Login Page" for classic universal login page

### ISSUE THREAD

**Issue by ad8lmondy** [auth0/terraform-provider-auth0#434]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

It would be nice if the Auth0 TF provider supported custom login pages for the classic login, e.g: https://auth0.com/docs/customize/universal-login-pages/customization-classic#modify-the-page-code

### Describe the ideal solution

A similar implementation to the 'universal login' part of https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/branding

### Alternatives and current workarounds

No work around as far as I know.

**Comment by felixcolaci** [comment]
Hi @ad8lmondy , to update the custom login page for classic ul you can use the global_client resource in the current implementation. It contains the classic ul page.
https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/global_client

**Comment by ad8lmondy** [comment]
Wow, you are totally correct!
Sorry about that, thanks for the steer!
