### ISSUE TITLE
Connection w/ Okta strategy causes subsequent Terraform runs to report that some options are being set to null

### ISSUE THREAD

**Issue by Aaronius** [auth0/terraform-provider-auth0#435]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We're creating a connection using the Okta strategy. I am not setting `authorization_endpoint`, `issuer`, `jwks_uri`, `token_endpoint`, or `user_info` endpoint, because the documentation states that they are optional fields and I don't see the fields in Auth0's dashboard UI. I'm also able to successfully apply the connection to Auth0 through Terraform and am able to authenticate to our app using the connection.

At this point, every time why attempt to apply changes that are unrelated to this connection, the terraform plan shows that we're attempting to set the above-mentioned options to null.

```
 # auth0_connection.****** (******) will be updated in-place
   ~ resource "auth0_connection" "******" {
         id                   = "con_XXXXXXXXXXXXX"
         name                 = "******-okta"
         # (6 unchanged attributes hidden)

       ~ options {
           - authorization_endpoint         = "https://******.okta.com/oauth2/v1/authorize" -> null
           - issuer                         = "https://******.okta.com" -> null
           - jwks_uri                       = "https://******.okta.com/oauth2/v1/keys" -> null
           - token_endpoint                 = "https://******.okta.com/oauth2/v1/token" -> null
           - userinfo_endpoint              = "https://******.okta.com/oauth2/v1/userinfo" -> null
             # (29 unchanged attributes hidden)
         }
     }
```

### Expectation

I would expect no changes related to the connection to be reported.

### Reproduction

1. Create a connection similar to this:

```
const connection = new Connection(stackScope, 'example', {
    name: 'example-okta',
    strategy: 'okta',
    // Terraform doesn't yet support managing the button icon, so we have to do that
    // manually through the Auth0 dashboard.
    showAsButton: true,
    displayName: 'Example Okta',
    options: {
      domain: 'example.okta.com',
      clientId: CLIENT_ID,
      clientSecret: CLIENT_SECRET,
    },
  });
 ```
 
 2. Run terraform to create the connection in Auth0.
 3. Make an unrelated terraform changes.
 4. Run the terraform plan.
 5. Notice that you'll see a plan similar to what I outlined in this issue description even though your changes were unrelated to the connection.

### Auth0 Terraform Provider version

0.42.0

### Terraform version

1.3.7

**Comment by sergiught** [comment]
Hey @Aaronius 👋🏻 Thanks for bringing this to our attention. A fix is available within https://github.com/auth0/terraform-provider-auth0/pull/443 and it will ship in the upcoming release next week. 

Regarding

```
// Terraform doesn't yet support managing the button icon, so we have to do that
// manually through the Auth0 dashboard.
```

Would you mind creating a separate issue for it? 🙏🏻 Given the time we might be able to ship that as well within the next release.

**Comment by Aaronius** [comment]
Great! Yeah, I'll create a ticket for the button icon. We've run into a few other issues and gaps as well. I'll try to write up issues for them.

**Comment by sergiught** [comment]
Hey @Aaronius  👋🏻 this is now fixed within the latest release [v0.43.0 (release)](https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.43.0). Please check it out and let us know if you encounter any issues.

**Comment by Aaronius** [comment]
Thank you! Will do as soon as possible.

**Comment by Aaronius** [comment]
I've verified this fixed the issue. Thanks!
