### ISSUE TITLE
missing segment log stream integration option

### ISSUE THREAD

**Issue by yundifu** [auth0/terraform-provider-auth0#436]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

integrate log stream with segment 

### Describe the ideal solution

have `sink` option in https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/log_stream for segment integration 

### Alternatives and current workarounds

manual set up

**Comment by sergiught** [comment]
Hey @yundifu, support for Segment Log Stream was added through https://github.com/auth0/terraform-provider-auth0/pull/437. We'll ship a release containing it next week.

**Comment by sergiught** [comment]
Hey @yundifu   👋🏻 this is now available in the latest release https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.43.0. Please check it out and let us know if you encounter any issues. https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/log_stream#segment_write_key
