### ISSUE TITLE
Action dependency for node-fetch incorrectly tracked

### ISSUE THREAD

**Issue by Aaronius** [auth0/terraform-provider-auth0#448]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We're creating an action within Terraform. We've listed `node-fetch` and `@datadog/datadog-api-client` as dependencies. The `dependencies` property on the action resource in Terraform looks basically like this:

```
const createThing = new Action(
    stackScope,
    'create-thing',
    {
      name: 'Creates a thing',
      runtime: 'node16',
      deploy: true,
      code: '...',
      supportedTriggers: {
        id: 'post-login',
        version: 'v3',
      },
      dependencies: [
        {
          name: 'node-fetch',
          version: '2.6.7',
        },
        {
          name: '@datadog/datadog-api-client',
          version: '1.6.0',
        },
      ],
    },
  )
```

We are not bundling `node-fetch` or `@datadog/datadog-api-client` into the bundled code; we're relying on Auth0 to provide the dependencies to our action code.

We've successfully deployed the action and it functions properly. However, every time we go to deploy unrelated Terraform changes, the Terraform plan shows that we're always adding `node-fetch` as a dependency:

```
auth0-terraform    # auth0_action.create-thing (create-thing) will be updated in-place
                   ~ resource "auth0_action" "create-thing" {
                         id         = "[redacted]"
                         name       = "Creates a thing"
                         # (4 unchanged attributes hidden)

                       + dependencies {
                           + name    = "node-fetch"
                           + version = "2.6.7"
                         }

                         # (8 unchanged blocks hidden) 
```

What's even more interesting and what makes me think this issue may extend beyond Terraform, is that the Auth0 dashboard UI for the action only shows the `@datadog/datadog-api-client` dependency and not the `node-fetch` dependency:

<img width="325" alt="image" src="https://user-images.githubusercontent.com/210820/215298590-e2d25cb0-55f2-4ebd-859e-5085de352ef5.png">

Yet I still see within the dashboard's code editor where our code requires `node-fetch`:

```
var j=require("node-fetch")
```

And the action still functions properly.

### Expectation

When we go to deploy unrelated Terraform changes, the Terraform plan should not be showing that we're adding the `node-fetch` dependency to the action since we deployed that change previously.

I would also expect the Auth0 dashboard to show that `node-fetch` has in fact been added as a dependency.

### Reproduction

Let me know if you need more detail than what I provided above.

### Auth0 Terraform Provider version

0.42.0

### Terraform version

1.3.7

**Comment by sergiught** [comment]
Hey @Aaronius 👋🏻 

I tried to reproduce the issue but unfortunately I was unable to. I'm also noticing that you aren't using terraform directly but a wrapper kit like [cdktf](https://developer.hashicorp.com/terraform/cdktf)? That might be one of the reasons why you're experiencing the issue. 

I used the following sample to try to reproduce:

```terraform
resource "auth0_action" "test" {
  name = "tf-issue448"
  runtime = "node16"
  code = <<EOF
exports.onExecutePostLogin = async (event, api) => {
  var j=require("node-fetch")
  console.log("test");
}
EOF
  supported_triggers {
    id      = "post-login"
    version = "v3"
  }
  dependencies {
    name    = "node-fetch"
    version = "2.6.7"
  }
  dependencies {
    name    = "@datadog/datadog-api-client"
    version = "1.6.0"
  }
}
```

Running multiple terraform apply's I get:

```
No changes. Your infrastructure matches the configuration.
```

And within the dashboard I can see both of the dependencies listed:

![image](https://user-images.githubusercontent.com/28300158/215492696-3a24873b-6cac-407e-9e14-75f0c8e4ca4c.png)

**Comment by sergiught** [comment]
We did have some issues in https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.34.0 with the dependencies block on the auth0_action, so I'd make sure you're using the latest version when you're fetching the provider 0.42.0.

**Comment by Aaronius** [comment]
I figured this one might be tricky to reproduce.  We are using cdktf. We'll try to fix it on our side by removing the action and adding it back, etc. I'll close this for now. If you're wanting to debug more on your end, I can give you the ID of the action in question. I'd prefer to send it privately though. I really think it might have more to do with an invalid state in the Auth0 DB considering we don't see node-fetch as a dependency and yet the action still functions correctly. I'll let you know if I find out more.

**Comment by Aaronius** [comment]
FYI, something unrelated to the terraform provider fixed this issue.
