### ISSUE TITLE
Add support for configuring connection logo

### ISSUE THREAD

**Issue by Aaronius** [auth0/terraform-provider-auth0#449]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The provider doesn't currently provide any way to configure the logo for a connection, but the Auth0 Dashboard supports it:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/210820/215299224-4cc8dfe9-ac3e-4924-be17-247dbf7dfb1b.png">

### Describe the ideal solution

A property on the connection resource that allows us to configure the logo. For example:

```
const connection = new Connection(stackScope, 'example', {
    name: 'example-okta',
    strategy: 'okta',
    showAsButton: true,
    buttonLogoUrl: 'http://example.com/logo.png',
    displayName: 'Example Okta',
    options: {
      domain: 'example.okta.com',
      clientId: CLIENT_ID,
      clientSecret: CLIENT_SECRET,
    },
  });
```

### Alternatives and current workarounds

We have to configure the logo through the dashboard.

**Comment by sergiught** [comment]
Hey @Aaronius 👋🏻 this is now available in the latest release. https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.43.0 You can now use the `icon_url` option to set the logo url for okta connections as well.

**Comment by Aaronius** [comment]
Excellent. Thank you!

**Comment by Aaronius** [comment]
I've verified this works. Thanks!
