### ISSUE TITLE
Need to replace `cross_origin_auth` argument to `cross_origin_authentication` in `auth0_client` resource

### ISSUE THREAD

**Issue by naru200** [auth0/terraform-provider-auth0#450]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [x] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The 'cross_origin_auth' attribute no longer works correctly in the client API of Auth0 Management API V2. I checked this through Auth0 Support Center. 

Since the 'cross_origin_authentication' property works normally, it needs to be replaced with this.

### Expectation

Can control cross-origin authentication option by using the 'cross_origin_authentication' argument to the auth0_clients resource.

### Reproduction

_Check that the `cross_origin_auth` argument is not working properly_
1. Create `auth0_client` resource, and set the `cross_origin_auth` argument to false.
2. terraform apply
3. In the Auth0 Dashboard, you can see that the Allow Cross-origin Authentication setting is still turned on.

### Auth0 Terraform Provider version

0.42.0

### Terraform version

1.3.7

**Comment by sergiught** [comment]
Thanks for bringing this to our attention @naru200 👋🏻 

I'll work on a fix today and we'll aim at squeezing it into the upcoming release ETA: ~ this week.

**Comment by sergiught** [comment]
Fix available within the Go SDK: https://github.com/auth0/go-auth0/pull/159. But not yet released.

**Comment by sergiught** [comment]
Hey @naru200  👋🏻  this is now available in the latest release. https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.43.0. We kept the `cross_origin_auth` schema name  but under the hood it uses the `cross_origin_authentication` json tag when sending the payload to the server. This was done to prevent introducing a breaking change for users. You can also check the updated docs in https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/client#cross_origin_auth.
