### ISSUE TITLE
Support "Federation Metadata" for ADFS connection

### ISSUE THREAD

**Issue by SimonG-Kontentai** [auth0/terraform-provider-auth0#454]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

auth_connection for ADFS connection only supports using adfs_server, but Auth0 has a second option -> using Federation Metadata
![image](https://user-images.githubusercontent.com/113501264/215455036-10bc982b-cd5b-4a75-9aee-e50f758cfe3a.png)

### Describe the ideal solution

Option to use the Federation Metadata file instead of adfs_server.

### Alternatives and current workarounds

Maybe I could use "metadata_xml", but if I define a value for this property, I get "Error: 400 Bad Request: missing federation metadata url"

[metadata_url](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection#metadata_url) (String) The URL of the SAML metadata document.
[metadata_xml](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection#metadata_xml) (String) The XML content for the SAML metadata document.

### Additional context

https://community.auth0.com/t/create-adfs-connection-with-federation-metadata-file-using-auth0-terraform-provider/90055/1

**Comment by sergiught** [comment]
Hey @SimonG-Kontentai 👋🏻  this is now available in the latest release. https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.43.0 You can now use the `fed_metadata_xml` option to set the metadata directly for adfs connections.
