### ISSUE TITLE
ADFS connections are not properly saved to the state

### ISSUE THREAD

**Issue by SimonG-Kontentai** [auth0/terraform-provider-auth0#455]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have definition as 
```
resource "auth0_connection" "adfs" {
  for_each = local.adfs_connections

  name                 = each.value.name
  display_name         = each.value.display_name
  strategy             = each.value.strategy
  show_as_button       = each.value.show_as_button
  is_domain_connection = each.value.is_domain_connection

  options {
    adfs_server                            = each.value.options.adfs_server
    tenant_domain                          = each.value.options.tenant_domain
    domain_aliases                         = each.value.options.domain_aliases
    sign_in_endpoint                       = each.value.options.signInEndpoint
    should_trust_email_verified_connection = each.value.options.should_trust_email_verified_connection
    }
}
```
but everytime I run terraform plan, it shows this changes:

```
  ~ resource "auth0_connection" "adfs" {
        id                   = "_id of the generated connection_"
        name                 = "_name of the generated connection_"
        # (6 unchanged attributes hidden)

      ~ options {
          + adfs_server                    = "_adfs_server of the generated connection_" -> **this should be saved in state**
          + allowed_audiences              = []
          + api_enable_users               = false
          + auth_params                    = {}
          + brute_force_protection         = false
          + configuration                  = (sensitive value)
          + custom_scripts                 = {}
          + debug                          = false
          + disable_cache                  = false
          + disable_sign_out               = false
          + disable_signup                 = false
          + domain_aliases                 = []
          + enabled_database_customization = false
          + forward_request_info           = false
          + import_mode                    = false
          + ips                            = []
          + non_persistent_attrs           = []
          + pkce_enabled                   = false
          + requires_username              = false
          + scopes                         = []
          + scripts                        = {}
          + sign_saml_request              = false
          + strategy_version               = 0
          + use_cert_auth                  = false
          + use_kerberos                   = false
          + use_wsfed                      = false
          + waad_common_endpoint           = false
        }
    }
```
Command "terraform state show" shows

```
resource "auth0_connection" "adfs" {
    id                   = "_id of the generated connection_"
    name                 = "_name of the generated connection_"
   ...
    options {
        allowed_audiences    = []
        auth_params          = {}
        configuration        = (sensitive value)
        custom_scripts       = {}
        domain_aliases       = []
        ips                  = []
        non_persistent_attrs = []
        scopes               = []
        scripts              = {}
    }
}
```

### Expectation

Terraform plan should not provide any updates if no change has been made

### Reproduction

1. Create definition of ADFS connection via auth0_connection
2. terraform apply
3. terraform plan

### Auth0 Terraform Provider version

0.42.0

### Terraform version

1.3.7

**Comment by sergiught** [comment]
Hey @SimonG-Kontentai 👋🏻 Thanks for bringing this to our attention. I was able to reproduce and understand what's going wrong. The fix is actually within the Go SDK as unfortunately we missed correctly unmarshalling the ADFS connection options. https://github.com/auth0/go-auth0/pull/160

I'll report back here when this is available in a release.

**Comment by sergiught** [comment]
Hey @SimonG-Kontentai 👋🏻  this is now fixed in the latest release. https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.43.0
