### ISSUE TITLE
new auth0_branding apply fails when only defining universal_login

### ISSUE THREAD

**Issue by hugues-lacoursiere-zinnia** [auth0/terraform-provider-auth0#466]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi,
When adding an "auth0_branding" resource, if I only define the "universal_login" attribute, applying it will fail with the following error:
```
Error: 400 Bad Request: Payload validation error: 'Too few properties defined (0), minimum 1'.

  on auth0/branding.tf line 18, in resource "auth0_branding" "test_branding":
  18: resource "auth0_branding" "test_branding" {
```
After that, the resource becomes tainted and must be recreated in the next apply (which fails again).

If I add the "logo_url" attribute (as is the case in the documentation examples), it will work. But this field is supposed to be optional so it shouldn't be happening.

Thanks

### Expectation

Every field in the "auth0_branding" resource should be optional according to the documentation (https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/branding).

### Reproduction

1. For any auth0 tenant that doesn't have a branding resource already, add this :
```tf
resource "auth0_branding" "test_branding" {
  universal_login {
    body = file("path/to/file.html")
  }
}
```
2. terraform apply, it will fail
3. Add the logo_url attribute
```tf
resource "auth0_branding" "test_branding" {
  logo_url = "https://path/to/logo.svg"
  universal_login {
    body = file("path/to/file.html")
  }
}
```
4. terraform apply, it will succeed

### Auth0 Terraform Provider version

0.43

### Terraform version

0.14.8

**Comment by sergiught** [comment]
Hey @hugues-lacoursiere-zinnia 👋🏻 

Thanks for bringing this to our attention. We fixed this within the latest release [v0.44.0](https://registry.terraform.io/providers/auth0/auth0/0.44.0/docs). Give it a try and let us know if you encounter any issues! 🙏🏻
