### ISSUE TITLE
In auth0_client default for jwt_configuration.alg should be RS256

### ISSUE THREAD

**Issue by sergiughf** [auth0/terraform-provider-auth0#48]
From terraform-provider-auth0 created by [abbaspour](https://github.com/abbaspour): alexkappa/terraform-provider-auth0#459  

In auth0_client, default for jwt_configuration.alg is HS256 which is not best practice. appreciate if you can change the default to RS256 is future.

**Comment by sergiughf** [comment]
We don't currently set any default value for the alg property: https://github.com/auth0/terraform-provider-auth0/blob/2b8e26891a8d584dcb298785773d0210e8d6a300/auth0/resource_auth0_client.go#L148-L151. Any defaults are set by the API itself. Will close this down because of this.

**Comment by kenkoooo** [comment]
I had the same issue and couldn't find any default value in go-auth0 or terraform-provider-auth0.

I tried `[/api/v2/clients](https://auth0.com/docs/api/management/v2#!/Clients/post_clients)` without `alg` and got a client with `HS256`, so I guess the value is filled in the server side.
