### ISSUE TITLE
Support "disable_self_service_change_password" option for database connections

### ISSUE THREAD

**Issue by djkrul-nlo** [auth0/terraform-provider-auth0#486]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The management API provides a boolean option to disable "self service change password", but the terraform provider doesn't support it.

See: https://auth0.com/docs/api/management/v2#!/Connections/patch_connections_by_id

### Describe the ideal solution

Support the disable_self_service_change_password option for database connections.

### Additional context

For more context: 

https://community.auth0.com/t/how-to-remove-the-forgot-password-link-from-the-new-universal-login-page/92554

**Comment by sergiught** [comment]
Hey @djkrul-nlo 👋🏻 thanks for bringing this to our attention. We'll first need to add support for this within the Go SDK that this provider leverages: https://github.com/auth0/go-auth0. We'll try to allocate some time to tackle this in the upcoming weeks.

**Comment by sergiught** [comment]
Hey @djkrul-nlo    👋🏻 

This is now supported in the latest release[v0.45.0](https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.45.0).  Please give it a go and let us know if you have any issues with it. Thanks!

Docs: https://registry.terraform.io/providers/auth0/auth0/0.45.0/docs
