### ISSUE TITLE
Missing prompt types from auth0_prompt_custom_text resource

### ISSUE THREAD

**Issue by Gipphe** [auth0/terraform-provider-auth0#497]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Specifying `login-passwordless` or `logout` in `auth0_prompt_custom_text`'s `prompt` field produces an error.

This despite that `login-passwordless` and `logout` are recognized prompt types in [Auth0's documentation](https://auth0.com/docs/customize/universal-login-pages/customize-login-text-prompts#prompt-values).

### Expectation

The custom prompt text should be applied and posted.

### Reproduction

Running a `terraform plan` with the given resource:

```hcl
resource "auth0_prompt_custom_text" "example" {
  prompt   = "login-passwordless"
  language = "en"
  body = jsonencode(
    {
      "login-passwordless-email-code" : {
        "pageTitle" : "Log in"
      }
    }
  )
}
```

Produces the following error:

```text
Error: expected prompt to be one of [login login-id login-password login-email-verification signup signup-id signup-password reset-password consent mfa-push mfa-otp mfa-voice mfa-phone mfa-webauthn mfa-sms mfa-email mfa-recovery-code mfa status device-flow email-verification email-otp-challenge organizations invitation common], got login-passwordless
│ 
│   with auth0_prompt_custom_text.example,
│   on example.tf line 2, in resource "auth0_prompt_custom_text" "example":
│  2:   prompt   = "login-passwordless"
```

This same issue appears with the `logout` prompt type.

### Auth0 Terraform Provider version

0.43.0

### Terraform version

1.3.6

**Comment by sergiught** [comment]
Hey @Gipphe 👋🏻 

Thanks for bringing this to us. We added the missing prompt types in the latest release: https://registry.terraform.io/providers/auth0/auth0/0.44.0/docs/resources/prompt_custom_text#required.
