### ISSUE TITLE
Connection data source errors with "Unmanaged Configuration Secret"

### ISSUE THREAD

**Issue by CaffeinatedCM** [auth0/terraform-provider-auth0#515]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When attempting to use the `auth0_connection` data source I get a lot of errors that look like the following:

```
Error: Unmanaged Configuration Secret

   .....

Detected a configuration secret not managed through terraform: "USER_POOL_ID". If you proceed, this configuration secret will get deleted. It is required to add this configuration secret to your custom database settings to prevent unintentionally destructive results.
```

My data source is defined as:

```hcl
data "auth0_connection" "users_connection" {
    name = "Users"
}
```

I want to read this so that I can create a `auth0_connection_client` resource to attach the connection to a client I am also creating.

### Expectation

Terraform Data Sources are meant to be read only, so I shouldn't get an error about things not being defined in terraform at all, and the error shouldn't tell me using the data source is potentially destructive on a read only type.

### Reproduction

1. Create a data block of type `auth0_connection` 
2. Run `terraform plan` and see the errors

### Auth0 Terraform Provider version

0.44.0

### Terraform version

1.3.9

**Comment by sergiught** [comment]
Hey @CaffeinatedCM 👋🏻 Thanks for raising this! I'll look into providing a fix ASAP.

**Comment by sergiught** [comment]
This is now fixed within the latest https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.44.1 

Thanks again @CaffeinatedCM for raising the issue with us!

**Comment by CaffeinatedCM** [comment]
Works great, thanks @sergiught !
