### ISSUE TITLE
Documentation: auth0_role permissions incorrectly references name instead of value

### ISSUE THREAD

**Issue by naebliss** [auth0/terraform-provider-auth0#520]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The `auth0_role` resource nested `permissions` resource documentation is incorrect.
It states that the `name` property of the nested resource references the `name` of the `auth0_resource_server` nested `scopes` resource, instead it references the `scopes.value` property.
This may lead to some confusion.

Although the docs provide an example it can be hard to miss the difference in writing between the resource server scope value and the permission scope value
 

### Expectation

I would expect one of the following:
- the permissions `name` field be named to reflect that it references scope, e.g. scope.
- the documentation to reflect that the field is referencing the `value` property instead of the `name` property.

### Reproduction

n/a

### Auth0 Terraform Provider version

0.44.1

### Terraform version

1.3.9

**Comment by sergiught** [comment]
Hey @naebliss     👋🏻 

This is now improved in the latest release [v0.45.0](https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.45.0).  Please give it a go and let us know if you have any issues with it. Thanks!

Docs: https://registry.terraform.io/providers/auth0/auth0/0.45.0/docs
