### ISSUE TITLE
auth0_branding_theme fonts link_style enforces invalid style `underline` vs `underlined`

### ISSUE THREAD

**Issue by jeffxor** [auth0/terraform-provider-auth0#521]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I just upgraded to the latest version of this provider 44.1

I was getting a validation error when running `plan` from the provider that `underlined` was not a valid option and I needed to select `normal` or `underline`. 

I selected `underline` when I attempt to run `apply` this I get an error from Auth0 Saying `underline` is not a valid option.

### Expectation

I should be able to add underline to fonts link_style and allow this change to apply

### Reproduction

- Change fonts.link_style on `auth0_branding_theme` to be underlined
- Run plan, it will fail saying `underlined` is not valid
- Change this to the allowed value `underline`
- Run Apply this fails to apply with error `underline` is not valid

### Auth0 Terraform Provider version

0.44.1

### Terraform version

1.3.9

**Comment by sergiught** [comment]
Hey @jeffxor 👋🏻 

Thanks for bringing this to our attention! We'll patch this soon and cut a release with the fix, probably some time next week as we want to include some additional improvements as well.

**Comment by sergiught** [comment]
Hey @jeffxor      👋🏻 

This is now fixed in the latest release [v0.45.0](https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.45.0).  Please give it a go and let us know if you have any issues with it. Thanks!

Docs: https://registry.terraform.io/providers/auth0/auth0/0.45.0/docs
