### ISSUE TITLE
Ability to attach permissions to users as we can do on the UI

### ISSUE THREAD

**Issue by stephanerenou** [auth0/terraform-provider-auth0#528]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Using the Auth0 UI, I can currently attach some permissions to my users, the same way I can attach roles. Unfortunately this is not possible via the terraform provider as of today.

### Describe the ideal solution

Extend the ressource auth0_user to allow to add permissions, in which case permission may also need to have an ID.

### Alternatives and current workarounds

Currently either you need to go to the UI for each user, or to create a specific role with just the permissions required

**Comment by sergiught** [comment]
Hey @stephanerenou 👋🏻 

Thanks for raising this with us. Indeed at the moment the user resource lacks the ability to assign permissions to a user and it's something we want to add support for. 

To set some realistic expectations, this feature will have to wait at least until Q2 for us to have some time to tackle it, however contributions are more than welcomed. 

We'll keep you updated and leave the issue open until then.

**Comment by carnei-ro** [comment]
+1

**Comment by sergiught** [comment]
Hey folks this is now available in the latest release https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.47.0. 

Documentation: 

- https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/role_permission
- https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/role_permissions
- https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/user_role
- https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/user_roles
- https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/user_permission
- https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/user_permissions

Migration guide:

- https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md

Let us know if you encounter any issues with the new attachment resources! 

Appreciate everyones patience while we worked on adding the new features.
