### ISSUE TITLE
auth0_resource_server data source incorrectly returns identifier value in the id field

### ISSUE THREAD

**Issue by rishabhg20** [auth0/terraform-provider-auth0#530]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The `auth0_resource_server` [data source](https://registry.terraform.io/providers/auth0/auth0/latest/docs/data-sources/resource_server) returns the identifier value of the API in the `id` field.

### Expectation

The data source should return the ID in the `id` field as it says in the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs/data-sources/resource_server#id).

### Reproduction

```
data "auth0_resource_server" "custom-api" {
  identifier = "custom-api-name"
}

output "custom-api-id" {
  value = data.auth0_resource_server.custom-api.id
}
```

### Auth0 Terraform Provider version

0.44.1

### Terraform version

1.3.9

**Comment by sergiught** [comment]
Hey @rishabhg20 👋🏻 , thanks for raising this! I have a fix ready in https://github.com/auth0/terraform-provider-auth0/pull/532 and we'll aim at releasing this in the next version.

**Comment by rishabhg20** [comment]
@sergiught thank you! How often do you cut releases?

**Comment by rishabhg20** [comment]
@sergiught perfect! Do you want me to close this issue or you'd do that once you cut the release?

**Comment by sergiught** [comment]
Appreciate you offering that @rishabhg20 👍🏻 however we'll close this down only once you have the fix in your hands and can benefit from it 😃 (once the release happens). So no worries about it! Thanks tho!
