### ISSUE TITLE
SAML mapping whitespace issue with jsonencode

### ISSUE THREAD

**Issue by raigow** [auth0/terraform-provider-auth0#531]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using the auth0_connection module for a SAML resource, using the fields_map option seems to always result in changes detected. Running a plan shows that there are whitespace changes but nothing has changed

 # module.auth0.auth0_connection.### will be updated in-place
  ~ resource "auth0_connection" "###" {
        id                   = "###"
        name                 = "###"
        # (6 unchanged attributes hidden)

      ~ options {
          ~ fields_map                     = jsonencode( # whitespace changes
                {

### Expectation

No changes should be detected if the JSON file hasn't changed

### Reproduction

Defining fields_map from file
 fields_map          = file("${path.module}/../../../src/mappings/###.json")

With the ###.json file in JSON format. Example:

{
  "name": "firstname & lastname",
  "email": [
    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn",
    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
  ],
  "user_id": [
    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn",
    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
  ],
  "ad_groups": [
    "group",
    "http://schemas.xmlsoap.org/claims/Group"
  ],
  "given_name": [
    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname",
    "firstname"
  ],
  "family_name": [
    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname",
    "lastname"
  ]
}

### Auth0 Terraform Provider version

0.43.0

### Terraform version

1.3.3

**Comment by sergiught** [comment]
Hey @raigow 👋🏻 ,

If your file is of type JSON, you can return a minified version of it using a round-trip through jsondecode and jsonencode like so:

```terraform
    fields_map = jsonencode(jsondecode(file("fields_map.json")))
```

This will prevent any noisy changes detected like extra whitespace.

**Comment by raigow** [comment]
That worked, thanks @sergiught!
