### ISSUE TITLE
Add resource that can patch only auth0_resource_server scopes

### ISSUE THREAD

**Issue by rishabhg20** [auth0/terraform-provider-auth0#533]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Currently, the [auth0 management API](https://auth0.com/docs/api/management/v2#!/Resource_Servers/patch_resource_servers_by_id) supports patching resource servers but that functionality is not available via the auth0 terraform provider.

### Describe the ideal solution

The terraform provider allows importing resource servers as a data source. It should support modifying this existing resource server by providing an interface to call the [patch api](https://auth0.com/docs/api/management/v2#!/Resource_Servers/patch_resource_servers_by_id).

### Additional context

With new organizations onboarded on auth0, there is a need to add scopes to an existing api. Such operations aren't yet possible with the current auth0 terraform provider due to the lack of this feature.

**Comment by sergiught** [comment]
Hey @rishabhg20 👋🏻 Have you tried using the `auth0_resource_server` resource? https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/resource_server

**Comment by rishabhg20** [comment]
@sergiught thank you for sharing this. I am looking to work through a scenario where I have the resource server already created outside terraform. I just want to update the scopes attached to this resource via terraform. Correct me if I'm wrong but I don't think I can do this via the `auth0_resource_server` resource.

**Comment by sergiught** [comment]
Thanks for the further clarification @rishabhg20 👍🏻 I'll try to help out. 

You can reuse the `auth0_resource_server` resource to start managing the scopes, even if the resource server was created outside of terraform. To do so you can leverage the import functionality of terraform such that the resource knows what it needs to start managing and then apply any changes to the scopes field. 

Given the following terraform config:

```
resource "auth0_resource_server" "my_resource_server" {
 // your desired attributes
}
```

### Steps
1. Run `terraform import auth0_resource_server.my_resource_server XXXXXXXXXXXXXXXXXXXXXXX` where XXXX is the ID of your resource server.
2. Update the scopes property
3. Run `terraform plan` to have a preview of the changes
4. Run `terraform apply `if you're happy with the changes

> **Warning**
> If you start managing the resource server through terraform, ideally you don't manage it elsewhere as well, otherwise you'll constantly have to update your config to reflect any out of bound changes before applying.

**Comment by rishabhg20** [comment]
Hi @sergiught , this seems like a reasonable approach and I did think about this a bit before.

I will elaborate more on what I am trying to do. Basically, I want to onboard customers as organizations in Auth0. As part of that, I want to create specific roles (scopes) for that particular organization's users which I will add to my already existing api (resource server). I also want to have the ability to remove all these resources if the customer needs to be removed from Auth0 in the future. This is where terraform destroy would come into picture.

With importing the resource server into the terraform state, I face the danger of accidentally destroying the whole resource server (api) while removing one single customer from Auth0. Thus, I was looking for a mechanism to simply add scopes to a resource server without the need to manage the resource server via terraform. Do you think this is a generic enough use case or something very specific to me? I'd love to hear your opinion on this or if you have a recommendation on how to solve this with the existing provider, please let me know.

For now, I have unblocked myself by leveraging the null resource that terraform provides and am making direct curl calls to the auth0 management api.

**Comment by sergiught** [comment]
Hi @rishabhg20  👋🏻, having now the full context I think I'm understanding your problem. Please feel free to correct me in case any of the following will be inaccurate for your use case.

Ideally you'd want a terraform module that wraps up all the logic behind onboarding your customers and being able to surgically remove them when necessary from your infrastructure without risking any side effects on your main resource server definition, or potentially any other shared resources (hypothetical example perhaps connections?). 

To allow you to achieve that you'd want a way to just manage the scopes of a resource server but none of the other attributes, correct?

We did set somewhat of a precedent within this provider of resources that only manage these kind of associations, for example `auth0_organization_member`, `auth0_organization_connection`, `auth0_connection_client` and a few extra open issues that are requesting some more resource associations (#16 , #154). 

As we're planning to tackle those 2 open issues, this is something we could include as well in something like:

```terraform
// Resource to manage associations between a resource server and a scope, this would be a 1 to 1 association.
auth0_resource_server_scope customer_A_scope {
  resource_server_id = "someID"
  scope = {
    value = "some name"
    description = "some description"
  }
}

// Destroying the above would only remove the scope from the resource server.
``` 

Would this work for your use case?

**Comment by rishabhg20** [comment]
Yes, this is exactly what I think will solve this use case.

**Comment by sergiught** [comment]
Awesome, thanks for confirming @rishabhg20 🥳 

I can't give you an exact estimate on when we'll be able to have this feature within the provider, but I'll keep you updated  whenever I have new information.

**Comment by rishabhg20** [comment]
Sounds good. As I mentioned before, I am not blocked on this feature as of now but I think it will be a good addition for everybody. All the best!
