### ISSUE TITLE
auth0_prompt_custom_text do not find organization-selection screen for organizations prompt

### ISSUE THREAD

**Issue by sileonrickard** [auth0/terraform-provider-auth0#539]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The custom text for the organizations prompt does not work with the organization-selection screen. I produces a 400 error. I have tested with version 0.40.0 and 0.44.1

```
│ Error: 400 Bad Request: Invalid screen "organization-selection".
│
│   with module.auth0_resources.auth0_prompt_custom_text.example_theme,
│   on ../../../modules/auth0/branding.tf line 90, in resource "auth0_prompt_custom_text" "example_theme":
│   90: resource "auth0_prompt_custom_text" "example_theme" {
│
╵
Operation failed: failed running terraform apply (exit 1)
NativeCommandExitException: Program "terraform.exe" ended with non-zero exit code: 1.
```

### Expectation

It should have updated the description and invalid-organization text. It should not produce an error

### Reproduction

```
resource "auth0_prompt_custom_text" "example_theme" {
  prompt   = "organizations"
  language = "en"
  body = jsonencode(
    {
      "organization-selection" : {
        "description" : "Kindly enter the organization name as stated in the email for proper identification.",
        "invalid-organization": "The organization name you entered is invalid. Please refer to the invitation email for the correct organization name"
      }
    }
  )
}
``` 

### Auth0 Terraform Provider version

0.44.1

### Terraform version

1.3.9

**Comment by sergiught** [comment]
Thanks for checking @sileonrickard.

What happens if you go to the Custom Text Tab and try to find the prompt in there and save it manually? 

![image](https://user-images.githubusercontent.com/28300158/225929337-fa599b84-cd43-460f-a780-5cdc5c018a79.png)

**Comment by sileonrickard** [comment]
taht works fine and I have also tried via the management API from postman which work fine too

**Comment by sergiught** [comment]
@sileonrickard Would you mind running a terraform plan with debug enabled and come back to us with the output? 🙏🏻 Please double check that any sensitive content is obfsucated. 

Ensure your provider has the debug property set to true:

```terraform
provider "auth0" {
  debug = true
}
```

and run terraform plan with TF_LOG=DEBUG, example:


```
TF_LOG=DEBUG terraform plan
```

**Comment by sileonrickard** [comment]
I se now that we do it diffrentlly the plan command works for me too, but get the problem when I run the apply command

```
terraform apply
```

But when I run the exakt same project today the module works fine. So maybe the bug was not in this module
