### ISSUE TITLE
Missing option in Breached Password Detection

### ISSUE THREAD

**Issue by ifyouseewendy** [auth0/terraform-provider-auth0#544]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hey team, I believe there is no option for enabling "Send notifications to users with compromised credentials" in Breached Password Detection. 

### Describe the ideal solution

Could anyone help enable it please? Thank you!

**Comment by sergiught** [comment]
Hey @ifyouseewendy 👋🏻 

Apologies for the delay in getting back to you on this one. To enable the "Send notifications to users with compromised credentials" you simply need to set the shields property on the `breached_password_detection` to `user_notification`. 

Example:

```terraform
resource "auth0_attack_protection" "my_protection" {
	breached_password_detection {
		enabled = true
		shields = ["user_notification"]
		admin_notification_frequency = ["daily", "monthly"]
		method = "standard"

		pre_user_registration {
			shields = ["block"]
		}
	}
}
```

We'll keep this issue open however to improve our docs and explain better what those properties do.

**Comment by ifyouseewendy** [comment]
Ah, got it. Thanks!
