### ISSUE TITLE
Client - Connection relation not detected by terraform when added manually

### ISSUE THREAD

**Issue by mkrasuskipgs** [auth0/terraform-provider-auth0#546]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When a client - connection relation is added in Auth0 management portal but not in the terraform, it is not detected as existing resource and marked for deletion (as with other providers, like azurerm)

### Expectation

When client - connection relation is added manually and then terraform script is run, it should be detected as a resource existing in auth0 but not in terraform and marked for deletion.

### Reproduction

1. Create auth0 client via terraform
2. Create 2 auth0 connections (A, B) via terraform
3. Assign connection A to the client
4. Login to Auth0 management portal
5. Manually add connection B to the client
6. Run terraform
7. No changes are detected

### Auth0 Terraform Provider version

0.45

### Terraform version

1.3.4

**Comment by raigow** [comment]
I also have this same issue. It would be good to be able to enforce those connections

**Comment by sergiught** [comment]
Hey @mkrasuskipgs and @raigow would you mind taking a look at https://github.com/auth0/terraform-provider-auth0/issues/549#issuecomment-1517790157 as this issue is similar to that one in certain ways. Would be useful to provide your feedback so we can come up with a good solution for everyone 🙏🏻 .

**Comment by sergiught** [comment]
Hey folks this is now available in the latest release https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.47.0. 

Documentation: 

- https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection_clients

This new resource is able to manage the entire list of enabled clients on a connection and report changes. 

Let us know if you encounter any issues with the new attachment resources! 

Appreciate everyones patience while we worked on adding the new feature.
