### ISSUE TITLE
data.auth0_resource_server cannot read scopes for Auth0 management API

### ISSUE THREAD

**Issue by sergei-ivanov** [auth0/terraform-provider-auth0#547]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

It's not possible to read the list of scopes for Auth0 Management API using `auth0_resource_server` data source.

It looks like `auth0_resource_server` data source reuses the read logic from the sibling `auth0_resource_server` resource, which explicitly skips reading scopes for Auth0 Management API:
https://github.com/auth0/terraform-provider-auth0/blob/1f91edb2adce721a60d45217c46c7e002ba03050/internal/auth0/resourceserver/resource.go#L191-L200

### Expectation

It should be possible to retrieve the list of scopes for Auth0 Management API.

### Reproduction

I was trying to create a machine-to-machine client with access to Auth0 Management API. I was hoping to retrieve the list of scopes from the data source as below, but it looks like for the time being I'll have to list them explicitly and manually.

```hcl
data "auth0_resource_server" "auth0_management_api" {
  identifier = "https://${var.auth0_domain}/api/v2/"
}

resource "auth0_client" "m2m" {
  app_type                   = "non_interactive"
  # ...
}

resource "auth0_client_grant" "m2m_auth0_management_api" {
  client_id = auth0_client.m2m.id
  audience  = data.auth0_resource_server.auth0_management_api.identifier
  scope     = data.auth0_resource_server.auth0_management_api.scopes[*].value
}
```

When I output the value of `data.auth0_resource_server.auth0_management_api`, I can see that scopes is an empty set.

### Auth0 Terraform Provider version

0.45.0

### Terraform version

1.3.7

**Comment by sergiught** [comment]
Hey @sergei-ivanov thanks for reporting this! I have a fix in https://github.com/auth0/terraform-provider-auth0/pull/555. I'll circle back here when we're able to get that merged and released.

**Comment by sergiught** [comment]
Thanks again @sergei-ivanov for raising this. It is now available within the latest https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.46.0. Please let us know if you have any issues with it.
