### ISSUE TITLE
Importing resource auth0_trigger_binding does not set trigger attribute

### ISSUE THREAD

**Issue by sergei-ivanov** [auth0/terraform-provider-auth0#548]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When importing an existing flow into terraform state, `trigger` attribute is not set on `auth0_trigger_binding`. As a result, the next `terraform apply` operation detects drift and attempts to replace the resource because the `trigger` attribute is marked as `ForceNew`.

### Expectation

The `trigger` attribute is imported into the state and there is no drift.

### Reproduction

Given a resource definition that matches the existing resource:

```hcl
resource "auth0_trigger_binding" "login_flow" {
  trigger = "post-login"

  actions {
    # ...
  }
}
```

When the following commands are run:

```shell
terraform import auth0_trigger_binding.login_flow post-login
terraform plan
```

Then the following plan output is generated:

```
  # auth0_trigger_binding.login_flow must be replaced
-/+ resource "auth0_trigger_binding" "login_flow" {
      ~ id      = "post-login" -> (known after apply)
      + trigger = "post-login" # forces replacement

        # (1 unchanged block hidden)
    }
```

### Auth0 Terraform Provider version

0.45.0

### Terraform version

1.3.7

**Comment by sergiught** [comment]
Hey @sergei-ivanov thanks for reporting this! I have a fix in #554. I'll circle back here when we're able to get that merged and released.
