### ISSUE TITLE
Payload validation error: 'Additional properties not allowed: options'

### ISSUE THREAD

**Issue by caleyg** [auth0/terraform-provider-auth0#550]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using the resourcesaver provider in the terraform-provider-auth0 module, I get the following error: 

```
 [2023-04-06T19:19:49.479Z] module.auth0_resource_server.auth0_resource_server.resource_server: Creating...
 [2023-04-06T19:19:50.384Z] ╷
 [2023-04-06T19:19:50.384Z] │ Error: 400 Bad Request: Payload validation error: 'Additional properties not allowed: options'.
 [2023-04-06T19:19:50.384Z] │ 
 [2023-04-06T19:19:50.384Z] │   with module.auth0_resource_server.auth0_resource_server.resource_server,
 [2023-04-06T19:19:50.384Z] │   on ../../../../../../providers/auth0/modules/resource_server/resource_server.tf line 3, in resource "auth0_resource_server" "resource_server":
 [2023-04-06T19:19:50.384Z] │    3: resource "auth0_resource_server" "resource_server" {
 [2023-04-06T19:19:50.384Z] │ 
 [2023-04-06T19:19:50.384Z] ╵
```

It also appears here at terraform https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/resource_server#options which I think is a mistake based on the behavior of the API on the docs site.

### Expectation

I would expect the API docs to reflect the API's actual behavior when using the upstream providers.

### Reproduction

1. When testing this in the API documentation here https://auth0.com/docs/api/management/v2#!/Resource_Servers/post_resource_servers 
2. Given with the following body (token required):
```
{
   "name": "caley-test",
   "identifier": "caley-test",
   "options": {}
 }
```
3. Then I get the following response:
```
 {
   "statusCode": 400,
   "error": "Bad Request",
   "message": "Payload validation error: 'Additional properties not allowed: options'.",
   "errorCode": "invalid_body"
 }
```

### Auth0 Terraform Provider version

0.45.0

### Terraform version

1.3.5

references PR #551

**Comment by sergiught** [comment]
Thanks again @caleyg for raising this. It is now available within the latest https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.46.0. Please let us know if you have any issues with it.

**Comment by caleyg** [comment]
> Thanks again @caleyg for raising this. It is now available within the latest https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.46.0. Please let us know if you have any issues with it.

absolutely! I'll let my cohorts know ciaoo
