### ISSUE TITLE
Importing a connection that has non-string values in its configuration fails

### ISSUE THREAD

**Issue by WesleyKlop** [auth0/terraform-provider-auth0#553]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am trying to describe our existing auth0 configuration in Terraform (well Pulumi but that uses this provider when looking under the hood).

When trying to import an existing Connection, I am running into the problem that the `connection.options.configuration` field [only accepts a map of strings](https://github.com/auth0/terraform-provider-auth0/blob/a5b676317b3143d8923d272343a4e756bd1e5f8c/internal/auth0/connection/schema.go#L246) instead of any value like the API does. We know the API accepts mixed values, but the Terraform resource does not. 

Is this something that is trivial to fix? Can I help?

This might be _slightly_ related to #251 and #252 

Side note: it looks like the Auth0 Community link in the PR template is not working :) 

### Expectation

When importing a Connection resource that has `options.configuration` with value types other than string I expect it to not throw an error.

### Reproduction

1. Given an existing (Database) connection that has a configuration key value pair of type boolean for example
2. When importing this resource.
3. Then the import fails

### Auth0 Terraform Provider version

v0.45.0 (@pulumi/auth0 2.18.0)

### Terraform version

n/a

**Comment by sergiught** [comment]
Hey @WesleyKlop 👋🏻 thanks for reporting this. Unfortunately to fix this within the provider we'd actually need to patch the underlying Go SDK that we use, as that's the one that dictates the type we're sending to the API in:

https://github.com/auth0/go-auth0/blob/main/management/connection.go#L305-L306

I'll sync with @ewanharris on working on a solution for this and keep you updated!

**Comment by WesleyKlop** [comment]
Hey @sergiught thanks! For now I worked around it by changing the types to strings and updating our connection code to match that.

In one of our scripts we use a boolean value to trigger some behaviour depending on which tenant we are using. So that would be something like 

```tf
resource "auth0_connection" "my_connection" {
  // -- snip --

  options {
    // -- snip --
    custom_scripts = {
      get_user = <<EOF
        function getByEmail(email, callback) {
          console.log(configuration.my_special_behavior)
          return callback(new Error("Whoops!"));
        }
      EOF
    }
    configuration = {
      my_special_behavior = true
    }
  }
}
```

**Comment by sergiught** [comment]
Hey @WesleyKlop 👋🏻,

Apologies for the delay on getting back to you on this issue. Considering that while creating a connection (POST endpoint), non string values are ignored by the API and the UI Dashboard only accepts strings as values, we won't be going forward in supporting this on the provider. Only the PATCH endpoint accepts non string values within the configuration block, however this is uninteded and it might get deprecated in the future. I would suggest moving away from custom scripts that leverage non string data within this property, you could consider moving them to a more secure place like hashicorp vault and fetch them from there and using feature flags within your application code for special behaviours.
