### ISSUE TITLE
SAML auth0_connection properties set by metadata_xml cause incorrect diffs

### ISSUE THREAD

**Issue by max-dekock** [auth0/terraform-provider-auth0#559]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have an Auth0 SAML connection resource that looks like this:

```
resource "auth0_connection" "example_connection" {
  name     = "Example"
  strategy = "samlp"
  options {
    metadata_xml        = data.local_file.example_metadata.content
    domain_aliases      = ["example.com"]
  }
}
```

This creates the connection just fine. But if I make an unrelated change and run `terraform plan`, I see this:

```
Terraform will perform the following actions:

  # auth0_connection.ad_gallery_test_connection will be updated in-place
  ~ resource "auth0_connection" "example_connection" {
        id                   = "con_xxxxxxxxxxxxxxxxxxx"
        name                 = "Example"
        # (6 unchanged attributes hidden)

      ~ options {
          - sign_in_endpoint               = "https://[...]" -> null
          - sign_out_endpoint              = "https://[...]" -> null
          - signing_cert                   = "[...]" -> null
            # (28 unchanged attributes hidden)
        }
    }

 [...]
```

It looks like the Auth0 provider doesn't realize that the `sign_in_endpoint`, `sign_out_endpoint`, and `signing_cert` arguments are computed from the `metadata_xml` argument. I think this issue is essentially the same as #387. 

### Expectation

I would expect the provider to realize that these properties are computed from the `metadata_xml` file, and not try to change them to `null` when nothing in that file has changed.

### Reproduction

A TF block like the one above should be sufficient provided that the `metadata_xml` argument contains a valid SAML metadata XML document.

First run `apply` to create the object, then run `plan` to see the diff.

### Auth0 Terraform Provider version

0.45.0

### Terraform version

1.3.3

**Comment by sergiught** [comment]
Thanks again @max-dekock for raising this. It is now available within the latest https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.46.0. Please let us know if you have any issues with it.
