### ISSUE TITLE
Tenant flag : mfa_show_factor_list_on_enrollment missing

### ISSUE THREAD

**Issue by r1m** [auth0/terraform-provider-auth0#560]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

`mfa_show_factor_list_on_enrollment` is missing from the `auth0_tenant` flags schema.

The flag was added in https://github.com/auth0/go-auth0/pull/187 but not yet ported into the terraform provider

### Describe the ideal solution

New version with the flag added :)

**Comment by sergiught** [comment]
Hey @r1m 👋🏻 I have this ready within https://github.com/auth0/terraform-provider-auth0/pull/561. I'll keep you updated for when we release it.

**Comment by sergiught** [comment]
Thanks again @r1m  for raising this. It is now available within the latest https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.46.0. Please let us know if you have any issues with it.
