### ISSUE TITLE
Unable to set up universal_login even with a custom_domain configured

### ISSUE THREAD

**Issue by la-kurt** [auth0/terraform-provider-auth0#577]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm trying to set up a custom login page for my application, but whenever I `terraform plan`, I keep getting the error `managing the universal login body through the 'auth0_branding' resource requires at least one custom domain to be configured for the tenant.
│ 
│ Use the 'auth0_custom_domain' resource to set one up.` I already have an `auth0_custom_domain` block and placed it under `auth0_branding`'s `depends_on`.

### Expectation

I expect for terraform plan to succeed without any errors.

### Reproduction

1. Terrraform config
```terraform
resource "auth0_custom_domain" "this" {
  domain     = "example.domain.com"
  type       = "auth0_managed_certs"
  tls_policy = "recommended"
}

resource "auth0_branding" "this" {
  logo_url = var.logo_url

  universal_login {
    body = file("some_file.html")
  }

  depends_on = [auth0_custom_domain.this]
}
```
2. `$ terraform plan`
3. Plan output:
```
Terraform planned the following actions, but then encountered a problem:

  # module.auth0_branding.auth0_custom_domain.this will be created
  + resource "auth0_custom_domain" "this" {
      + domain             = "example.domain.com"
      + id                 = (known after apply)
      + origin_domain_name = (known after apply)
      + primary            = (known after apply)
      + status             = (known after apply)
      + tls_policy         = "recommended"
      + type               = "auth0_managed_certs"
      + verification       = (known after apply)
    }

╷
│ Error: managing the universal login body through the 'auth0_branding' resource requires at least one custom domain to be configured for the tenant.
│ 
│ Use the 'auth0_custom_domain' resource to set one up.
│ 
│   with module.auth0_branding.auth0_branding.this,
│   on ../../shared/la_auth0_branding/main.tf line 16, in resource "auth0_branding" "this":
│   16: resource "auth0_branding" "this" {
│ 
```

### Auth0 Terraform Provider version

0.46.0

### Terraform version

1.4.6

**Comment by sergiught** [comment]
Hey @la-kurt 👋🏻 

Thanks for opening an issue with us. The terraform plan fails because the custom domain is not yet created for the branding resource. In order to modify the `universal_login.body` property a custom domain needs to exist before hand.

What you can do is:
1. Have a config just with the custom domain
2. Apply the config through `terraform apply`
3. Add the branding settings through the `auth0_branding` resource
4. `terraform plan` should execute correctly
5. You can apply your changes through `terraform apply`
