### ISSUE TITLE
connection property set_user_root_attributes 'on_each_login' doesn't reflect in tenant

### ISSUE THREAD

**Issue by PrestonR** [auth0/terraform-provider-auth0#587]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When I set `set_user_root_attributes` to `on_each_login` I do not see the setting toggled in the Auth0 connection.

### Expectation

I would expect to see the setting toggled in the tenant.

### Reproduction

1. Given the following resource block (filling in the appropriate variables and references as necessary):

```
resource "auth0_connection" "azure_ad" {
  name           = substr(replace(replace(var.display_name, " ", ""), "_", "-"), 0, min(length(var.display_name), 128))
  display_name   = ""
  strategy       = "waad"
  show_as_button = true

  options {
    identity_api             = "microsoft-identity-platform-v2.0"
    client_id                = azuread_application.app.application_id
    client_secret            = azuread_application_password.app_pw.value
    tenant_domain            = var.aad_domain
    domain                   = var.aad_domain
    use_wsfed                = false
    waad_protocol            = "openid-connect"
    waad_common_endpoint     = false
    max_groups_to_retrieve   = 250
    api_enable_users         = true
    set_user_root_attributes = "on_each_login"
    non_persistent_attrs     = ["ethnicity", "gender"]

    should_trust_email_verified_connection = "always_set_emails_as_verified"

    domain_aliases = [
      "example.com",
      "example2.com",
    ]

    scopes = [
      "basic_profile",
      "ext_groups",
      "ext_profile",
    ]

    upstream_params = jsonencode({
      "screen_name" : {
        "alias" : "login_hint"
      }
    })
  }
}
```

2. When I deploy the resource block, all settings should look as defined for the connection.
3. Then I check the connection in the Auth0 portal, "Sync user profile attributes at each login" is untoggled

### Auth0 Terraform Provider version

0.47.0

### Terraform version

1.45

### Additional notes
For what it's worth, I also tried not specifying the property so that it would set the default to `on_each_login` but it looks like it just sets the value to an empty string.

**Comment by sergiught** [comment]
Hey folks, we just released https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.48.0 with a fix for this. Please check it out and let us know if you encounter any issues!

**Comment by spawluk-zartis** [comment]
Hey. After that fix, Microsoft AD tenant works ok, but Google Workspace tenant switches `set_user_root_attributes` off on UI, even if `set_user_root_attributes = "on_each_login"` is set

**Comment by sergiught** [comment]
Hey @spawluk-zartis 👋🏻 , thanks for raising that with issue. Just so I'm understanding correctly, before the fix for Microsoft AD Connections you were able to manage the `set_user_root_attributes` property and after you're not any longer?

**Comment by spawluk-zartis** [comment]
@sergiught yes. This is the behavior I observed after opdating from 0.47.0 to 0.48.0

**Comment by sergiught** [comment]
Alright we'll look into it 👍🏻

**Comment by sergiught** [comment]
Hey folks, we fixed this across various other enterprise connections in https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.49.0. Try it out and let us know if you encounter any other issues.
