### ISSUE TITLE
Missing documentation : `auth0_client` `addons.samlp` missing `signing_key` 

### ISSUE THREAD

**Issue by BalaGanaparthi** [auth0/terraform-provider-auth0#606]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The resource [auth0_client](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/client#nested-schema-for-addonssamlp) is missing the attribute `signing_key` for attribute `addons.samlp` in the documentation, but the `Example Usage` sections shows the attribute.

### Expectation

NA

### Reproduction

NA

### Auth0 Terraform Provider version

0.48.0

### Terraform version

1.4.6

**Comment by sergiught** [comment]
Hey @BalaGanaparthi 👋🏻 

Thanks for reporting this, the presence of the `signing_key` within the `addons.samlp` of the `auth0_client` resource was removed from the example as it was mistakenly added there. The docs on the registry will get updated accordingly on our next release.
