### ISSUE TITLE
Provider not detecting removal of blocks from resources

### ISSUE THREAD

**Issue by BalaGanaparthi** [auth0/terraform-provider-auth0#616]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using resources like `auth0_attack_protection` and `auth0_client` that contain blocks like `auth0_attack_protection. suspicious_ip_throttling` or `auth0_client. addons` 

Once the resources are configured in tenant using the blocks by executing `terraform apply` and later remove the blocks from the resource and re-execute `terraform apply` the changes (removal of blocks) are not being detected. 

### Expectation

The blocks removal are detected and a change operation is executed during apply

### Reproduction

1. Initial state of the of tenant (disabled initally)
<img width="1508" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/22507821/18680d98-22ff-49c1-94be-7fb6ed51ca27">

2. Initial resource with the three blocks (`suspicious_ip_throttling`, `brute_force_protection`, and `breached_password_detection`)

```hcl
resource "auth0_attack_protection" "my_protection" {
  suspicious_ip_throttling {
    enabled   = true
    shields   = ["admin_notification", "block"]
    allowlist = ["192.168.1.1"]

    pre_login {
      max_attempts = 100
      rate         = 864000
    }

    pre_user_registration {
      max_attempts = 50
      rate         = 1200
    }
  }

  brute_force_protection {
    allowlist    = ["127.0.0.1"]
    enabled      = true
    max_attempts = 5
    mode         = "count_per_identifier_and_ip"
    shields      = ["block", "user_notification"]
  }

  breached_password_detection {
    admin_notification_frequency = ["daily"]
    enabled                      = true
    method                       = "standard"
    shields                      = ["admin_notification", "block"]

    pre_user_registration {
      shields = ["block"]
    }
  }
}
```

3. execute `terraform apply`
4. Resultant status in the tenant
<img width="1511" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/22507821/440dd099-5d68-4240-ac9a-8e81b992e1b1">

5. change resource to by removing `suspicious_ip_throttling` block

```hcl
resource "auth0_attack_protection" "my_protection" {
 
  brute_force_protection {
    allowlist    = ["127.0.0.1"]
    enabled      = true
    max_attempts = 5
    mode         = "count_per_identifier_and_ip"
    shields      = ["block", "user_notification"]
  }

  breached_password_detection {
    admin_notification_frequency = ["daily"]
    enabled                      = true
    method                       = "standard"
    shields                      = ["admin_notification", "block"]

    pre_user_registration {
      shields = ["block"]
    }
  }
}
```

6. execute `terraform apply`
7. Execution outputs 
*Apply complete! Resources: 0 added, 0 changed, 0 destroyed.*
8. Tenant do not reflect the change
9. Similarly the issue can also be reproducible with `auth0_client` resource by add/remove `addons` block and this may be the case for other resource as well

### Auth0 Terraform Provider version

provider registry.terraform.io/auth0/auth0 v0.48.0

### Terraform version

Terraform v1.4.6 on linux_amd64

**Comment by sergiught** [comment]
Hey @BalaGanaparthi 👋🏻 

Thanks for taking the time to raise this with us. The fact that the removal of the blocks for the attack protection resource does nothing is **intended**. The reason behind this is not to force someone to set up and configure all 3 attack protection resources if they only want to manage one of them. 

To specifically toggle either one of them off please use the enabled property within the blocks and set it to false. 

However, if there's enough demand to change the behavior of blocks we can start considering it. Would you expect that not having the block disables those Auth0 attack protection resources?
