### ISSUE TITLE
Document how to use is_token_endpoint_ip_header_trusted

### ISSUE THREAD

**Issue by redbmk** [auth0/terraform-provider-auth0#620]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After upgrading to v0.48.0 using the [Migration Guide](https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md), things seemed to work until I tried to create a new client. I now get this error:

```
Error: 400 Bad Request: The flag is_token_endpoint_ip_header_trusted can only be set true on clients that require authentication (i.e. token_endpoint_auth_method is set to 'client_secret_post' or 'client_secret_basic')
```

Here's a minimal example:

```terraform
resource "auth0_client" "my_client" {
  name = "Test IP Header Trusted"

  is_token_endpoint_ip_header_trusted = true
  # token_endpoint_auth_method = "client_secret_post"
}

resource "auth0_client_credentials" "my_client-credentials" {
  client_id = auth0_client.my_client.id

  authentication_method = "client_secret_post"
}
```

If I use the old method with `token_endpoint_auth_method = "client_secret_post"`, then it lets me create, but I get a warning from the terraform provider:

```
╷
│ Warning: Argument is deprecated
│
│   with auth0_client.my_client,
│   on temp.tf line 5, in resource "auth0_client" "my_client":
│    5:   token_endpoint_auth_method          = "client_secret_post"
│
│ Managing the authentication method through this attribute is deprecated and it will be changed to read-only in a future version. Migrate to the `auth0_client_credentials` resource to manage a client's authentication method instead.
│ Check the [MIGRATION GUIDE](https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md) on how to do that.
│
│ (and one more similar warning elsewhere)
```

### Expectation

I expected to be able to create a new auth0 tenant using the recommended settings after following the migration guide for the latest version.

I also expected [the documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/client) to show a complete, working example that doesn't produce errors or warnings.

### Reproduction

**Given** the following terraform config:

```terraform
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "0.48.0"
    }
  }
}

resource "auth0_client" "my_client" {
  name = "Test IP Header Trusted"

  is_token_endpoint_ip_header_trusted = true
}

resource "auth0_client_credentials" "my_client-credentials" {
  client_id = auth0_client.my_client.id

  authentication_method = "client_secret_post"
}
```

**When** I run `terraform apply`

**Then** I get the following error:

```
auth0_client.my_client: Creating...
╷
│ Error: 400 Bad Request: The flag is_token_endpoint_ip_header_trusted can only be set true on clients that require authentication (i.e. token_endpoint_auth_method is set to 'client_secret_post' or 'client_secret_basic')
│
│   with auth0_client.my_client,
│   on temp.tf line 1, in resource "auth0_client" "my_client":
│    1: resource "auth0_client" "my_client" {
│
╵
```

------------

**Given** the following terraform config:

```terraform
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "0.48.0"
    }
  }
}

resource "auth0_client" "my_client" {
  name = "Test IP Header Trusted"

  is_token_endpoint_ip_header_trusted = true
  token_endpoint_auth_method          = "client_secret_post"

}
```

**When** I run `terraform plan` or `terraform apply`

**Then** I get the following warning:

```
Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: Argument is deprecated
│
│   with auth0_client.my_client,
│   on temp.tf line 5, in resource "auth0_client" "my_client":
│    5:   token_endpoint_auth_method          = "client_secret_post"
│
│ Managing the authentication method through this attribute is deprecated and it will be changed to read-only in a future version. Migrate to the `auth0_client_credentials` resource to manage a client's authentication method instead.
│ Check the [MIGRATION GUIDE](https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md) on how to do that.
│
│ (and one more similar warning elsewhere)
╵
```

### Auth0 Terraform Provider version

0.48.0

### Terraform version

1.4.6

**Comment by sergiught** [comment]
Hey @redbmk 👋🏻 we've fixed this within the latest release https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.50.0. Give it a try and let us know if you encounter any issues with it. Closing this now.

**Comment by redbmk** [comment]
@sergiught sorry for the delay. I just tested this out, and this doesn't feel quite right.

When creating a new client, I need to run `terraform apply` twice in a row in order for everything to take effect. I'm relatively new to terraform, but I would expect running the command a single time would be enough to get everything to work.

Instead of requiring `terraform apply && terraform apply`, would there be any way to have it internally do a couple passes? i.e. calling it once would somehow do:

- create `auth0_client` with `is_token_endpoint_ip_header_trusted = false`
- create `auth0_client_credentials`
- update `auth0_client` with `is_token_endpoitn_ip_header_trusted = true`

**Comment by sergiught** [comment]
Hey @redbmk 👋🏻 

Thanks for following up on this. The issue is with the fact that the token auth method was moved to the `client_credentials` resource, and the `is_token_endpoint_ip_header_trusted` property can only be updated after having set that value, thus the 2 applies needed because they're in 2 separate resources.

For us to be able to improve the experience we'd need to move that field over to the `client_credentials` resource instead. I'll sync internally with my team and discuss this path. I'll post an update once we have some info.

**Comment by sergiught** [comment]
Hey @redbmk 👋🏻 

I followed up with an improvement for this within https://github.com/auth0/terraform-provider-auth0/pull/796. After it gets merged and released, you'll not need to run 2 terraform applies any more. When the client gets created and that field is set, we will default the auth method to `client_secret_post`, as that field requires `client_secret_post` or `client_secret_basic`. To change to `client_secret_basic` you can use the `auth0_client_credentials` resource.

I'll circle back once this is released. Thanks again for the feedback and for the patience for us to improve this!

**Comment by sergiught** [comment]
Hey @redbmk 👋🏻 the DX improvement is now available within https://registry.terraform.io/providers/auth0/auth0/1.0.0-beta.3. Please give it a go and let us know if you encounter any issues!

**Comment by richarddbarnett** [comment]
@sergiught:

> When the client gets created and that field is set, we will default the auth method to `client_secret_post`, as that field requires `client_secret_post` or `client_secret_basic`. To change to `client_secret_basic` you can use the `auth0_client_credentials` resource.

I'm trying to set `is_token_endpoint_ip_header_trusted` for an existing client which was created without specifying an authentication method. 

The client behaves as if it's using `client_secret_post` (ie when requesting a token) but GET `/api/v2/clients/:id` does not return a value for `token_endpoint_auth_method` and Terraform apply fails with

```
Error: 400 Bad Request: The flag is_token_endpoint_ip_header_trusted can only be set true on clients that require authentication (i.e. token_endpoint_auth_method is set to 'client_secret_post' or 'client_secret_basic')
```

Can I do this without 2 Terraform applys?

Terraform Auth0 provider `auth0/auth0` v1.43.0, Terraform 1.12.2.
