### ISSUE TITLE
Customize Login Page 

### ISSUE THREAD

**Issue by BalaGanaparthi** [auth0/terraform-provider-auth0#624]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The `auth0_tenant` provides functionality to manage `Password Reset` using `change_password` block and `Multi-Factor Authentication` using `guardian_mfa_page` block. There is no option for managing `Customize Login Page` 

<img width="1542" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/22507821/79afb01b-eb99-41c5-b830-b02875f01822">
``

### Describe the ideal solution

Similar to the `change_password` and `guardian_mfa_page` have a block for `login_page`

```hcl
 login_page {
    enabled = true
    html    = "<html>Login</html>"
  }
```

### Alternatives and current workarounds

NA

**Comment by sergiught** [comment]
Hey @BalaGanaparthi 👋🏻 

Thanks for taking the time to raise this with us. The "Customize Login Page" functionality is already available through the `auth0_global_client` resource. Docs: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/global_client

However I agree that this is not easily discoverable and the fact that the other pages are under the tenant resource makes it even more confusing. 

What do you think about having a separate `auth0_pages` resource where we could offer the option to manage all types of pages e.g.

```terraform
resource "auth0_pages" "my_pages" {
  login_page {
    enabled = true
    html    = "<html>Login</html>"
  }

  change_password_page {
    enabled = true
    html    = "<html>Change Password</html>"
  }

  guardian_mfa_page {
    enabled = true
    html    = "<html>MFA</html>"
  }

  error_page {
    html          = "<html>Error Page</html>"
    show_log_link = true
    url           = "https://example.com/errors"
  }
}

```

**Comment by sergiught** [comment]
Hey @BalaGanaparthi we went ahead and worked on improving the discoverability of managing a custom login page through a newly introduced auth0_pages resource in https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.50.0. Give it a try and let us know if you encounter any issues! Closing this now.

Docs: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/pages

**Comment by Nargonath** [comment]
I'm migrating from `auth0_global_client` to `auth0_pages` for the custom login page following the migration documentation. When checking the plan from Terraform, it will drop the `auth0_global_client` resource and create a `auth0_pages` resource. Is there a way to import the global client configuration into the `auth0_pages` resource without having to drop/recreate?

**Comment by sergiught** [comment]
Hey @Nargonath 👋🏻 

That's correct, we have a few resources within the provider that aren't identifiable by an ID within the API, but we're bound to require an ID when importing a terraform resource, so for these importing with any string works. 

We aim to be transparent in this within the docs: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/pages#import. Let us know however if you feel there's anything we can do better to improve that part. 

It's also safe to proceed with deleting the `auth0_global_client` if you migrated everything to the `auth0_pages` resource. The deletion logic for the global client doesn't do anything, we're just required to implement it. 

Let us know if you encounter any issues with the migration 🙏🏻
