### ISSUE TITLE
Managing scopes with auth0_resource_server_scopes

### ISSUE THREAD

**Issue by james-emerton** [auth0/terraform-provider-auth0#687]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I recently migrated from defining scopes on the `auth0_resource_server` resource to using the new top level `auth0_resource_server_scopes` resource. Both of these resources are defined in the same terraform configuration.

When applying the configuration, the scopes will be deleted if they exist (because they are *not* defined on `auth0_resource_server`) or created if they do not (because they *are* defined on `auth0_resource_server_scopes`.

### Expectation

The documentation for `auth0_resource_server` indicates that `scopes` are deprecated, and Terraform will emit warnings about using them. Either the warnings need to be removed if it is expected that `auth0_resource_server` will manage scopes, or the `auth0_resource_server` should not attempt to manage scopes in this way.

### Reproduction

```
resource "auth0_resource_server" "this" {
  name = "My API"
  identifier = "https://api.example.com"

  enforce_policies = false
  token_dialect = "access_token"
}

resource "auth0_resource_server_scopes" "this" {
  resource_server_identifier = auth0_resource_server.this.identifier

  scopes {
    name = "read"
    description = "Read values"
  }

  scopes {
    name = "update"
    description = "Update data"
  }
}

```

### Auth0 Terraform Provider version

0.49.0

### Terraform version

1.4.6

**Comment by sergiught** [comment]
Hey @james-emerton 👋🏻 

It seems like you're missing a `lifecycle` `ignore_changes` block for the scopes attribute on the `auth0_resource_server`.

From the migration guide: https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#resource-server-scopes, it is important to have this block within the config until we remove the deprecation. 

So your config should be rewritten to: 

```
resource "auth0_resource_server" "this" {
  name = "My API"
  identifier = "https://api.example.com"

  enforce_policies = false
  token_dialect = "access_token"

  # Until we remove the ability to operate changes on
  # the scopes field it is important to have this
  # block in the config, to avoid diffing issues.
  lifecycle {
    ignore_changes = [scopes]
  }
}

resource "auth0_resource_server_scopes" "this" {
  resource_server_identifier = auth0_resource_server.this.identifier

  scopes {
    name = "read"
    description = "Read values"
  }

  scopes {
    name = "update"
    description = "Update data"
  }
}

```

Can you try with the above config and let us know if you're still encountering issues? 🙏🏻

**Comment by sergiught** [comment]
Hey @james-emerton    👋🏻 

This should be fixed now as part of the [v1.0.0-beta.0](https://registry.terraform.io/providers/auth0/auth0/latest/docs) release! 🙌🏻 Please give it a try and let us know if you encounter any issues.

```
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "1.0.0-beta.0"
    }
  }
}
```

### 📚 Resources

[Quickstart](https://registry.terraform.io/providers/auth0/auth0/latest/docs/guides/quickstart) | [Documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) | [Migration Guide](https://github.com/auth0/terraform-provider-auth0/blob/v1/MIGRATION_GUIDE.md) | [Changelog](https://github.com/auth0/terraform-provider-auth0/releases/tag/v1.0.0-beta.0)

**Comment by reify-tanner-stirrat** [comment]
I just attempted this migration according to the deprecation and didn't have

```
lifecycle {
  ignore_changes = [scopes]
}
```

in the `auth0_resource_server` block (which isn't in the linked migration docs) and it broke our clients because their client grants no longer had the desired permissions. This may be because our client configuration is in one bit of TF state and the server/permission configuration is in another.

Is that behavior fixed in the new beta?

**Comment by sergiught** [comment]
Hey @reify-tanner-stirrat 👋🏻 

I'm sorry to hear about your issue 😞 , the migration guide tho actually contains this specific info: https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#resource-server-scopes-1. However yes, this is fixed in the new beta, there's no need to add lifecycle ignore blocks any more.

**Comment by reify-tanner-stirrat** [comment]
Got it. I think I was looking at the wrong revision of the migration guide. I appreciate it!

**Comment by H-Finch-404** [comment]
> Hey @reify-tanner-stirrat 👋🏻
> 
> I'm sorry to hear about your issue 😞 , the migration guide tho actually contains this specific info: https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#resource-server-scopes-1. However yes, this is fixed in the new beta, there's no need to add lifecycle ignore blocks any more.

It seems this information is in conflict with the resource documentation at https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/resource_server_scopes. Can you confirm we don't need this anymore? We have had issues with scopes disappearing on deployments

**Comment by elythh** [comment]
Hello, the `lifecycle` even though still listed in the documentation doesn't seem to be available anymore. Is this a known behavior ?

**Comment by whitlaaa** [comment]
If it helps anyone else, I just ran into this issue using the `v1.2.1` provider (latest at the moment). Swapping from a single `auth0_resource_server_scopes` to multiple `auth0_resource_server_scope` resources seems to have fixed the issue, e.g.:

```
# Broken
resource "auth0_resource_server_scopes "foo" {
    resource_server_identifier = auth0_resource_server.foo.id
    
    scopes {
        name = "create:foo"
        description = "Create foo"
    }

    scopes {
        name = "read:foo"
        description = "Read foo"
    }
}

---

# Works
resource "auth0_resource_server_scope" "create_foo" {
    resource_server_identifier = auth0_resource_server.foo.id
    scope = "create:foo"
    description = "Create foo"
}

resource "auth0_resource_server_scope" "read_foo" {
    resource_server_identifier = auth0_resource_server.foo.id
    scope = "read:foo"
    description = "Read foo"
}
```

**Comment by whitlaaa** [comment]
> [@whitlaaa](https://github.com/whitlaaa) I just tested with the below code, and it worked fine:
> 
> # Broken
> resource "auth0_resource_server_scopes" "foo" {
>     resource_server_identifier = auth0_resource_server.foo.identifier
>     
>     scopes {
>         name = "create:foo"
>         description = "Create foo"
>     }
> 
>     scopes {
>         name = "read:foo"
>         description = "Read foo"
>     }
> }
> I wonder if you are facing an issue because of the missing `"` after `auth0_resource_server_scopes` in your declaration.

Hm, I don't have access to the relevant project any more so I can't verify that, but if that was the case that's certainly embarrassing. 😆 

However, considering terraform yells at you when quotes are missing I'm pretty sure that wasn't the case and is just a typo from when I converted my sample over for reference in this issue. Thanks for checking though.
