### ISSUE TITLE
Provide a list of users associated with a specific role in Terraform data sources.

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [auth0/terraform-provider-auth0#688]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would appreciate having the ability to retrieve the users associated with a specific role when utilizing Terraform data sources.

```
data "auth0_role" "this" {
  role_id = "rol_xxxx"
}
```

Desired output:
``
 + auth0      = {
      + description = "my role"
      + id          = "rol_xxx"
      + name        = "my role"
      + permissions = []
      + role_id     = "rol_xxx"
      + users =  [
         + "google-oauth2|yyyy"
         + "google-oauth2|zzzz"
      ]
``

### Describe the ideal solution

As previously mentioned [here](https://github.com/auth0/terraform-provider-auth0/issues/22#issuecomment-1622405141), it appears that including this feature in your future plans is not currently being considered. However, it would be highly appreciated if it could be implemented at some point down the line.

It is worth noting that enabling this functionality might potentially have a performance impact, especially if a role contains a large number of users.

Please inform me if there is a possibility of considering this request.

Thank you.

**Comment by sergiught** [comment]
Hey @marcportabellaclotet-mt 👋🏻 

Thanks for moving our discussion to a dedicated issue. Would you mind giving us further info about how you intend to use this feature? 🙏🏻 Particularly useful would be knowing if you'd need more than 1000 users retrieved through this new proposed field on the data source.

**Comment by marcportabellaclotet-mt** [comment]
Thanks for the fast response, and interest about this topic.
In our scenario, we are not managing such a large number of users.
The use case that I have in mind, is to be able to sync roles and users from auth0 to another identity provider or user management system (SCIM).
It is not a hard requirement from our side, as we could write some code which connects to auth0 API. However, it may be useful in certain scenarios.

**Comment by sergiught** [comment]
Hey @marcportabellaclotet-mt 👋🏻 

I was able to add support for fetching the available users assigned to a role and provide this information through the `auth0_role` data source. We'll ship this new feature with the upcoming `v1.0.0-beta.1` release, so in case you haven't migrated yet, it would be great to do so before the `v1.0.0` GA relaese.

**Comment by marcportabellaclotet-mt** [comment]
Thanks a lot!
