### ISSUE TITLE
Azure email communication service support as email provider

### ISSUE THREAD

**Issue by fja-dawn** [auth0/terraform-provider-auth0#692]
### Checklist

- [x] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [x] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
 - [x] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
 - [x] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
 - [x] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [x] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.

### Describe the problem you'd like to have solved

I would appreciate having the ability to configure Azure email communication service as email provider when deploying Auth0 resources. 

Right now this only supported by clicking around in Auth0 portal, we would like to be able to automate this. 

### Describe the ideal solution

To configure Azure Email Communication services in Terraform.

Something a long the lines of:
```
resource "auth0_email" "azure_communication_service" {
  name                 = "azure_email_communication"
  enabled              = true
  default_from_address = "<from-address-value>"

  credentials {
    connectionstring = "<connectionstring-value>"
  }
}
```

### Alternatives and current workarounds

Configuring Azure Email Communication services in the Auth0 Portal.

**Comment by sergiught** [comment]
Hey @fja-dawn 👋🏻 

Thanks for raising this with us. In order for us to be able to provide this feature we'd need it first within the https://github.com/auth0/go-auth0 SDK that this provider leverages. We'll sync with the responsible team owning the Go SDK in order to push this feature through. I'll report back once I have an update. 

Appreciate your patience 🙏🏻

**Comment by sergiught** [comment]
Hey @fja-dawn  👋🏻 

We've followed up with this feature in https://registry.terraform.io/providers/auth0/auth0/1.0.0-beta.1. Please make sure you update the version in your terraform configs:

```
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
       version = "1.0.0-beta.1"
    }
  }
}
```

Please also check the migration guide: https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md.

Let us know if you have any other issues!  🙇🏻
