### ISSUE TITLE
Support RP-Initiated Logout Prompt

### ISSUE THREAD

**Issue by Vannevelj** [auth0/terraform-provider-auth0#701]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

This toggle exists in the UI: 
![image](https://github.com/auth0/terraform-provider-auth0/assets/2777107/a5a4e645-16bc-4ea6-9845-fd2cd4fb3b64)

I don't see any way for me to change this setting through the `auth0_tenant` resource. 

### Describe the ideal solution

Provide a new flag to configure this toggle.

### Additional context

We've also noticed that this toggle doesn't appear to work correctly. Even though it is turned off (per the screenshot), we still encounter it when a user logs out without an `id_token_hint` parameter.

**Comment by willvedd** [comment]
@Vannevelj Thanks for reporting this. I can confirm that this property does not exist in the provider. But nor is it implemented in the Auth0 Go SDK, which is a blocking requirement before it can be added to the TF provider. I can work with the appropriate team to get that implemented. I cannot provide a timeline for release but it is reasonable to expect this feature in the near future.

**Comment by sergiught** [comment]
Hey @Vannevelj, @roxanacojocari  👋🏻 

We've followed up with this feature in https://registry.terraform.io/providers/auth0/auth0/1.0.0-beta.1. Please make sure you update the version in your terraform configs:

```
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
       version = "1.0.0-beta.1"
    }
  }
}
```

Please also check the migration guide: https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md.

Let us know if you have any other issues!  🙇🏻
