### ISSUE TITLE
Ability to set decryptKey in options when creating auth0_connection resource

### ISSUE THREAD

**Issue by tb00-cloud** [auth0/terraform-provider-auth0#733]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

It's possible to use the Auth0 API v2 to add a custom decryption key to a connection. Anybody who wants to use Terraform but must use custom keys for SAML response decryption is blocked because it's not possible to do this via the resource.

### Describe the ideal solution

Ideally the options block will support the argument decryption_key in the exact way it support signing_key. 

```
resource "auth0_connection" "this" {
  name     = var.name
  display_name = var.display_name
  strategy = "samlp"
  show_as_button           = var.show_button

  options {
...

    signing_key {
      key  = var.request_signing_key.key
      cert = var.request_signing_key.cert
    }

    decryption_key {
      key = var.decryption_key.key
      cert = var.decryption_key.cert
    }

  }
}

```

### Alternatives and current workarounds

Currently you have to use the API directly to update these values.

**Comment by sergiught** [comment]
Hey @tb00-cloud 👋🏻 

Thanks for taking the time to raise this with us. At the moment the Go SDK that this provider relies upon for the Management Requests doesn't support the decryption key, however I'll liasion with the team owning the SDK and look into adding support for this. I'll circle back once I have an update.

**Comment by sergiught** [comment]
Hey @tb00-cloud  👋🏻 

We've followed up with this feature in https://registry.terraform.io/providers/auth0/auth0/1.0.0-beta.1. Please make sure you update the version in your terraform configs:

```
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
       version = "1.0.0-beta.1"
    }
  }
}
```

Please also check the migration guide: https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md.

Let us know if you have any other issues!  🙇🏻
