### ISSUE TITLE
Document log stream filters

### ISSUE THREAD

**Issue by alberto** [auth0/terraform-provider-auth0#739]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would like to filter the log stream to some categories, but the names are not documented, so I can't properly filter.

### Describe the ideal solution

Add a list of the available category names.

**Comment by sergiught** [comment]
Hey @alberto 👋🏻 thanks for taking the time to raise this with us. I have a PR that lists all the available filters in https://github.com/auth0/terraform-provider-auth0/pull/741.

**Comment by sergiught** [comment]
Hey @alberto 👋🏻 

The improved docs are now part of the [v1.0.0-beta.0](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/log_stream#filters) release! 🙌🏻 Please give it a try and let us know if you encounter any issues.

```
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "1.0.0-beta.0"
    }
  }
}
```

### 📚 Resources

[Quickstart](https://registry.terraform.io/providers/auth0/auth0/latest/docs/guides/quickstart) | [Documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) | [Migration Guide](https://github.com/auth0/terraform-provider-auth0/blob/v1/MIGRATION_GUIDE.md) | [Changelog](https://github.com/auth0/terraform-provider-auth0/releases/tag/v1.0.0-beta.0)

**Comment by alberto** [comment]
Thanks @sergiught! 🙌
