### ISSUE TITLE
Return signing key ID in outputs of auth0_client

### ISSUE THREAD

**Issue by baynezy** [auth0/terraform-provider-auth0#764]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The `auth0_client` resource has the `signing_keys` property. I would like to have the Key ID present in this as it is currently missing.

Currently `signing_keys` looks like so:-

```
tolist([
  tomap({
    "cert" = <<-EOT
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
    EOT
    "pkcs7" = <<-EOT
    -----BEGIN PKCS7-----

    -----END PKCS7-----

    EOT
    "subject" = "deprecated"
  }),
])
```

### Describe the ideal solution

```hcl
resource "auth0_client" "this" {
}

output "signing_keys" {
  value       = auth0_client.this.signing_keys
  description = "The JWT signing keys for the app client."
  sensitive   = true
}
```

The `signing_keys` output would have the `kid` property that you can get from the [Get all application signing keys](https://auth0.com/docs/api/management/v2/keys/get-signing-keys) API.

```json
[
  {
    "cert": "-----BEGIN CERTIFICATE----- -----END CERTIFICATE-----",
    "pkcs7": "-----BEGIN PKCS7----- -----END PKCS7-----\r\n",
    "kid": "xxxxxxxxxxxxxxxxxxxxx",
    "next": true,
    "fingerprint": "xxxxxxxxxxxxxxxxx",
    "thumbprint": "xxxxxxxxxxxxxx"
  },
  {
    "cert": "-----BEGIN CERTIFICATE----- -----END CERTIFICATE-----",
    "pkcs7": "-----BEGIN PKCS7----- -----END PKCS7-----\r\n",
    "kid": "xxxxxxxxxxxxxxxxxxxx",
    "current": true,
    "current_since": "xxxxxxxxxxxxxxxxxx",
    "fingerprint": "xxxxxxxxxxxxxxxxxxxxx",
    "thumbprint": "xxxxxxxxxxxxxxxxxxxxxx"
  }
]
```

### Alternatives and current workarounds

Without this, I am either going to have to try and use https://github.com/Mastercard/terraform-provider-restapi or shell out the cURL.

**Comment by sergiught** [comment]
Hey @baynezy 👋🏻 

Thanks for raising this with us and apologies for the late reply. Rather than pushing the signing keys within each client resource, would having an `auth0_keys` data-source work for you instead? Considering that these keys are for all applications. This data source would effectively return the same data as https://auth0.com/docs/api/management/v2/keys/get-signing-keys.

**Comment by baynezy** [comment]
Today would be great.

**Comment by sergiught** [comment]
Hey @baynezy 👋🏻 

Just a heads up that I have a PR open to add support for this in https://github.com/auth0/terraform-provider-auth0/pull/839. Feel free to give it a look. 

Short summary is that the new data source will look something like:

```terraform
data "auth0_signing_keys" "my_keys" {}

# Example on how to get the current key from the data source.
output "current_key" {
  value = try(
    element([for key in data.auth0_signing_keys.my_keys.signing_keys : key.kid if key.current], 0),
    "No current key found"
  )
}
```
