### ISSUE TITLE
Better Validation of Universal Login Template

### ISSUE THREAD

**Issue by AshleyEke** [auth0/terraform-provider-auth0#770]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am working on bringing an existing auth0 tenant under terraform. As part of this I am setting up the universal login using the auth0_branding resource. 

For the universal_login.body variable, I am reading the content from a HTML file withing my module's resources folder. The HTML file contains the existing HTML that I copied from within the universal login section of the auth0 dashboard.

When I run terraform validate it completes without issue but when I eventually go to apply it, I get the following error:
```
Error: 400 Bad Request: The template must contain a single auth0:head tag and at least one auth0:widget tag.
``` 

### Describe the ideal solution

It would have saved me a lot of additional effort with my company's branching and merging strategy if this would have been flagged during the validate command. Theoretically, it only needs to scan the contents set against the variable to check if the auth0:head and auth0:widget tags are present.

**Comment by sergiught** [comment]
Hey @AshleyEke 👋🏻 

Thanks for raising this with us. This is definitely a good improvement sugestion and we'll look into adding the validation at some point in time, however no ETA at the moment. I'll circle back once I have an update. Appreciate your patience meanwhile!

**Comment by sergiught** [comment]
Hey @AshleyEke  👋🏻

We have improved the validation of the universal login template body in the latest beta release, which you can find here: [registry.terraform.io/providers/auth0/auth0/1.0.0-beta.4](https://registry.terraform.io/providers/auth0/auth0/1.0.0-beta.4). Please give it a try, and if you come across any issues, don't hesitate to reach out.

✌🏻
