### ISSUE TITLE
`auth0_client_credentials` requires `read:client_secret` permissions

### ISSUE THREAD

**Issue by tadhglewis** [auth0/terraform-provider-auth0#774]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When migrating from `token_endpoint_auth_method` to `auth0_client_credentials`, if you're not using an access token that has `read:client_secret` you will receive `Error: 403 Forbidden: You cannot read the following fields: client_secret` when `apply`ing

More context: https://github.com/auth0/terraform-provider-auth0/issues/772#issuecomment-1673067445

### Expectation

I should not need a privileged access token to use this resource and it should be an empty string if `read:client_keys` is not in the token

> To access this attribute you need to add the read:client_keys scope to the Terraform client. Otherwise, the attribute will contain an empty string

https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/client_credentials#optional

### Reproduction

1. Use terraform without a `read:client_keys` on the access token
2. Migrate from `token_endpoint_auth_method` to `auth0_client_credentials`

### Auth0 Terraform Provider version

0.50.0

### Terraform version

NA

**Comment by sergiught** [comment]
Hey @tadhglewis 👋🏻 

I have a fix for this within https://github.com/auth0/terraform-provider-auth0/pull/795, once reviewed and approved it will be available in the next release. 

Appreciate your patience with the fix 🙏🏻
