### ISSUE TITLE
Error while trying to import auth0_resource_server resource

### ISSUE THREAD

**Issue by vaclav-stummer** [auth0/terraform-provider-auth0#775]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I want to configure, some properties of [Auth0 Management API](https://auth0.com/docs/api/management/v2) as is described in https://github.com/auth0/terraform-provider-auth0/pull/374 and I am trying to import the resource `auth0_resource_server` as is described in https://github.com/auth0/terraform-provider-auth0/issues/407. But unfortunately, I am getting an error

Error:
```
Error: failed to send the request: Get "https://api/v2/resource-servers/<Auth0_Management_API_ID>": Post "https:/oauth/token": http: no Host in request URL
```

I tried both command import and import from `imports.tf` file. But it leads to the same error. It seems I might miss some configuration in the auth0 provider. Or there might be some bug?

Thank you for any feedback or help

### Expectation

I am able to import the desired resource

### Reproduction

terraform command:
```
terraform import auth0_resource_server.<RESOURCE_SERVER_NAME> <Auth0_Management_API_ID>
```

### Auth0 Terraform Provider version

1.0.0-beta.1

### Terraform version

v1.5.5

**Comment by sergiught** [comment]
Hey @vaclav-stummer 👋🏻 

This looks like you're not configuring the provider correctly. Have you tried following the quickstart guide: https://registry.terraform.io/providers/auth0/auth0/latest/docs/guides/quickstart? 

Ensure you have the following within your terraform config files:

```terraform
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "1.0.0-beta.1"
    }
  }
}

provider "auth0" {
  domain        = "<yourDomain>" # can be sourced from AUTH0_DOMAIN env var
  client_id     = "<yourClientID>" # can be sourced from AUTH0_CLIENT_ID env var
  client_secret = "<yourClientSecret>" # can be sourced from AUTH0_CLIENT_SECRET env var
  # or alternatively an API token api_token = yourAPIToken, can be sourced from AUTH0_API_TOKEN env var
}
```

**Comment by vaclav-stummer** [comment]
Yes, but we use it in different models for different environments. This is our structure. We are working with it for a couple of months and we didn't need to import before. Do you think the problem could be caused by it?

```
/auth0 # place where are variables, secrets and initial configuraiont
  /terraform.tf
  /providers.tf
/modules
  /auth0 # dynamic module, which works for all environments
    /terraform
    ...reset of the resources
```

auth0/terraform.tf
```
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "1.0.0-beta.1"
    }
  }
}

module "terraform" {
  source = "../modules/terraform"
  name   = "Auth0"
}

locals {
  env_variables = yamldecode(file("<PATH_TO_SECRETS>"))
}
```

auth0/providers.tf
```
provider "auth0" {
  alias         = "amy"
  domain        = local.env_variables["amy_domain"]
  client_id     = local.env_variables["amy_client_id"]
  client_secret = local.env_variables["amy_client_secret"]
}

provider "auth0" {
  alias         = "experimental"
  domain        = local.env_variables["experimental_domain"]
  client_id     = local.env_variables["experimental_client_id"]
  client_secret = local.env_variables["experimental_client_secret"]
}

...

```

modules/auth0/terraform.tf
```
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "1.0.0-beta.1"
    }
  }
}
```

**Comment by vaclav-stummer** [comment]
So it seems that we had the structure wrongly and it was working until now just by coincidence. We had to move the `auth0` provider to the modules, so it is created dynamically from within the module.

With that, we can close this issue and thank you for your great work on this terraform provider, especially de documentation, migration with it was a piece of cake!

**Comment by sergiught** [comment]
Hey @vaclav-stummer 👋🏻 

Glad you were able to find the issue in your setup. As a suggestion if you're setting up a multi-environment workflow consider the following structure:

```
.
└── terraform/
    ├── modules/
    │   ├── auth0_client.tf
    │   ├── auth0_actions.tf
    │   ├── inputs.tf
    │   └── outputs.tf
    ├── production/
    │   ├── provider.tf
    │   └── config.tf
    ├── staging/
    │   ├── provider.tf
    │   └── config.tf
    └── development/
        ├── provider.tf
        └── config.tf
```

And within each environment folder only have 1 instance of the provider setup.

**Comment by vaclav-stummer** [comment]
Thanks this structure seems great. We will consider migrating to it
