### ISSUE TITLE
Actions Runtime Support for `node18-actions`

### ISSUE THREAD

**Issue by chadrsmith** [auth0/terraform-provider-auth0#777]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When uploading an Action with `node18` as the runtime, the Tenant shows a suggestion 

> "Upgrade this action from the Node 18 Beta to Node 18 GA runtime"

I upgraded the version and got the action using the Auth0 Management API to see the runtime it was updated to which was `node18-actions`. When trying to use `node18-actions` runtime in the terraform, I get the following error: 

`Error: expected runtime to be one of [node12 node16 node18], got node18-actions`

### Expectation

I would expect that runtime would accept all runtime versions that are supported in Auth0

### Reproduction

1. Upload an action using runtime `node18`
2. In the Auth0 Tenant upgrade the the runtime to Node 18 GA runtime
3. Call the Auth0 management API and look at the response for action, runtime should be `node18-actions`
4. Update resource to use `node18-actions` for runtime
5. Run terraform plan

### Auth0 Terraform Provider version

1.0.0-beta.1

### Terraform version

1.5.5

**Comment by tadhglewis** [comment]
Duplicate of https://github.com/auth0/terraform-provider-auth0/issues/705

**Comment by tadhglewis** [comment]
See https://github.com/auth0/terraform-provider-auth0/issues/705 for more details but the tldr is 1.0.0 translates `node18` to `node18-actions` behind the scenes.

As in, the API technically has `node18` (beta) and `node18-actions` (GA) however the Management Dashboard only has `Node 18` as the beta version has been deprecated / shouldn't be used.

1.0.0 terraform simulates similar behaviour as the Management Dashboard

**Comment by willvedd** [comment]
@tadhglewis Is correct. This was a conscious decision to deviate away from the official API to align better to user expectations; we don't believe it is intuitive for users to know that `node18-actions` is GA while `node18` is the beta. Further, the beta version is soon to be phased out, so for v1 of the Terraform provider, we're only allowing users to select Node 18 GA and disallowing usage of the beta.

@chadrsmith Does this clear up some confusion or are you still experiencing further issue?

**Comment by chadrsmith** [comment]
Yes - @willvedd  cleared up the issue. Thank you so much!

**Comment by brianhyder** [comment]
Thank you!  We really appreciate the support and flexibility.
