### ISSUE TITLE
Can't enable `custom_domains_in_emails` in the same apply as automated custom domain verification

### ISSUE THREAD

**Issue by tyhunt99** [auth0/terraform-provider-auth0#781]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When following the example for automated verification there is a race condition between the domain being marked as ready and trying to enable the `enable_custom_domain_in_emails` in the tenant.

### Expectation

I would expect the tenant resource to be updated with the flag. But I would not expect to have to set an explicit `depends_on` in the tenant.

### Reproduction

Assuming the tenant is already created using the defaults in the UI. The following terraform code consistently produces the error. Note the terraform example has some filler values

<details><summary>Terraform code</summary>

```
resource "auth0_tenant" "production_tenant" {
  friendly_name = "NAME"
  picture_url   = "http://picture.com"

  support_email = "email@email.com"
  support_url   = ""

  flags {
    enable_client_connections              = false
    enable_apis_section                    = false
    enable_pipeline2                       = false
    enable_dynamic_client_registration     = false
    enable_custom_domain_in_emails         = true
    enable_legacy_logs_search_v2           = false
    disable_clickjack_protection_headers   = false
    enable_public_signup_user_exists_error = false
  }

  session_lifetime      = 168
  idle_session_lifetime = 72
  sandbox_version       = "12"
  enabled_locales       = ["en"]
}


resource "auth0_custom_domain" "auth_domain" {
  domain = "auth.example.com"
  type   = "auth0_managed_certs"
}

resource "auth0_custom_domain_verification" "verification" {
  custom_domain_id = auth0_custom_domain.patients_auth_domain.id

  depends_on = [aws_route53_record.verification_cname]
  timeouts { create = "15m" }
}

resource "aws_route53_record" "verification_cname" {
  zone_id  = "xxxxxxxxxxxxxxxx"
  name     = auth0_custom_domain.patients_auth_domain.domain
  type     = "CNAME"
  ttl      = 600
  records  = [auth0_custom_domain.auth_domain.verification[0].methods[0].record]
}
```

</details>

<details><summary>Apply output</summary>

```
auth0_custom_domain.auth_domain: Creating...
auth0_tenant.production_tenant: Modifying... [id=c969a9a6-9596-4676-bdbd-b8a88183d8f7]
auth0_custom_domain.auth_domain: Creation complete after 2s [id=cd_xxxxxxxxx]
aws_route53_record.verification_cname: Creating...
aws_route53_record.verification_cname: Still creating... [10s elapsed]
aws_route53_record.verification_cname: Still creating... [20s elapsed]
aws_route53_record.verification_cname: Still creating... [30s elapsed]
aws_route53_record.verification_cname: Still creating... [40s elapsed]
aws_route53_record.verification_cname: Creation complete after 46s [id=Z1RFDSAFdDAS_auth.example.com_CNAME]
auth0_custom_domain_verification.verification: Creating...
auth0_custom_domain_verification.verification: Still creating... [10s elapsed]
auth0_custom_domain_verification.verification: Still creating... [20s elapsed]
auth0_custom_domain_verification.verification: Still creating... [30s elapsed]
auth0_custom_domain_verification.verification: Still creating... [40s elapsed]
auth0_custom_domain_verification.verification: Still creating... [50s elapsed]
auth0_custom_domain_verification.verification: Still creating... [1m0s elapsed]
auth0_custom_domain_verification.verification: Still creating... [1m10s elapsed]
auth0_custom_domain_verification.verification: Still creating... [1m20s elapsed]
auth0_custom_domain_verification.verification: Still creating... [1m30s elapsed]
auth0_custom_domain_verification.verification: Creation complete after 1m33s [id=cd_xxxxxxxxx]
╷
│ Error: 400 Bad Request: Before enabling the "enable_custom_domain_in_emails" flag, you must have a custom domain with status: "ready"
│ 
│   with auth0_tenant.patients_production,
│   on tenant.tf line 1, in resource "auth0_tenant" "patients_production":
│    1: resource "auth0_tenant" "patients_production" {
│ 
╵
Releasing state lock. This may take a few moments...
```

</details>

### Auth0 Terraform Provider version

0.5

### Terraform version

1.5.4

**Comment by sergiught** [comment]
Hey @tyhunt99 👋🏻 

Thanks for raising this with us. Considering the implicit dependency is found within 2 separate resources we are unable to orchestrate the sequence directly ourseleves through the underlying code. For such use cases terraform introduced the `depends_on` meta argument. Please make use of this or perform an apply in two steps, first adding a custom domain and verifying it, and second enabling the tenant flag. 

We've updated however our docs to further clarify the dependency in https://github.com/auth0/terraform-provider-auth0/pull/797. 

Unfortunately there isn't anything more we can do at the moment.
