### ISSUE TITLE
OIDC connections: Specify user mapping

### ISSUE THREAD

**Issue by MatthiasWinzeler** [auth0/terraform-provider-auth0#783]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hi folks - we are happy users of the Auth0 provider, but couldn't find a way to set the user mapping on OIDC connections.

In the UI, it can be specified as follows:

<img width="610" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/474567/75f781e7-8e89-482c-b0f9-fb245078c32f">

However, the provider does not offer a field to set it. From browsing through the docs and Github issues, we saw that there is a similar field `fields_map` for SAML connections.

Interestingly, when applying a setting like the following, it succeeds, but the OIDC connection in the portal doesn't show any fields anymore (leaving the connection in a weird state, so we had to recreate it):

```
options {
    fields_map = jsonencode({
      "mapping_mode": "use_map",
      "attributes": {
        "name" : "$${context.tokenset.name}"
      }
    })
}
```

### Describe the ideal solution

It would be nice if the `auth0_connection` resource would allow specifying the mapping. Example:

```
  options {
    attribute_mapping = jsonencode({
      "mapping_mode": "use_map",
      "attributes": {
        "name" : "$${context.tokenset.name}"
      }
    })
  }
```

**Comment by sergiught** [comment]
Hey @MatthiasWinzeler 👋🏻 

Thanks for raising this with us, you're correct that at the moment this field is lacking within the provider. We'll aim at adding support for it in the near future, however no ETA as to when. I'll circle back once I have an update. Appreciate your patience!

**Comment by sergiught** [comment]
Hey @MatthiasWinzeler  👋🏻

We have added support for this within the `auth0_connection` resource in the latest beta release. Please give it a try, and if you come across any issues, don't hesitate to reach out.

Changelog: https://github.com/auth0/terraform-provider-auth0/releases/tag/v1.0.0-beta.4
Docs: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection#nested-schema-for-optionsattribute_map
Example: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection#oidc-connection

✌🏻

**Comment by MatthiasWinzeler** [comment]
hi @sergiught that's great news, many thanks - we'll give it a try and let you know if we encounter any issues.
