### ISSUE TITLE
Unable to import user into a `auth0_user`

### ISSUE THREAD

**Issue by multani** [auth0/terraform-provider-auth0#808]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I tried to import a Auth0 user, but the import fails while trying to parse the "email verified" field (I assume):

```
$ terraform import auth0_user.test "$user_id""             
auth0_user.test: Importing from ID "$user_id"...
auth0_user.test: Import prepared!
  Prepared auth0_user for import
auth0_user.test: Refreshing state... [id=$user_id]
╷
│ Error: failed to unmarshal response payload: strconv.ParseBool: parsing "$user_id": invalid syntax
```

Running in debug mode, I can see that the get request on /api/v2/users/:id works and returns 200:

```
/api/v2/users/$user_id HTTP/1.1
Host: xxx.auth0.com
User-Agent: Terraform-Provider-Auth0/1.0.0-beta.2 (Go-Auth0-SDK/1.0.0; Terraform-SDK/2.10.1; Terraform/1.5.3)
Content-Length: 5
Auth0-Client: ...
Content-Type: application/json
Accept-Encoding: gzip
[...]

HTTP/2.0 200 OK
[...]
```

The JSON output contains something like this:

```json
{
  "email": "email@example.com",
  "email_verified": "email@example.com",
  ...
  "user_id": "$user_id",
  ...
}
```

This seems to come from the Auth0 Go SDK: https://github.com/auth0/go-auth0/blob/d28490de18ad5d5322ea9a9b92e84ad43591352c/management/user.go#L146

### Expectation

I can import a user using its Auth0 user ID.

### Reproduction

Create a `auth0_user` resource:

```hcl
resource "auth0_user" "test" {
  connection_name = "My-Connection"
  email           = "user@example.com"
}
```

Try to import an existing user in this resource:

```
terraform import auth0_user.user "$user_id"
```

### Auth0 Terraform Provider version

1.0.0-beta.2

### Terraform version

v1.5.6

**Comment by sergiught** [comment]
Hey @multani 👋🏻 

Thanks for raising this with us. The issue is caused by a corrupted user data as `email_verified` should only contain true or false, either in string form or boolean form. From docs you can also see the correct type for this is a boolean (true/false), https://auth0.com/docs/api/management/v2/users/get-users-by-id. 

Would you mind offering more context into how this particular user was created / updated? What connection / identiy provider does it come from?
