### ISSUE TITLE
to have a way to limit application/client to specific user databases only

### ISSUE THREAD

**Issue by phi1ipp** [auth0/terraform-provider-auth0#811]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

When creating a client with TF, I can't specify databases which application should be using. There is resource to add an application to a database, but if there are existing DBs in the environment the application maybe assigned to them.

### Describe the ideal solution

To have a parameter on client, or a separate resource which would allow constraints/lists of databases to be used by the client

### Alternatives and current workarounds

Manually verify and adjust available database connections

**Comment by pfrydids** [comment]
I think this might be relevant 

https://community.auth0.com/t/application-connections/42377

**Comment by sergiught** [comment]
Hey @phi1ipp 👋🏻 

As @pfrydids mentioned, if you don't want any connections to be automatically enabled for new clients please set the `enable_client_connections` flag to false on the tenant resource:

```terraform
resource "auth0_tenant" "my_tenant" {
  flags {
    enable_client_connections = false
  }
}
```

And afterwards use the 1:1 or 1:many `auth0_connection_client(s)` resource to manage enabled clients on a connection. 

Docs: 

- https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection_client
- https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection_clients

Let us know if you have any other questions or if you experience issues with the above.

**Comment by phi1ipp** [comment]
Thank you @sergiught , that's exactly the path I took.
