### ISSUE TITLE
After importing a auth0_tenant resource the tenant flags in the state do not reflect what is seen in the auth0 UI

### ISSUE THREAD

**Issue by pfrydids** [auth0/terraform-provider-auth0#814]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have imported a tenant:
```
terraform import auth0_tenant.public XXXXX-XXXXXX-XXXXX
terraform state show auth0_tenant.public
```
and I see flags 

```
    flags {
        allow_legacy_delegation_grant_types    = false
        allow_legacy_ro_grant_types            = false
        allow_legacy_tokeninfo_endpoint        = false
        dashboard_insights_view                = false
        dashboard_log_streams_next             = false
        disable_clickjack_protection_headers   = false
        disable_fields_map_fix                 = false
        disable_management_api_sms_obfuscation = false
        enable_adfs_waad_email_verification    = false
        enable_apis_section                    = false
        enable_client_connections              = false
        enable_custom_domain_in_emails         = false
        enable_dynamic_client_registration     = false
        enable_idtoken_api2                    = false
        enable_legacy_logs_search_v2           = false
        enable_legacy_profile                  = false
        enable_pipeline2                       = false
        enable_public_signup_user_exists_error = false
        mfa_show_factor_list_on_enrollment     = false
        no_disclose_enterprise_connections     = false
        revoke_refresh_token_grant             = false
        universal_login                        = true
        use_scope_descriptions_for_consent     = false
    }
```
This is inconsistent with what is present in the auth0 UI.

The main reason for pursuing this is to set 
```
  flags {
    enable_client_connections = false
  }
```

Currently because from a terraform state perspective this setting is false no changes get shown in the plan.

Also can some identifier attributes be included in the auth0_tenant resource state. It is impossible to know what tenant has been imported.

### Expectation

That the default auth0 tenant behaviour is changed from enabling all client connections to not enabling any by default.

### Reproduction

See above.

### Auth0 Terraform Provider version

0.49.0

### Terraform version

1.1.9

**Comment by sergiught** [comment]
Hey @pfrydids 👋🏻 

Thanks for raising this issue with us. The current list of tenant flags within the tenant resource are a mix between flags available on different type of tenants and because they are defined within the schema they'll all get initialized to something (true/false as the type is Bool) even if not all flags are available on your tenant. In order to toggle one on/off you have to explicitly opt in.

If `enable_client_connections` is set as false it means on your tenant that flag is disabled. To toggle it on you simply have to set `enable_client_connections = true`. Does the state say the flag is false but the UI shows it as true for you?

Also you can only have one tenant per provider workspace, so the tenant is the one you've configured your provider with.

**Comment by sergiught** [comment]
Hey @pfrydids 👋🏻 

I'm gonna close this issue down as I wasn't able to find any issues toggling the `enable_client_connections` flag on or off. However I'm more than happy to reopen if you're still experiencing issues or if you have any other questions.
