### ISSUE TITLE
After importing a auth0_client resource the cross_origin_auth attribute in the state do not reflect what is seen in the auth0 UI

### ISSUE THREAD

**Issue by cgetzen** [auth0/terraform-provider-auth0#816]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After importing a SPA client, the plan indicates that terraform will set 
```
    ~ cross_origin_auth                   = false -> true
```

Even though cross origin auth is already set to true in the UI.

### Expectation

The import state correctly sets cross_origin_auth to true.

### Reproduction

1. Create a SPA app in the UI with cross original auth enabled.
2. Import it into terraform

### Auth0 Terraform Provider version

1.0.0-beta.3

### Terraform version

1.5.4

**Comment by sergiught** [comment]
Hey @cgetzen 👋🏻 

Thanks for taking the time to raise this with us. Upon investigating, I couldn't identify any issues with the `cross_origin_auth` setting within the provider. It is indeed functioning as intended to enable or disable Cross-Origin Authentication.

However, there's one important detail to note. When creating a fresh SPA through the UI, the Cross-Origin Authentication toggle might appear enabled by default on the UI, but it's not actually enabled on the API level. To activate Cross-Origin Authentication, you can safely proceed by applying the diff to set `cross_origin_auth` to true through the provider.

Thank you for your understanding and patience. If you have any more questions or need further assistance, please don't hesitate to reach out.

**Comment by wafrelka** [comment]
@sergiught 

Hi. I also encountered this issue.

> When creating a fresh SPA through the UI, the Cross-Origin Authentication toggle might appear enabled by default on the UI, but it's not actually enabled on the API level.

Is this correct?

For a fresh SPA client created through the Auth0 dashboard, the client metadata retrieved from the API does not contain the `cross_origin_auth` field at all.

The dashboard interprets the absence of `cross_origin_auth` as *cross origin auth enabled*, while the Terraform provider and the underlying Auth0 Go client interpret it as *disabled*, resulting in the dicrepancy mentioned in this issue.

Based on my local testing with [auth0.js](https://github.com/auth0/auth0.js), it appears that the dashboard's interpretation is the correct one. Cross-origin authentication seems to be enabled by default.
