### ISSUE TITLE
Auth0 Connections

### ISSUE THREAD

**Issue by stephenbawks** [auth0/terraform-provider-auth0#817]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

When creating a `auth0_connection`, mainly with the `strategy` set to be "google-apps" there are many different settings for establishing a connection for Google Workspace as an IDP Enterprise connection.

There is one issue I have run into because after setting up a connection for Google, once you authorize the connection it creates an admin token as well as a admin refresh token.  However if you make a change later, no matter what that change is, it loses those admin tokens.  Which then requires you to go back and re-authorize those connections if there is every a change.

### Describe the ideal solution

Wondering if there is a way to preserve those admin tokens so its not losing those tokens which then requires you reauthorize those connections.

**Comment by sergiught** [comment]
Hey @stephenbawks 👋🏻

We appreciate your feedback and wanted to let you know that we have addressed this issue in the latest beta release. Please give it a try, and if you come across any other issues, don't hesitate to reach out.

Changelog: https://github.com/auth0/terraform-provider-auth0/releases/tag/v1.0.0-beta.4
Terraform Registry Docs: https://registry.terraform.io/providers/auth0/auth0/1.0.0-beta.4

✌🏻
