### ISSUE TITLE
Optional value in auth0_connection password_history setting

### ISSUE THREAD

**Issue by charlrvd** [auth0/terraform-provider-auth0#82]
### Describe the problem

Hi, I've recently hit an error while using the `auth0_connection` [resource](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection). 
The `password_history` setting was set as following

```
    password_history {
      enable = false
    }
```

This resulted in an error

```
Error: 400 Bad Request: Payload validation error: 'Expected type integer but found type null' on property options.password_history.size.
```

The secondary issue I found was that when setting up the value to 0, it also raises the same error. It makes sense to raise the same error but the documentation didn't explicitely mention that 0 would be translated to a null value and not be allowed.

This setting raised the same error
```
    password_history {
      size   = 0
      enable = false
    }
```

### What was the expected behavior?

I'd except that when `password_history.enabled` is set to false, the default value for `password_history.size` is enough and doesn't raise an error

### Reproduction

Use any `auth0_connection` resource with a `password_history.enabled` to `false` and no `password_history.size` explicit value.
Or a `password_history.enabled` to `false` and `password_history.size` to `0`.

### Environment

- terraform_version: 1.1.5
- auth0/auth0 v0.27.0

**Comment by sergiughf** [comment]
Hey @charlrvd thanks for opening this issue, we have a potential solution over at #97 that hopefully will get merged soon. Will update this issue when that happens. Thanks for your patience!

**Comment by sergiughf** [comment]
Closing this down as this is now available through https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.29.0
