### ISSUE TITLE
Support configuration of `allow_organization_name_in_authentication_api` in `auth0_tenant` resource 

### ISSUE THREAD

**Issue by kherock** [auth0/terraform-provider-auth0#826]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

https://auth0.com/docs/manage-users/organizations/configure-organizations/use-org-name-authentication-api

Auth0 tenants now support configuring the `allow_organization_name_in_authentication_api`, which is detailed in the article above. I didn't notice mention of this in issues so I was wondering if there's an ETA for supporting this feature?

### Describe the ideal solution

New boolean parameter for `allow_organization_name_in_authentication_api` is added to the `auth0_tenant` resource.

**Comment by sergiught** [comment]
Hey @kherock 👋🏻

Thanks for raising this with us. We have added the new field within the `auth0_tenant` resource in the latest beta release, which you can find here: [registry.terraform.io/providers/auth0/auth0/1.0.0-beta.4](https://registry.terraform.io/providers/auth0/auth0/1.0.0-beta.4). Please give it a try, and if you come across any issues, don't hesitate to reach out.

Docs: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/tenant#allow_organization_name_in_authentication_api

✌🏻

**Comment by kherock** [comment]
Hey @sergiught thanks for handling this. Was this supposed to be included as a top-level attribute? It seems like it belongs in the `flags` nested block.

**Comment by sergiught** [comment]
Hey @kherock 👋🏻 

> Was this supposed to be included as a top-level attribute? It seems like it belongs in the flags nested block.

This is a tenant level setting, not a flag. Please also see the API Docs: https://auth0.com/docs/api/management/v2/tenants/patch-settings
