### ISSUE TITLE
Error when created client with device_code grant type 

### ISSUE THREAD

**Issue by jusbuc2k** [auth0/terraform-provider-auth0#828]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using `auth0_client` with `grant_types` including `urn:ietf:params:oauth:grant-type:device_code`

We get the error:
```
 400 Bad Request: Application must have Token Endpoint Authentication Method set to "none" when urn:ietf:params:oauth:grant-type:device_code is enabled
```

However, when adding that option (obviously because it's been removed as an option):

```
An argument named "token_endpoint_auth_method" is not expected here.`
```

Client code snippet:

```
resource "auth0_client" "cli_client" {
  name            = "${var.product_id} CLI"
  description     = "Client for Device Code Flow"
  app_type        = "native"
  grant_types = [ "urn:ietf:params:oauth:grant-type:device_code", "refresh_token" ]
  oidc_conformant = true
  is_first_party = true
  logo_uri = local.app_logo_uri
  jwt_configuration {
    alg = "RS256"
  }
  lifecycle {
    ignore_changes = [ 
      callbacks,
      allowed_logout_urls,
      allowed_origins,
      web_origins
    ]
  }
}
```

### Expectation

I expect the client to get created correctly.

### Reproduction

1. Create a client using the grant type "urn:ietf:params:oauth:grant-type:device_code" and apply the terraform

### Auth0 Terraform Provider version

1.0.0-beta.3

### Terraform version

1.5.7

**Comment by VeithBuergerhoff** [comment]
This error results from a breaking change. You should be able to specify the auth method using the `auth0_client_credentials` resource like this:

```terraform
resource "auth0_client" "cli_client" {
  name            = "${var.product_id} CLI"
  description     = "Client for Device Code Flow"
  app_type        = "native"
  grant_types     = ["urn:ietf:params:oauth:grant-type:device_code", "refresh_token"]
  oidc_conformant = true
  is_first_party  = true
  logo_uri        = local.app_logo_uri
  jwt_configuration {
    alg = "RS256"
  }
  lifecycle {
    ignore_changes = [
      callbacks,
      allowed_logout_urls,
      allowed_origins,
      web_origins
    ]
  }
}

resource "auth0_client_credentials" "cli_client" {
  client_id = auth0_client.cli_client.id

  authentication_method = "none"
}
```

See [here](https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#client-authentication-method) for more details.
Taken from [this v0.x code](https://github.com/auth0/terraform-provider-auth0/blob/0269a8792e08ed5d990d3d19996695d6bf144ebe/internal/auth0/client/resource.go#L544C1-L567C6).

If I interpret the code correctly, this is a seperate api call [according to this function](https://github.com/auth0/terraform-provider-auth0/blob/16676a300555fd835360292453842f297a639bf3/internal/auth0/client/resource_credentials.go#L412C1-L423C2).
But the client is being created first [here](https://github.com/auth0/terraform-provider-auth0/blob/4e81f0977029b1ab19a053372b9bdb10eb3d999c/internal/auth0/client/resource.go#L1279C1-L1292C1) before the auth method is being set, causing the error.

[The api does not appear to support this yet.](https://auth0.com/docs/api/management/v2/clients/post-clients)

**Comment by jusbuc2k** [comment]
Correct, I'm aware of being able to use `auth0_client_credentials` with `authentication_method` set to `none`. As you said though, that is a separate API call, so the first API call to create the client still fails, because now we can't set `token_endpoint_auth_method`, which appears to be a required field when using device code.

**Comment by sergiught** [comment]
Hey @jusbuc2k 👋🏻

We appreciate your feedback and wanted to let you know that we have addressed this issue in the latest beta release, which you can find here: https://registry.terraform.io/providers/auth0/auth0/1.0.0-beta.4. Please give it a try, and if you come across any other issues, don't hesitate to reach out.

Additionally, it's worth mentioning that as a workaround for this problem, you could have set the `client_grants` after using the `auth0_client_credentials` resource to set the authentication method as `none`, and then configure the grants using the device code flow.

✌🏻
