### ISSUE TITLE
Add support map_user_id_to_id in Auth0 connections

### ISSUE THREAD

**Issue by shalabi** [auth0/terraform-provider-auth0#838]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am trying to create terraform code for auth0 enterprise connection with google workspace.
But while creating the code, I don’t see any terraform argument for "Use ID instead of Email for Auth0 User ID " to enable it.
as we have the boolean argument for “Enable Users API” in terraform documentation in “auth0_connection google_apps”
I am attaching the screenshot of the argument that I want enable using terraform.
As you can see in the screenshot “Enable Users API” can be enabled using terraform but in case of "Use ID instead of Email for Auth0 User ID " we don’t have any terraform argument to enable it.

![image](https://github.com/auth0/terraform-provider-auth0/assets/171654/bbccd30a-1349-4fed-9335-6881eef61914)

### Describe the ideal solution

Add the option:

`map_user_id_to_id": true`

see:
https://community.auth0.com/t/how-to-enable-use-id-instead-of-email-for-auth0-user-id-using-terraform/107997/3

**Comment by sergiught** [comment]
Hey @shalabi  👋🏻 

This is now avaialable in the latest v1.0.0 GA release https://registry.terraform.io/providers/auth0/auth0/latest. Please give it a try and let us know if you encounter any issues.
