### ISSUE TITLE
Migrating from 0.50.2 -> 1.0.0 fails with no schema available

### ISSUE THREAD

**Issue by fals** [auth0/terraform-provider-auth0#848]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We are migrating from `v0.50.2` to `v1.0`, but we stuck into issues with some resources. Following the migration documentation didn't help us to get it done.

```bash
Error: no schema available for auth0_trigger_binding.login_flow while reading state; this is a bug in Terraform and should be reported
Error: no schema available for auth0_email.sendgrid_email_provider while reading state; this is a bug in Terraform and should be reported
```

### Expectation

After following the migration guide [Upgrading from v0.x → v1.0](https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#upgrading-from-v0x--v10) we should see a clean plan to execute.

### Reproduction

1. Given you already have existing `auth0_trigger_binding` and resources a `auth0_email_provider`
2. When I execute my plan
3. Then I should have expected plan without resource erros

### Auth0 Terraform Provider version

v1.0.0

### Terraform version

v1.5.0

**Comment by sergiught** [comment]
Hey @fals 👋🏻 

Thanks for taking the time to raise this with us. From the error message it seems like the `auth0_trigger_binding` and `auth0_email` resources weren't removed from state and then reimported, as mentioned in https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#email-provider and https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#email-provider.

Before upgrading please execute the following:

```sh
$ terraform state rm auth0_trigger_binding.login_flow
$ terraform state rm auth0_email.sendgrid_email_provider
```

Then:
- Rename the resource from `auth0_trigger_binding` to `auth0_trigger_actions`
- Run: `terraform import auth0_trigger_actions.login_flow login_flow`
- Rename the resource from `auth0_email` to `auth0_email_provider`
- Run: `terraform import auth0_email_provider.sendgrid_email_provider <any-uuid-eg-b4213dc2-2eed-42c3-9516-c6131a9ce0b0>`

Let me know if you encounter any issues with the above, or have any other questions.

**Comment by fals** [comment]
> Hey @fals 👋🏻
> 
> Thanks for taking the time to raise this with us. From the error message it seems like the `auth0_trigger_binding` and `auth0_email` resources weren't removed from state and then reimported, as mentioned in https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#email-provider and https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#trigger-bindings.
> 
> Before upgrading please execute the following:
> 
> ```shell
> $ terraform state rm auth0_trigger_binding.login_flow
> $ terraform state rm auth0_email.sendgrid_email_provider
> ```
> 
> Then:
> 
> * Rename the resource from `auth0_trigger_binding` to `auth0_trigger_actions`
> * Run: `terraform import auth0_trigger_actions.login_flow <trigger-id>`
> * Rename the resource from `auth0_email` to `auth0_email_provider`
> * Run: `terraform import auth0_email_provider.sendgrid_email_provider <any-uuid-eg-b4213dc2-2eed-42c3-9516-c6131a9ce0b0>`
> 
> Let me know if you encounter any issues with the above, or have any other questions.

Thank you, I missed that we should remove the old resources, I will try and update the issue after executing the plan again.

**Comment by emilhdiaz** [comment]
Hi @sergiught, I'm attempting to re-import the auth0_email_provider but getting the following error... Any thoughts as to what might be happening? 

```
$> terraform import auth0_email_provider._ b4213dc2-2eed-42c3-9516-c6131a9ce0b0

data.auth0_tenant._: Reading...
data.auth0_tenant._: Read complete after 1s [id=terraform-20240220201842679700000001]
╷
│ Error: Configuration for import target does not exist
│ 
│ The configuration for the given import auth0_email_provider._ does not
│ exist. All target instances must have an associated configuration to be
│ imported.
╵
```
