### ISSUE TITLE
Forbidden to destroy auth0_branding with terraform

### ISSUE THREAD

**Issue by rfrerebe-stx** [auth0/terraform-provider-auth0#853]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Using a auth0_branding with terraform, like this one

```
resource "auth0_branding" "my_brand" {
  logo_url = "https://mycompany.org/logo.png"
  favicon_url = "https://mycompany.org/favicon.ico"
  colors {
    primary         = "#0059d6"
    page_background = "#000000"
  }
}
```

I get the following error:
403 Forbidden: The account is not allowed to perform this operation, please contact our support team

### Expectation

no error

### Reproduction

Apply a auth0_brading like 

```
resource "auth0_branding" "my_brand" {
  logo_url = "https://mycompany.org/logo.png"
  favicon_url = "https://mycompany.org/favicon.ico"
  colors {
    primary         = "#0059d6"
    page_background = "#000000"
  }
}
```

### Auth0 Terraform Provider version

1.0.0

### Terraform version

1.5.7

**Comment by sebdebros** [comment]
any news on this issue? or a work around?

**Comment by sergiught** [comment]
Hey folks, I'll be looking at this today. I'll circle back once I have an update.

**Comment by sergiught** [comment]
Hey folks, this has been now fixed within https://github.com/auth0/terraform-provider-auth0/releases/tag/v1.1.0.
