### ISSUE TITLE
Unable to create user - Connection must be enabled for this client to perform single user creation and signup operations

### ISSUE THREAD

**Issue by leonseng** [auth0/terraform-provider-auth0#854]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Attempted to create an `auth0_user` resource and received the following error:

```
auth0_user.this: Creating...
╷
│ Error: 400 Bad Request: Connection must be enabled for this client to perform single user creation and signup operations (client_id: lqR5zeI2OVVhfcAWSBK5dE4HnyySbQ1l - connection: test)
│ 
│   with auth0_user.this,
│   on main.tf line 35, in resource "auth0_user" "this":
│   35: resource "auth0_user" "this" {
│ 
╵
```

### Expectation

The `auth0_user` should be created.

### Reproduction

Apply the Terraform code as below to create a database connection, a client and a user
```
resource "auth0_connection" "this" {
  name                 = "test"
  is_domain_connection = false
  strategy             = "auth0"
  realms               = ["test"]
}

resource "auth0_client" "this" {
  name = "test"

  app_type                            = "regular_web"
  grant_types                         = ["authorization_code"]
  custom_login_page_on                = false
  is_token_endpoint_ip_header_trusted = false
  oidc_conformant                     = true
  sso_disabled                        = false
}

resource "auth0_connection_clients" "this" {
  connection_id   = auth0_connection.this.id
  enabled_clients = [auth0_client.this.id]
}

resource "auth0_user" "this" {
  depends_on = [auth0_connection_clients.this]

  connection_name = auth0_connection.this.name
  email           = var.auth0_user_email
  password        = var.auth0_user_password
}

```

### Auth0 Terraform Provider version

1.0.0

### Terraform version

v1.6.0

**Comment by leonseng** [comment]
Solved this by adding the `API Explorer Application` application into the `auth0_connection_clients.enabled_clients` list

```
data "auth0_connection" "api_explorer_app" {
  name = "API Explorer Application"
}

resource "auth0_connection_clients" "this" {
  connection_id   = auth0_connection.this.id
  enabled_clients = [data.auth0_connection.api_explorer_app.id, auth0_client.this.id]
}
```

**Comment by sergiught** [comment]
Hey @leonseng 👋🏻 

Apologies for the late reply and awesome to hear you were able to solve the issue. 

To clarify further, you were encountering the error message because the client you were leveraging to authenticate on the terraform provider was not added to the enabled clients of the connection you wanted to create a user through. 

When creating users directly through the provider like that, the client that creates the user is actually the one you authenticate on the provider with, and that has to have the connection enabled for it. 

Hope this makes sense, let me know if you have any other questions.
