### ISSUE TITLE
Allow us to set "Use Custom Domain in Emails"

### ISSUE THREAD

**Issue by Vannevelj** [auth0/terraform-provider-auth0#869]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

This checkbox exists in the UI to use the custom domain in emails (e.g. password reset) but I can't find the equivalent in Terraform. Am I overlooking it perhaps?

<img width="293" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/2777107/64d26c0f-6dcf-4ec9-b385-c046560a046c">

### Describe the ideal solution

A flag in terraform that allows me to turn this on.

**Comment by Will956** [comment]
Hello, as far as I can understand it lives under `auth0_tenant` resource as a flag here https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/tenant#enable_custom_domain_in_emails.

**Comment by sergiught** [comment]
Hey @Vannevelj 👋🏻  as @Will956 mentioned this is already supported through the tenant flags property linked above.
