### ISSUE TITLE
Creating a SPA sets client credentials authentication method to client secret post

### ISSUE THREAD

**Issue by TaylorBriggs** [auth0/terraform-provider-auth0#872]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When creating a SPA, the `auth0_client_credentials` resource gets created with `authentication_method = "client_secret_post"` by default. [This issue](https://github.com/auth0/terraform-provider-auth0/issues/545) suggests it should be created with "none", as appropriate for SPA.

### Expectation

The `authentication_method` should be set to "none" for a SPA.

### Reproduction

Given a resource defined like so:

```tf
resource "auth0_client" "frontend_client" {
  name        = "name"
  description = "description"

  client_metadata = {} # some real values here

  app_type = "spa"

  # filled with real values
  initiate_login_uri  = ""
  callbacks           = []
  allowed_origins     = ""
  allowed_logout_urls = ""
  web_origins         = []

  oidc_conformant = true
  logo_uri        = "logo_uri"
  grant_types     = [
    "refresh_token",
    "authorization_code",
    "http://auth0.com/oauth/grant-type/mfa-otp"
  ]
  is_first_party  = true

  jwt_configuration {
    alg = "RS256"
  }

  refresh_token {
    rotation_type                = "rotating"
    expiration_type              = "expiring"
    token_lifetime               = 43200 # 12 hours
    idle_token_lifetime          = 28800 # 8 hours
    infinite_idle_token_lifetime = false
  }
}
```

When the resource is created, the token endpoint authentication method is set to `client_secret_post` instead of `none`.

This can be consistently reproduced.

![Screenshot 2023-11-06 at 9 31 52 AM](https://github.com/auth0/terraform-provider-auth0/assets/1335519/bf7aac56-8433-4d34-b5c9-0837300018b5)
![Screenshot 2023-11-06 at 9 30 14 AM](https://github.com/auth0/terraform-provider-auth0/assets/1335519/46ade27d-8a1a-4630-ac01-560b12619952)

### Auth0 Terraform Provider version

1.0.0

### Terraform version

1.5.6

**Comment by sergiught** [comment]
Hey @TaylorBriggs 👋🏻 

Thanks for raising this with us. To manage a client's authentication method, please use the https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/client_credentials resource, until we can look into adding these defaults as well when creating the client through the `auth0_client` resource.

Example:
```terraform
resource "auth0_client" "frontend_client" {
  name        = "name"
  description = "description"
  app_type = "spa"
  #other config parameters ...
}

resource "auth0_client_credentials" "creds_for_frontend_client" {
  client_id = auth0_client.frontend_client.id
  authentication_method = "none"
}
```

**Comment by sergiught** [comment]
Hey folks, this has been now fixed within https://github.com/auth0/terraform-provider-auth0/releases/tag/v1.1.0.
