### ISSUE TITLE
Attempting to create auth0_log_stream of type "eventgrid" returns 400

### ISSUE THREAD

**Issue by WietseDeKoninckPXL** [auth0/terraform-provider-auth0#886]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The following config resource 
```
"auth0_log_stream" "eventgrid-partnertopic-logstream" {

  depends_on = [azapi_resource.eventgrid-partners-configuration]
  name = "${var.common.resource_prefix}-azure-eventgrid-logstream"
  type = "eventgrid"
  status = "active"
  sink {
    azure_region = var.common.location (-> "westeurope")
    azure_resource_group = var.azure_resource_group
    azure_subscription_id = var.azure_subscription_id
    azure_partner_topic = "${var.common.resource_prefix}-<redacted>"# We specify this explicitly according to our naming convention
  }
}
```

fails with 400 Bad Request: Payload validation error: 'Data does not match any schemas from 'oneOf''.

### Expectation

Creating the resource works or a clear validation error is shown.

### Reproduction

1. Create a auth0_log_stream with type "eventgrid" (maybe also eventbridge)
2. Fails with 400 Bad Request: Payload validation error: 'Data does not match any schemas from 'oneOf''.

### Auth0 Terraform Provider version

1.0.0

### Terraform version

1.5

**Comment by WietseDeKoninckPXL** [comment]
UPDATE: Removing the status attribute does not fix the issue. Possibly there is something wrong with the region field validation?

**Comment by WietseDeKoninckPXL** [comment]
I found the root cause: setting azure_partner_topic. It is also not specified as an allowed value on the Management API

**Comment by sergiught** [comment]
Hey @WietseDeKoninckPXL 👋🏻 

Thanks for raising this with us. Indeed the `azure_partner_topic` parameter is computed and shouldn't be specified when creating the log stream, but it is something that gets generated after creation. You can reference it as `auth0_log_stream.eventgrid-partnertopic-logstream.azure_partner_topic` within your config. This is also mentioned in the docs: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/log_stream#azure_partner_topic.

Let me know if you have any other questions!

**Comment by WietseDeKoninckPXL** [comment]
> Hey @WietseDeKoninckPXL 👋🏻
> 
> Thanks for raising this with us. Indeed the `azure_partner_topic` parameter is computed and shouldn't be specified when creating the log stream, but it is something that gets generated after creation. You can reference it as `auth0_log_stream.eventgrid-partnertopic-logstream.azure_partner_topic` within your config. This is also mentioned in the docs: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/log_stream#azure_partner_topic.
> 
> Let me know if you have any other questions!

What you say is not entirely correct in my opinion. In case specifying the property is not supported AT ALL, it should not be included on the resource's input attributes (only on export attributes). The documentation AS IS states that it could be specified, but notes that it 'generally'? should not be specified: `[azure_partner_topic](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/log_stream#azure_partner_topic)(String) Name of the Partner Topic to be used with Azure. Generally should not be specified.` 

At least a clarification to the documentation is in order, but the resource should be updated as well imo.
