### ISSUE TITLE
OIDC's `pkce` setting case mismatch

### ISSUE THREAD

**Issue by tomasz-torcz-airspace-intelligence** [auth0/terraform-provider-auth0#895]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using `auth0_connection` with strategy `oidc`, setting for `pkce` type isn't accepted. Documentation states that `s256` (lowercase `s`) is correct, yet I receive an error on apply:

> `Error: 400 Bad Request: "options.connection_settings.pkce" must be one of [auto, S256, plain, disabled]`

After changing to uppercase `S`, there's still an error, but different:

> `Error: expected options.0.connection_settings.0.pkce to be one of [auto s256 plain disabled], got S256`

I worked around the issue by setting pkce to `auto`, which should translate to s256.

Note: I did not upgrade to latest provider version, as there are no commits touching OIDC.

### Expectation

Value described in documentation should be accepted. Ideally, case of `s` shouldn't matter.

### Reproduction

```
resource "auth0_connection" "oidc-connection" {
  strategy     = "oidc"
  connection_settings {
    pkce = "S256"
  }
}
```

Should be accepted.

### Auth0 Terraform Provider version

1.0.0

### Terraform version

1.5.2

**Comment by sergiught** [comment]
This is now fixed and available through https://registry.terraform.io/providers/auth0/auth0/1.1.2.
