### ISSUE TITLE
Can't create auth0 connection, client and user

### ISSUE THREAD

**Issue by iRoachie** [auth0/terraform-provider-auth0#90]
### Describe the problem

Hey team, been trying out the provider for an upcoming project and ran into some issues. Not sure if I'm doing something wrong, but I'm unable to create a username-password connection, along with a client, and user.

The error seems to be at the stage of creating the user:

```
Error: 400 Bad Request: connection is disabled
```

When I check the console the connection is enabled for the app client. I'm at a lost here.

### What was the expected behavior?

The user should be created under the connection created.

### Reproduction

```tf
resource "auth0_client" "app-client" {
  name                = "My App Client"
  app_type            = "regular_web"
  callbacks           = ["http://localhost:3000/api/auth/callback"]
  allowed_logout_urls = ["http://localhost:3000/"]
}

resource "auth0_connection" "connection" {
  name            = "Email-Password-Authentication"
  strategy        = "auth0"
  enabled_clients = [auth0_client.app-client.id]

  options {
    disable_signup   = true
    password_policy  = "good"
  }
}

resource "auth0_user" "user" {
  connection_name = auth0_connection.connection.name
  name            = "Tester Test"
  email           = "tester.test@gmail.com"
  email_verified  = true
  password        = "passpass$12$12"
}
```

### Environment

- **Version of `terraform-provider-auth0` used:** 0.28.1

**Comment by sergiughf** [comment]
Hey @iRoachie, thanks for opening this issue. Have you tried adding a depends_on on the connection and user resources? e.g.

```hcl
resource "auth0_client" "app-client" {
  name                = "My App Client"
  app_type            = "regular_web"
  callbacks           = ["http://localhost:3000/api/auth/callback"]
  allowed_logout_urls = ["http://localhost:3000/"]
}

resource "auth0_connection" "connection" {
  name            = "Email-Password-Authentication"
  strategy        = "auth0"
  enabled_clients = [auth0_client.app-client.id]

  options {
    disable_signup   = true
    password_policy  = "good"
  }
 depends_on = [auth0_client.app-client]
}

resource "auth0_user" "user" {
  connection_name = auth0_connection.connection.name
  name            = "Tester Test"
  email           = "tester.test@gmail.com"
  email_verified  = true
  password        = "passpass$12$12"
  depends_on = [auth0_connection.connection]
}
```

**Comment by iRoachie** [comment]
@sergiughf can confirm that the issue is still present after using `depends_on`

**Comment by Gibstick** [comment]
I ran into this today and it seems to be a common pitfall with the Auth0 management API. You can see someone asking about this in the Auth0 community forums: https://community.auth0.com/t/post-api-v2-users-connection-is-disabled/53641

The M2M application you use to run the terraform needs to be enabled in the connection that the user is being created with.

**Comment by iRoachie** [comment]
Pleased to report that this worked! Thanks a ton @Gibstick
