### ISSUE TITLE
[Docs] auth0_role_permission and auth0_role_permissions documentation pages do not include instructions on importing resources.

### ISSUE THREAD

**Issue by BPerry24** [auth0/terraform-provider-auth0#919]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

There is no section in the [auth0_role_permission docs](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/role_permission) and [auth0_role_permissions docs](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/role_permission) regarding the ability to import the resources.

I was able to import an auth0_role_permission following a similar strategy outlined in the [auth0_user_permission docs](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/user_permission#import):

`terraform import auth0_role_permission.this <roleID>::<resourceServerIdentifier>::<permission>`

I did not test the strategy on the auth0_role_permissions resource.

### Expectation

A section in both docs instructing method of import for these resources.

### Reproduction

N/A

### Auth0 Terraform Provider version

1.1.2

### Terraform version

N/A

**Comment by developerkunal** [comment]
Hi @BPerry24,

I hope you're having a nice day!

I apologize for the late response, but I wanted to inform you that we have added the documentation in PR #963. Although it has been merged, it has not yet been released. We anticipate its release soon. Thank you for your patience.

Best regards,

**Comment by developerkunal** [comment]
Hey @kikeyama,

Good news! The docs have been updated to version 1.2.1. Take a look when you get a chance, and if you run into any more issues, just give me a shout.
