### ISSUE TITLE
Incorrect documentation on datasource_auth0_client

### ISSUE THREAD

**Issue by nclaeys** [auth0/terraform-provider-auth0#92]
### Describe the problem

The docs mention that the attribute reference of datasource_auth0_client is the same as in the resource auth0_client except for client_secret_rotation_trigger. This is however not in line with the source code as it also does not contain client_secret.

### What was the expected behavior?
I would like to have client_secret being exposed from the datasource but otherwise update the docs to also mention that client_secret is not exposed.

### Reproduction

/

### Environment
/

**Comment by willvedd** [comment]
Thanks for the question. We've intentionally omitted `client_secret` from the data source to prevent accidental exposure. However, we would be open to the idea if there was a reasonable use case. Can you explain what you're attempting to accomplish here?

**Comment by sergiughf** [comment]
Closing this down as this is now available through https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.29.0.
