### ISSUE TITLE
Add support for button logo URL in connection

### ISSUE THREAD

**Issue by tomliversidge** [auth0/terraform-provider-auth0#93]
We are able to set the `show_as_button` [option on a connection](https://github.com/auth0/terraform-provider-auth0/blob/81c4641e15a22057202cf0b0cb9dac7a9cf6be71/auth0/resource_auth0_connection.go#L667), but not able to add a button logo url.

It would be nice to support this when configuring the connection

![CleanShot 2022-03-21 at 10 08 40](https://user-images.githubusercontent.com/1437372/159224460-026e3da9-725b-4d8b-aecd-3910c6a34b93.png)

**Comment by sergiughf** [comment]
Hey @tomliversidge 👋🏻 , thanks for opening this issue. Have you tried the options.icon_url param to configure that url? This should already be possible using that one. I'm posting an example below:

```
resource "auth0_connection" "aad" {
  name     = "microsoft-azure-AD"
  strategy = "waad"
  show_as_button = true
  display_name = "Login with AD"
  options {
    icon_url = "https://my.domain/logo.png"
  }
}
```

Let us know in case you're encountering any issues with that as it should work.

**Comment by tomliversidge** [comment]
Yes thanks, that works!
