### ISSUE TITLE
several attributes cause plan spam with their defaults

### ISSUE THREAD

**Issue by DavidS-ovm** [auth0/terraform-provider-auth0#930]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Several attributes across the module cause spurious plan changes when the attributes should be set to their defaults.

This happens at least for auth0_connection.set_user_root_attributes, auth0_client.sso, and auth0_client.organization_require_behavior.

This might only happen after touching the attribute once.

### Expectation

terraform resources should not show up in the plan if there is no actual change.

### Reproduction

1. Given...

this resource decl

```
resource "auth0_connection" "customer_connection" {
  name         = var.terraform_env_name == "prod" ? "customer" : "dev"
  display_name = "customer SSO (${var.terraform_env_name})"
  strategy     = "samlp"

  options {
    debug         = var.terraform_env_name != "prod"
    tenant_domain = var.auth0_domain

    metadata_xml = file(var.terraform_env_name == "prod" ? "sso-metadata/customer.xml" : "sso-metadata/dev.xml")

    # TODO
    icon_url = "https://saml.provider/assets/logo.png"

    signature_algorithm = "rsa-sha256"
    digest_algorithm    = "sha256"
  }
}
```

2. When ...

running `terraform plan`

3. Then ...

This message pops up, while `set_user_root_attributes` defaults to `on_each_login`

```
  # auth0_connection.customer_connection will be updated in-place
  ~ resource "auth0_connection" "customer_connection" {
        id                   = "con_REDACTED"
        name                 = "dev"
        # (6 unchanged attributes hidden)

      ~ options {
          - set_user_root_attributes             = "on_each_login" -> null
            # (36 unchanged attributes hidden)
        }
    }
```

### Auth0 Terraform Provider version

registry.terraform.io/auth0/auth0 v1.2.0

### Terraform version

Terraform v1.5.7

**Comment by ad8lmondy** [comment]
Yes, I can confirm I see the same issue with Terraform v1.6.2

```
  # module.sre__auth0-module.auth0_client.application["Studio"] will be updated in-place
  ~ resource "auth0_client" "application" {
        id                                    = "xxx"
        name                                  = "STAGE: Studio "
      - sso                                   = true -> null
        # (22 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # module.sre__auth0-module.auth0_client.application["M-Files and HubShare"] will be updated in-place
  ~ resource "auth0_client" "application" {
        id                                    = "x"
        name                                  = "STAGE: M-Files and HubShare"
      - sso                                   = true -> null
        # (21 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # module.sre__auth0-module.auth0_client.application["Product Support Portal"] will be updated in-place
  ~ resource "auth0_client" "application" {
        id                                    = "xxx"
        name                                  = "STAGE: Product Support Portal"
      - sso                                   = true -> null
        # (21 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # module.sre__auth0-module.auth0_connection.aad["AAD"] will be updated in-place
  ~ resource "auth0_connection" "aad" {
        id                   = "con_xyz"
        name                 = "AAD"
        # (6 unchanged attributes hidden)

      ~ options {
          - set_user_root_attributes               = "on_each_login" -> null
            # (37 unchanged attributes hidden)
        }
    }
```

**Comment by DavidS-ovm** [comment]
Hey folks, my account manager has advised me to contact Auth0 support to get this ticket prioritized with engineering. The current status is 

> I am just reaching out to update you that the internal ticket is still in progress.
>
> I will return as soon as any updates occur. 

from nine days ago on a ticket I opened three weeks ago. It might be useful if any customer on this ticket also contacted support pointing out that there is already an engineering ticket for this, and to add your weight (i.e. revenue) to that.

Thanks for listening.

**Comment by duedares-rvj** [comment]
Hello!
Sorry about a delayed response on this.

Could we try setting a value for these field in the resource definition.
Whichever field points as the source of a noisy plan, setting them explicitly should remove the noise.

Let us know how it goes.

**Comment by duedares-rvj** [comment]
@DavidS-ovm 
Following up on this, is this still an issue?

**Comment by DavidS-ovm** [comment]
Hi,

this seems to have vanished but was cloaked by the noise caused by #1029
