### ISSUE TITLE
totp is always applied

### ISSUE THREAD

**Issue by njlr** [auth0/terraform-provider-auth0#935]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Here is my resource:

```hcl
resource "auth0_connection" "app" {
  name                 = "App"
  is_domain_connection = true
  strategy             = "auth0"

  options {
    disable_signup   = true
    api_enable_users = false

    brute_force_protection = true

    password_policy = "fair"

    password_history {
      enable = true
      size   = 3
    }

    password_complexity_options {
      min_length = 12
    }

    totp {
      time_step = 300
      length    = 6
    }

    mfa {
      active                 = true
      return_enroll_settings = true
    }
  }
}
```

When I apply this, I get this change:

```
 ~ resource "auth0_connection" "app" {
        id                   = "con_xxxxxxxx"
        name                 = "App"
        # (4 unchanged attributes hidden)

      ~ options {
            # (30 unchanged attributes hidden)

          + totp {
              + length    = 6
              + time_step = 300
            }

            # (3 unchanged blocks hidden)
        }
    }
```

When I apply it for a second time, the change is the same!

### Expectation

It should apply once and then require no more changes (or throw an error)

### Reproduction

(see above)

### Auth0 Terraform Provider version

1.2.0

### Terraform version

1.7.5

**Comment by developerkunal** [comment]
Hey @njlr,

Hope you're doing well!

It seems that totp is not recognized as an attribute in the Terraform Auth0 provider for the Auth0 strategy for connection resources. This might be the reason why it's not updating as expected.

**Comment by developerkunal** [comment]
Hi @njlr,

I hope you're doing well!

I will be closing this issue. If you encounter any other issues, please open a new issue.

**Comment by njlr** [comment]
> It seems that totp is not recognized as an attribute in the Terraform Auth0 provider for the Auth0 strategy for connection resources. This might be the reason why it's not updating as expected.

Is this intended behavior? It seems like a bug to me.

**Comment by developerkunal** [comment]
Hi @njlr ,

I hope you're having a pleasant day!

I just wanted to inform you that I'll be closing this issue shortly. However, if you have any more issues or questions, please feel free to open a new one. I'm here to assist you further.

Thank you for your cooperation.

Best regards,
