### ISSUE TITLE
auth0 cli not importing email templates, hooks and rules

### ISSUE THREAD

**Issue by tranceporter** [auth0/terraform-provider-auth0#943]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello,

I am using latest cli (1.4.0) and latest tf provider version (1.2.0). I am using TF version 1.6.x. I have generated an M2M app for Terraform import with full access (All scopes checked) to Auth0 Management API. From what I can see, I have one "auth0_connection" of type email that has a default template (lots of flattened and escaped html), but there are no auth0_email_template resources or hooks or rules. I ran the cli command to list email templates, and I can see all of them.

<img width="595" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/1443060/a75471a5-79f0-406e-8598-bfadf84bcb9f">

Rules

<img width="563" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/1443060/db5c71d6-7842-44ee-9472-fcc79ca6a97a">

I cannot seem to find cli command for showing hooks, so unsure how to list them. I have instead taken screenshots from UI.

<img width="1082" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/1443060/e293a719-96e3-44f4-8227-071f15da7c65">

<img width="1049" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/1443060/949b85cc-ffc0-4791-910f-4738bd9fac1a">

We are using SNS for SMS MFA, and none of that configuration seems to have been imported. I have tried adding the --debug flag to auth0 tf generate command, and I do not get any errors (in fact there is no debug output)

<img width="810" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/1443060/c7011448-7807-4ebd-8890-6fd6f1dc225f">

Can you please guide me?

Thanks,
Shreyas

### Expectation

All resources should be imported into terraform by Auth0 CLI. Since hooks and rules will not be deprecated by Nov 2024, we should still have time to migrate them over.

### Reproduction

Given that auth0 cli has full access to Auth0 Management API, auth0 tf generate should import all resources in tf configuration.

### Auth0 Terraform Provider version

1.2.0

### Terraform version

1.6.4

**Comment by tranceporter** [comment]
To add to the above, I just checked the auth0 cli page, and none of the missing resources above seem to be listed in auth0 tf generate docs

  --force               Skip confirmation.
  -o, --output-dir string   Output directory for the generated Terraform config files. If not provided, the files will be saved in the current working directory. (default "./")
  -r, --resources strings   Resource types to generate Terraform config for. If not provided, config files for all available resources will be generated. (default **[auth0_action,auth0_attack_protection,auth0_branding,auth0_client,auth0_client_grant,auth0_connection,auth0_custom_domain,auth0_email_provider,auth0_guardian,auth0_organization,auth0_pages,auth0_prompt,auth0_prompt_custom_text,auth0_resource_server,auth0_role,auth0_tenant,auth0_trigger_actions])**

Does this mean I cannot import them? Or maybe I need an older version of cli?

**Comment by duedares-rvj** [comment]
@tranceporter Hello. Apologies for a delayed response on this.
Your understanding is correct that we presently only support a limited number of resources while exporting from auth0 cli. 

Ideally, adding a new fetcher on the below file should allow an import of hooks/rules.
https://github.com/auth0/auth0-cli/blob/main/internal/cli/terraform.go

Having said that, since we have plans on deprecating `hooks` and `rules` and moving to `actions`, I cannot provide a certainty or a timeline if we'd extend the CLI's functionality to support a near deprecating resource.

Also, if you're at a point where you must need this feature, you may refer to this small PR which highlights how we can add a new resource:
https://github.com/auth0/auth0-cli/pull/833/files

Once the changes are made, you can install that version of the cli by running `make install` and then go on to import hooks/rules etc.

I hope this is helpful to you.
Appreciate your understanding.
