### ISSUE TITLE
Client creation suddenly no longer working with oauth2: "server_error" "callback is not a function"

### ISSUE THREAD

**Issue by guineveresaenger** [auth0/terraform-provider-auth0#944]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

A test program that has been working up until this weekend suddenly started failing with the error `oauth2: "server_error" "callback is not a function"`. No code was changed; the program suddenly stopped working as expected.

### Expectation

I expected a Client resource to be created, as previously possible.

To be clear, this is something that suddenly stopped working, with no changes on our end to conviguration, variables, or code. It was working for the most recent provider version right up until some time a few days ago.

It would be great to have more insight on the particular error message as well.

### Reproduction

Running `terraform apply` on the following example code:

```
provider "auth0" {
  domain         = <OUR_DOMAIN>
  client_id      = <OUR_ID>
  client_secret  = <OUR_SECRET>
}

# Create a new Auth0 client
resource "auth0_client" "my_client" {
  name                                = "Application - Acceptance Test"
  app_type                            = "non_interactive"
  custom_login_page_on                = true
  is_first_party                      = true
  oidc_conformant                     = false
  callbacks                           = ["https://example.com/callback"]
  allowed_origins                     = ["https://example.com"]
  allowed_logout_urls                 = ["https://example.com"]
  web_origins                         = ["https://example.com"]
  grant_types = [
    "authorization_code",
    "http://auth0.com/oauth/grant-type/password-realm",
    "implicit",
    "password",
    "refresh_token"
  ]
  client_metadata = {
    foo = "zoo"
  }
}
```

results in:

```
 auth0_client.my_client: Creating...
╷
│ Error: failed to send the request: Post "https://<OUR_DOMAIN>/api/v2/clients": oauth2: "server_error" "callback is not a function"
│ 
│   with auth0_client.my_client,
│   on auth0_client.tf line 18, in resource "auth0_client" "my_client":
│   18: resource "auth0_client" "my_client" {
│ 
╵
```

### Auth0 Terraform Provider version

v1.2.0

### Terraform version

v1.5.7

**Comment by developerkunal** [comment]
Hi @guineveresaenger,

I hope you're having a great day!

I attempted to replicate the error on my end, but I wasn't able to encounter it while using your resource configuration. Could you provide me with more information about the issue so that I can assist you further?

**Comment by developerkunal** [comment]
Hey @guineveresaenger,

I hope you're doing well today! I wanted to reach out and apologize for any confusion my last message might have caused. I truly want to make sure everything is clear and easy for you.

So, about the configuration you're using:

```hcl
provider "auth0" {
  domain         = <OUR_DOMAIN>
  client_id      = <OUR_ID>
  client_secret  = <OUR_SECRET>
}

# Create a new Auth0 client
resource "auth0_client" "my_client" {
  name                                = "Application - Acceptance Test"
  app_type                            = "non_interactive"
  custom_login_page_on                = true
  is_first_party                      = true
  oidc_conformant                     = false
  callbacks                           = ["https://example.com/callback"]
  allowed_origins                     = ["https://example.com"]
  allowed_logout_urls                 = ["https://example.com"]
  web_origins                         = ["https://example.com"]
  grant_types = [
    "authorization_code",
    "http://auth0.com/oauth/grant-type/password-realm",
    "implicit",
    "password",
    "refresh_token"
  ]
  client_metadata = {
    foo = "zoo"
  }
}
```

It seems you're using `<Domain>` as the domain. My suggestion would be to take a look at your configuration to ensure everything is set up correctly. 

Also, I just wanted to clarify something from my last message. In my previous comment, I mentioned that I'm unable to reproduce the issue you're experiencing. This is because I've ensured that the configuration on my end is correct. If you have any further questions or need assistance, please feel free to let me know. I'm here to help!
