### ISSUE TITLE
Add support for auth0_tenant.error_page

### ISSUE THREAD

**Issue by alex-jobber** [auth0/terraform-provider-auth0#966]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would like to manage the `error_page` settings of my Auth0 tenant through Terraform.

### Describe the ideal solution

Within an Auth0 tenant block I can specify the error page settings
```
resource "auth0_tenant" "main" {
  ...

  error_page {
    url = "https://example.com/500.html"
  }
```

### Additional context

It's possible to do this through [the management API](https://auth0.com/docs/api/management/v2/tenants/patch-settings) but the [Auth0 Terraform provider](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/tenant) does not support it.

**Comment by sergiught** [comment]
Hey @alex-jobber 👋🏻 

This is already supported through https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/pages. 

Let us know if you encounter any issues with the resource!
