### ISSUE TITLE
OIDC Connection Requires Over-Specification (Again?)

### ISSUE THREAD

**Issue by dh-abaird** [auth0/terraform-provider-auth0#969]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

As recently as February, when creating an `auth0_connection` of `strategy` `oidc`, I was able to supply only the `discovery_url` and Auth0 would pull the other settings from the JSON response (`authorization_endpoint`, `jwks_uri`, etc.). As of today, when trying to do the same thing, with say, this example config:

```
resource "auth0_connection" "oidc" {
  name           = "oidc-connection"
  display_name   = "OIDC Connection"
  strategy       = "oidc"
  show_as_button = false

  options {
    client_id      = "1234567"
    client_secret  = "1234567"
    domain_aliases = ["example.com"]
    type           = "back_channel"
    discovery_url  = "https://www.paypalobjects.com/.well-known/openid-configuration"
    scopes         = ["openid", "email"]

    connection_settings {
      pkce = "auto"
    }
  }
}
```

The management API throws an HTTP 400:

```
Error: 400 Bad Request: "options.issuer" must be a string
```

It's not until I manually add `issuer`, `authorization_endpoint`, and `jwks_uri`, all of which are present in the response from the discovery URL, that the apply completes successfully. As mentioned previously, this didn't use to be the case, and indeed isn't the case now if I create the connection using the dashboard, where all I have to do is enter the `OpenID Connect Discovery URL`.

Feels like a potential recurrence of [this issue](https://github.com/auth0/terraform-provider-auth0/issues/238), however given the connection is created fine from the dashboard I'm guessing it isn't a problem with the management API.

### Expectation

When `discovery_url` is provided I expect `issuer`, `authorization_endpoint`, and `jwks_uri` to be extracted automatically

### Reproduction

As per the description above 👆

### Auth0 Terraform Provider version

1.2.0

### Terraform version

1.5.7

**Comment by mikeaddresscloud** [comment]
Also experiencing this issue.  Thanks for reporting.

**Comment by craig-a-vinet** [comment]
Also experiencing this issue. I've only started using TF, but this is the first issue I've come across. Sorry that it's new-ish

**Comment by bendiknesbo** [comment]
> I've only been using this provider for a morning and have already been very frustrated by this. There is actually a worse level here too. You have to specify `discovery_url` to create a connection, but, once created you have to remove `discovery_url` otherwise every plan/apply adds the `discovery_url`.

We have also stumbled into this. We are hesitant to remove the `discovery_url`, as then a recreation of the connection, or applying our Terraform to a new Auth0-tenant would not work.

We are thus leaving the `discovery_url` there, and then every apply will attempt to modify the connection, even though there are no real changes.

**Comment by bendiknesbo** [comment]
We are no longer getting the diff. Maybe this has been fixed on the API-side?

**Comment by dh-abaird** [comment]
@bendiknesbo I believe you're right, it's now possible to add an OIDC connection with only the discovery URL.

Closing this ...
